from __future__ import annotations

import json
import subprocess
import sys
import zipfile
from pathlib import Path

import rextio.build.orchestrator as orchestrator
from rextio.cli.main import main
from rextio.codegen.rust.generator import RustCodegenError


def test_build_generates_rust_project_for_accepted_native_only(
    tmp_path: Path,
    capsys,
    fake_cargo: Path,
) -> None:
    (tmp_path / "rextio.toml").write_text(
        """
[policy]
native_marker = "decorator"
""",
        encoding="utf-8",
    )
    (tmp_path / "app.py").write_text(
        """
import rextio

@rextio.native
def add(a: int, b: int) -> int:
    return a + b

def helper(x: int) -> int:
    return x + 1

@rextio.native
def rejected(x: int) -> int:
    return helper(x)
""",
        encoding="utf-8",
    )

    exit_code = main(["build", str(tmp_path), "--fallback=cpython"])

    captured = capsys.readouterr()
    rust_dir = tmp_path / ".rextio" / "generated" / "rust"
    python_dir = tmp_path / ".rextio" / "generated" / "python"
    build_python_dir = tmp_path / ".rextio" / "build" / "python"
    dist_dir = tmp_path / "dist"
    lib_rs = rust_dir / "src" / "lib.rs"
    app_py = python_dir / "app.py"
    fallback_app_py = python_dir / "_fallback_app.py"
    build_report = tmp_path / ".rextio" / "reports" / "build.json"

    assert exit_code == 0
    assert "generated Rust project" in captured.out
    assert "generated Python package tree" in captured.out
    assert "build artifact" in captured.out
    assert (rust_dir / "Cargo.toml").exists()
    assert (rust_dir / ".cargo" / "config.toml").exists()
    assert (rust_dir / "pyproject.toml").exists()
    assert lib_rs.exists()
    assert "fn app__add(a: i64, b: i64) -> PyResult<i64>" in lib_rs.read_text(encoding="utf-8")
    assert "fn rejected" not in lib_rs.read_text(encoding="utf-8")
    assert app_py.exists()
    assert fallback_app_py.exists()
    assert (build_python_dir / "app.py").exists()
    assert (build_python_dir / "_fallback_app.py").exists()
    assert (build_python_dir / "rextio" / "__init__.py").exists()
    assert (build_python_dir / "rextio" / "runtime" / "flags.py").exists()
    wrapper_source = app_py.read_text(encoding="utf-8")
    assert wrapper_source.startswith("# Generated by Rextio. Do not edit manually.")
    assert "from _fallback_app import *  # noqa: F401,F403" in wrapper_source
    assert "def add(a: int, b: int) -> int:" in wrapper_source
    assert "def rejected" not in wrapper_source
    assert "def rejected" in fallback_app_py.read_text(encoding="utf-8")
    data = json.loads(build_report.read_text(encoding="utf-8"))
    assert data["status"] == "built"
    assert data["accepted_native_count"] == 1
    assert data["rejected_native_count"] == 1
    assert data["generated_python"] == str(python_dir)
    assert data["build_python"] == str(build_python_dir)
    assert data["native_build"]["status"] == "built"
    assert Path(data["native_build"]["installed_path"]).exists()
    assert data["wheel_build"]["status"] == "built"
    assert Path(data["wheel_build"]["path"]).exists()
    assert Path(data["wheel_build"]["path"]).is_relative_to(dist_dir)
    assert "wheel artifact" in captured.out
    with zipfile.ZipFile(data["wheel_build"]["path"]) as archive:
        names = set(archive.namelist())
    assert "app.py" in names
    assert "_fallback_app.py" in names
    assert "rextio/runtime/flags.py" in names
    assert any(name.endswith(".dist-info/WHEEL") for name in names)
    assert any(name.endswith(".dist-info/RECORD") for name in names)


def test_build_embeds_fallback_threshold(
    tmp_path: Path,
    capsys,
    fake_cargo: Path,
) -> None:
    (tmp_path / "app.py").write_text(
        """
def add(a: int, b: int) -> int:
    return a + b
""",
        encoding="utf-8",
    )

    exit_code = main(["build", str(tmp_path), "--fallback=cpython", "--fallback-threshold=4"])

    captured = capsys.readouterr()
    report = json.loads(
        (tmp_path / ".rextio" / "reports" / "build.json").read_text(encoding="utf-8")
    )
    wrapper_source = (
        tmp_path / ".rextio" / "build" / "python" / "app.py"
    ).read_text(encoding="utf-8")

    assert exit_code == 0
    assert "boundary fallback threshold: 4" in captured.out
    assert report["boundary_fallback_threshold"] == 4
    assert 'boundary_fallback_required("app.add", 4)' in wrapper_source


def test_build_generates_zipapp_executable(
    tmp_path: Path,
    capsys,
    fake_cargo: Path,
) -> None:
    package = tmp_path / "src" / "demo_cli"
    package.mkdir(parents=True)
    (package / "__init__.py").write_text("", encoding="utf-8")
    (package / "app.py").write_text(
        """
def main() -> int:
    print("zipapp ok")
    return 0
""",
        encoding="utf-8",
    )

    exit_code = main(
        [
            "build",
            str(tmp_path),
            "--fallback=cpython",
            "--entrypoint=demo_cli.app:main",
            "--executable-name=demo-tool",
        ]
    )

    captured = capsys.readouterr()
    report = json.loads(
        (tmp_path / ".rextio" / "reports" / "build.json").read_text(encoding="utf-8")
    )
    executable = tmp_path / "dist" / "demo-tool.pyz"

    assert exit_code == 0
    assert "executable artifact: built" in captured.out
    assert f"executable: {executable}" in captured.out
    assert report["executable_build"]["status"] == "built"
    assert report["executable_build"]["path"] == str(executable)
    assert report["executable_build"]["entrypoint"] == "demo_cli.app:main"
    completed = subprocess.run(
        [sys.executable, str(executable)],
        check=True,
        capture_output=True,
        text=True,
    )
    assert completed.stdout.strip() == "zipapp ok"


def test_build_reports_invalid_zipapp_entrypoint(
    tmp_path: Path,
    capsys,
    fake_cargo: Path,
) -> None:
    (tmp_path / "app.py").write_text(
        """
def main() -> int:
    return 0
""",
        encoding="utf-8",
    )

    exit_code = main(["build", str(tmp_path), "--entrypoint=not-a-module"])

    captured = capsys.readouterr()
    report = json.loads(
        (tmp_path / ".rextio" / "reports" / "build.json").read_text(encoding="utf-8")
    )

    assert exit_code == 1
    assert "executable artifact: failed" in captured.out
    assert "Use module:function" in captured.out
    assert report["status"] == "executable-build-failed"
    assert report["executable_build"]["status"] == "failed"


def test_build_reports_native_build_failure_when_cargo_is_missing(
    tmp_path: Path,
    monkeypatch,
    capsys,
) -> None:
    monkeypatch.setenv("PATH", "")
    (tmp_path / "app.py").write_text(
        """
import rextio

@rextio.native
def add(a: int, b: int) -> int:
    return a + b
""",
        encoding="utf-8",
    )

    exit_code = main(["build", str(tmp_path), "--fallback=cpython"])

    captured = capsys.readouterr()
    build_report = tmp_path / ".rextio" / "reports" / "build.json"
    data = json.loads(build_report.read_text(encoding="utf-8"))

    assert exit_code == 1
    assert "RXT060 Build failed while compiling generated Rust module" in captured.out
    assert data["status"] == "native-build-failed"
    assert data["native_build"]["status"] == "failed"
    assert data["wheel_build"]["status"] == "skipped"
    assert data["wheel_build"]["path"] is None


def test_build_uses_maturin_when_available(
    tmp_path: Path,
    fake_maturin: Path,
    capsys,
) -> None:
    (tmp_path / "rextio.toml").write_text(
        """
[rust]
build_tool = "maturin"
""",
        encoding="utf-8",
    )
    (tmp_path / "app.py").write_text(
        """
import rextio

@rextio.native
def add(a: int, b: int) -> int:
    return a + b
""",
        encoding="utf-8",
    )

    exit_code = main(["build", str(tmp_path), "--fallback=cpython"])

    captured = capsys.readouterr()
    build_report = tmp_path / ".rextio" / "reports" / "build.json"
    data = json.loads(build_report.read_text(encoding="utf-8"))

    assert exit_code == 0
    assert "rust build tool: maturin" in captured.out
    assert data["native_build"]["tool"] == "maturin"
    assert Path(data["native_build"]["installed_path"]).exists()


def test_build_respects_cargo_build_tool_config(
    tmp_path: Path,
    fake_cargo: Path,
    capsys,
) -> None:
    (tmp_path / "rextio.toml").write_text(
        """
[rust]
build_tool = "cargo"
""",
        encoding="utf-8",
    )
    (tmp_path / "app.py").write_text(
        """
import rextio

@rextio.native
def add(a: int, b: int) -> int:
    return a + b
""",
        encoding="utf-8",
    )

    exit_code = main(["build", str(tmp_path), "--fallback=cpython"])

    captured = capsys.readouterr()
    build_report = tmp_path / ".rextio" / "reports" / "build.json"
    data = json.loads(build_report.read_text(encoding="utf-8"))

    assert exit_code == 0
    assert "rust build tool: cargo" in captured.out
    assert data["native_build"]["tool"] == "cargo"


def test_build_uses_configured_fallback_backend_when_argument_is_omitted(
    tmp_path: Path,
    monkeypatch,
    capsys,
) -> None:
    monkeypatch.setenv("PATH", "")
    (tmp_path / "rextio.toml").write_text(
        """
[build]
fallback_backend = "nuitka"
""",
        encoding="utf-8",
    )
    (tmp_path / "app.py").write_text(
        """
def add(a: int, b: int) -> int:
    return a + b
""",
        encoding="utf-8",
    )

    exit_code = main(["build", str(tmp_path)])

    captured = capsys.readouterr()

    assert exit_code == 1
    assert "Nuitka fallback was requested, but Nuitka is not installed." in captured.out


def test_build_fallback_argument_overrides_config(
    tmp_path: Path,
    fake_cargo: Path,
    capsys,
) -> None:
    (tmp_path / "rextio.toml").write_text(
        """
[build]
fallback_backend = "nuitka"

[rust]
build_tool = "cargo"
""",
        encoding="utf-8",
    )
    (tmp_path / "app.py").write_text(
        """
import rextio

@rextio.native
def add(a: int, b: int) -> int:
    return a + b
""",
        encoding="utf-8",
    )

    exit_code = main(["build", str(tmp_path), "--fallback=cpython"])

    captured = capsys.readouterr()
    build_report = tmp_path / ".rextio" / "reports" / "build.json"
    data = json.loads(build_report.read_text(encoding="utf-8"))

    assert exit_code == 0
    assert "fallback: cpython" in captured.out
    assert data["fallback"] == "cpython"


def test_build_reports_unsupported_configured_fallback_backend(
    tmp_path: Path,
    capsys,
) -> None:
    (tmp_path / "rextio.toml").write_text(
        """
[build]
fallback_backend = "unsupported"
""",
        encoding="utf-8",
    )

    exit_code = main(["build", str(tmp_path)])

    captured = capsys.readouterr()

    assert exit_code == 1
    assert "RXT060 Build failed while loading configuration." in captured.out
    assert "unsupported config value for [build].fallback_backend" in captured.out


def test_build_reports_unsupported_native_backend(
    tmp_path: Path,
    capsys,
) -> None:
    (tmp_path / "rextio.toml").write_text(
        """
[build]
native_backend = "llvm"
""",
        encoding="utf-8",
    )

    exit_code = main(["build", str(tmp_path)])

    captured = capsys.readouterr()

    assert exit_code == 1
    assert "RXT060 Build failed while loading configuration." in captured.out
    assert "unsupported config value for [build].native_backend" in captured.out


def test_build_respects_boundary_warnings_policy(
    tmp_path: Path,
    fake_cargo: Path,
    capsys,
) -> None:
    (tmp_path / "rextio.toml").write_text(
        """
[rust]
build_tool = "cargo"

[policy]
boundary_warnings = false
""",
        encoding="utf-8",
    )
    (tmp_path / "app.py").write_text(
        """
import rextio

@rextio.native
def score_one(x: float) -> float:
    return x * 2.0

def process_all(xs: list[float]) -> list[float]:
    out = []
    for x in xs:
        out.append(score_one(x))
    return out
""",
        encoding="utf-8",
    )

    exit_code = main(["build", str(tmp_path), "--fallback=cpython"])

    capsys.readouterr()
    check_report = tmp_path / ".rextio" / "reports" / "check.json"
    data = json.loads(check_report.read_text(encoding="utf-8"))

    assert exit_code == 0
    assert data["accepted_native"] == ["app.score_one"]
    assert data["diagnostics"] == []


def test_build_reports_clear_error_when_nuitka_is_missing(
    tmp_path: Path,
    monkeypatch,
    capsys,
) -> None:
    monkeypatch.setenv("PATH", "")
    (tmp_path / "app.py").write_text(
        """
def add(a: int, b: int) -> int:
    return a + b
""",
        encoding="utf-8",
    )

    exit_code = main(["build", str(tmp_path), "--fallback=nuitka"])

    captured = capsys.readouterr()

    assert exit_code == 1
    assert "RXT060 Build failed while preparing Nuitka fallback." in captured.out
    assert "Nuitka fallback was requested, but Nuitka is not installed." in captured.out
    assert "rextio build --fallback=cpython" in captured.out


def test_build_invokes_nuitka_when_requested_and_available(
    tmp_path: Path,
    fake_nuitka: Path,
    capsys,
) -> None:
    (tmp_path / "app.py").write_text(
        """
def add(a: int, b: int) -> int:
    return a + b
""",
        encoding="utf-8",
    )

    exit_code = main(["build", str(tmp_path), "--fallback=nuitka"])

    captured = capsys.readouterr()
    build_report = tmp_path / ".rextio" / "reports" / "build.json"
    data = json.loads(build_report.read_text(encoding="utf-8"))

    assert exit_code == 0
    assert "fallback: nuitka" in captured.out
    assert "fallback packaging: built" in captured.out
    assert data["fallback_build"]["backend"] == "nuitka"
    assert data["fallback_build"]["status"] == "built"
    assert data["fallback_build"]["command"]
    assert data["fallback_build"]["compiled_artifacts"]
    assert fake_nuitka.with_name("nuitka.log").exists()


def test_build_reports_codegen_failure_and_keeps_fallback(
    tmp_path: Path,
    monkeypatch,
    capsys,
) -> None:
    (tmp_path / "app.py").write_text(
        """
import rextio

@rextio.native
def add(a: int, b: int) -> int:
    return a + b
""",
        encoding="utf-8",
    )

    def fail_codegen(_module_ir):
        raise RustCodegenError("synthetic codegen failure")

    monkeypatch.setattr(orchestrator, "generate_rust_module", fail_codegen)

    exit_code = main(["build", str(tmp_path), "--fallback=cpython"])

    captured = capsys.readouterr()
    python_dir = tmp_path / ".rextio" / "generated" / "python"
    build_report = tmp_path / ".rextio" / "reports" / "build.json"
    data = json.loads(build_report.read_text(encoding="utf-8"))

    assert exit_code == 1
    assert "RXT050 Codegen failure" in captured.out
    assert data["status"] == "codegen-failed"
    assert data["native_build"]["tool"] == "codegen"
    assert (python_dir / "app.py").exists()
    assert (python_dir / "_fallback_app.py").exists()
