"""Focused tests for C6.2 host-extension wheel evidence emission."""

from __future__ import annotations

import hashlib
import json
import textwrap
from pathlib import Path

import pytest

from rextio.analyzer.models import ModuleAnalysis, ProjectAnalysis
from rextio.artifacts.models import ArtifactKind
from rextio.artifacts.profiles import detect_host_target_triple, host_extension_profile
from rextio.build.artifact_layout import ArtifactLayout
from rextio.build.cargo_builder import NativeBuildResult
from rextio.build.supply_chain import (
    EvidenceInputSnapshot,
    capture_cargo_lock_input,
    capture_generated_python_inputs,
    capture_generated_rust_inputs,
    capture_project_source_snapshot,
    emit_host_extension_wheel_evidence,
)
from rextio.build.wheel_builder import WheelBuildResult, build_artifact_wheel
from rextio.partition.build_plan import BuildPlan
from rextio.partition.fallback_plan import FallbackPlan
from rextio.partition.native_plan import NativePlan
from rextio.source.models import SourceModule, SourceModuleGraph, SourceOrigin
from rextio.source.planning import HostSourcePlan


def _sha(data: bytes) -> str:
    return hashlib.sha256(data).hexdigest()


def _write_project_with_generated_tree(tmp_path: Path) -> tuple[Path, ArtifactLayout, Path]:
    project = tmp_path / "project"
    project.mkdir()
    source = project / "app.py"
    source_text = "def add(a: int, b: int) -> int:\n    return a + b\n"
    source.write_bytes(source_text.encode("utf-8"))

    layout = ArtifactLayout(project)
    layout.python_dir.mkdir(parents=True)
    (layout.python_dir / "app.py").write_text(
        "# Generated by Rextio. Do not edit manually.\n" + source_text,
        encoding="utf-8",
    )
    layout.rust_dir.mkdir(parents=True)
    (layout.rust_dir / "Cargo.toml").write_text(
        textwrap.dedent(
            """
            [package]
            name = "rextio_generated_native"
            version = "0.1.0"
            edition = "2021"

            [lib]
            name = "_rextio_native"
            crate-type = ["cdylib"]
            """
        ).lstrip(),
        encoding="utf-8",
    )
    (layout.rust_dir / "src").mkdir()
    (layout.rust_dir / "src" / "lib.rs").write_text(
        "// Generated by Rextio. Do not edit manually.\npub fn dummy() {}\n",
        encoding="utf-8",
    )
    (layout.rust_dir / "Cargo.lock").write_text(
        textwrap.dedent(
            """
            # This file is automatically @generated by Cargo.
            version = 4

            [[package]]
            name = "rextio_generated_native"
            version = "0.1.0"
            """
        ).lstrip(),
        encoding="utf-8",
    )
    layout.build_python_dir.mkdir(parents=True)
    (layout.build_python_dir / "app.py").write_text(
        (layout.python_dir / "app.py").read_text(encoding="utf-8"),
        encoding="utf-8",
    )
    wheel = build_artifact_wheel(project, layout.build_python_dir, layout.dist_dir)
    assert wheel.status == "built" and wheel.path is not None
    return project, layout, Path(wheel.path)


def _plan(project: Path, profile, source: Path) -> BuildPlan:
    source_bytes = source.read_bytes()
    module = SourceModule(
        module_name="app",
        path="app.py",
        is_package_init=False,
        source_origin=SourceOrigin.PROJECT,
        sha256=_sha(source_bytes),
        dependency_depth=0,
    )
    graph = SourceModuleGraph(modules=(module,))
    host_plan = HostSourcePlan(graph=graph, module_initializers=(), unavailable_reason=None)
    project_analysis = ProjectAnalysis(
        project_root=project,
        modules=[
            ModuleAnalysis(
                module_name="app",
                file_path=str(source),
            ),
        ],
    )
    return BuildPlan(
        analysis=project_analysis,
        native=NativePlan(
            accepted_functions=(),
            rejected_functions=(),
            embedded_functions=(),
        ),
        fallback=FallbackPlan(
            backend="cpython",
            modules=(),
        ),
        host_source_plan=host_plan,
        artifact_profiles=(profile,),
    )


def _snapshot(project: Path, layout: ArtifactLayout, plan: BuildPlan) -> EvidenceInputSnapshot:
    snap = capture_project_source_snapshot(project_root=project, plan=plan)
    snap = capture_generated_python_inputs(snap, project_root=project, layout=layout)
    snap = capture_generated_rust_inputs(snap, project_root=project, layout=layout)
    snap = capture_cargo_lock_input(snap, project_root=project, layout=layout)
    return snap


def test_nuitka_host_extension_is_out_of_scope(tmp_path: Path) -> None:
    project, layout, wheel_path = _write_project_with_generated_tree(tmp_path)
    profile = host_extension_profile(
        detect_host_target_triple(),
        python_fallback_backend="nuitka",
    )
    plan = _plan(project, profile, project / "app.py")
    snap = _snapshot(project, layout, plan)
    evidence = emit_host_extension_wheel_evidence(
        project_root=project,
        layout=layout,
        plan=plan,
        wheel_build=WheelBuildResult(status="built", path=str(wheel_path), message="ok"),
        native_build=NativeBuildResult(status="built", tool="cargo", message="ok"),
        input_snapshot=snap,
    )
    assert evidence is None
    assert not list(layout.dist_dir.glob("*.cdx.json"))


def test_non_host_extension_profile_omits_evidence(tmp_path: Path) -> None:
    project, layout, wheel_path = _write_project_with_generated_tree(tmp_path)
    profile = host_extension_profile(detect_host_target_triple())
    plan = _plan(project, profile, project / "app.py")
    object.__setattr__(plan, "artifact_profiles", ())
    evidence = emit_host_extension_wheel_evidence(
        project_root=project,
        layout=layout,
        plan=plan,
        wheel_build=WheelBuildResult(status="built", path=str(wheel_path), message="ok"),
        native_build=NativeBuildResult(status="built", tool="cargo", message="ok"),
        input_snapshot=None,
    )
    assert evidence is None


def test_native_not_built_yields_unavailable_not_failure(tmp_path: Path) -> None:
    project, layout, wheel_path = _write_project_with_generated_tree(tmp_path)
    profile = host_extension_profile(detect_host_target_triple())
    plan = _plan(project, profile, project / "app.py")
    evidence = emit_host_extension_wheel_evidence(
        project_root=project,
        layout=layout,
        plan=plan,
        wheel_build=WheelBuildResult(status="built", path=str(wheel_path), message="ok"),
        native_build=NativeBuildResult(status="failed", tool="cargo", message="boom"),
        input_snapshot=None,
    )
    assert evidence is not None
    assert evidence.status == "unavailable"
    assert evidence.reason == "native-extension-not-built"
    assert evidence.authority == "evidence-only"
    assert evidence.signature_status == "unsigned"
    assert evidence.composition == "incomplete"
    assert not list(layout.dist_dir.glob("*.cdx.json"))


def test_source_snapshot_mismatch_marks_unavailable(tmp_path: Path) -> None:
    project, layout, wheel_path = _write_project_with_generated_tree(tmp_path)
    profile = host_extension_profile(detect_host_target_triple())
    plan = _plan(project, profile, project / "app.py")
    # Capture while disk matches the plan, then mutate before evidence emit.
    snap = _snapshot(project, layout, plan)
    assert snap.unavailable_reason is None
    (project / "app.py").write_text(
        "def add(a: int, b: int) -> int:\n    return a + b + 1\n",
        encoding="utf-8",
    )
    evidence = emit_host_extension_wheel_evidence(
        project_root=project,
        layout=layout,
        plan=plan,
        wheel_build=WheelBuildResult(status="built", path=str(wheel_path), message="ok"),
        native_build=NativeBuildResult(status="built", tool="cargo", message="ok"),
        input_snapshot=snap,
    )
    assert evidence is not None
    assert evidence.status == "unavailable"
    assert evidence.reason == "source-snapshot-mismatch"

    # Capture-time mismatch against a stale plan also fails closed.
    stale = capture_project_source_snapshot(project_root=project, plan=plan)
    assert stale.unavailable_reason == "source-snapshot-mismatch"


def test_preview_ready_writes_sidecars_when_cargo_available(tmp_path: Path) -> None:
    cargo = pytest.importorskip("shutil").which("cargo")
    if cargo is None:
        pytest.skip("cargo is required")

    project, layout, wheel_path = _write_project_with_generated_tree(tmp_path)
    profile = host_extension_profile(detect_host_target_triple())
    plan = _plan(project, profile, project / "app.py")
    snap = _snapshot(project, layout, plan)
    assert snap.unavailable_reason is None

    evidence = emit_host_extension_wheel_evidence(
        project_root=project,
        layout=layout,
        plan=plan,
        wheel_build=WheelBuildResult(status="built", path=str(wheel_path), message="ok"),
        native_build=NativeBuildResult(status="built", tool="cargo", message="ok"),
        input_snapshot=snap,
    )
    assert evidence is not None
    assert evidence.status == "preview-ready"
    assert evidence.preview is True
    assert evidence.complete is False
    assert evidence.signed is False
    assert evidence.authority == "evidence-only"
    assert evidence.subject is not None
    assert evidence.subject.logical_path.startswith("dist/")

    sbom_path = project / evidence.sbom.logical_path  # type: ignore[union-attr]
    prov_path = project / evidence.provenance.logical_path  # type: ignore[union-attr]
    assert sbom_path.is_file()
    assert prov_path.is_file()
    sbom = json.loads(sbom_path.read_text(encoding="utf-8"))
    assert sbom["specVersion"] == "1.6"
    assert sbom["compositions"][0]["aggregate"] == "incomplete"
    root_ref = sbom["metadata"]["component"]["bom-ref"]
    assert root_ref not in [c["bom-ref"] for c in sbom["components"]]
    assert str(project) not in sbom_path.read_text(encoding="utf-8")

    prov = json.loads(prov_path.read_text(encoding="utf-8"))
    assert len(prov["subject"]) == 2
    assert "invocationId" not in prov["predicate"]["runDetails"].get("metadata", {})
    material_uris = [
        item["uri"] for item in prov["predicate"]["buildDefinition"]["resolvedDependencies"]
    ]
    assert not any(uri.endswith(".cdx.json") for uri in material_uris)

    report = evidence.to_dict()
    assert report["status"] == "preview-ready"
    assert report["authority"] == "evidence-only"
    assert "wheel_entries" in report
    assert "cargo_dependencies" in report


def test_prewrite_failure_preserves_preexisting_sidecars(
    tmp_path: Path, monkeypatch: pytest.MonkeyPatch
) -> None:
    from rextio.build import supply_chain as sc

    project, layout, wheel_path = _write_project_with_generated_tree(tmp_path)
    profile = host_extension_profile(detect_host_target_triple())
    plan = _plan(project, profile, project / "app.py")
    snap = _snapshot(project, layout, plan)
    sbom_path = wheel_path.with_suffix(wheel_path.suffix + ".cdx.json")
    provenance_path = wheel_path.with_suffix(wheel_path.suffix + ".intoto.json")
    sbom_path.write_bytes(b"owner-sbom")
    provenance_path.write_bytes(b"owner-provenance")

    def fail_before_write(*_args, **_kwargs):
        raise sc.ArtifactEvidenceError(
            "cargo inventory failed", reason="cargo-metadata-failed"
        )

    monkeypatch.setattr(sc, "resolve_cargo_inventory", fail_before_write)
    evidence = emit_host_extension_wheel_evidence(
        project_root=project,
        layout=layout,
        plan=plan,
        wheel_build=WheelBuildResult(status="built", path=str(wheel_path), message="ok"),
        native_build=NativeBuildResult(status="built", tool="cargo", message="ok"),
        input_snapshot=snap,
    )
    assert evidence is not None
    assert evidence.status == "unavailable"
    assert evidence.reason == "cargo-metadata-failed"
    assert sbom_path.read_bytes() == b"owner-sbom"
    assert provenance_path.read_bytes() == b"owner-provenance"


def test_late_failure_cleans_written_sidecar_only(
    tmp_path: Path, monkeypatch: pytest.MonkeyPatch
) -> None:
    from rextio.build import supply_chain as sc
    from rextio.build.cargo_inventory import CargoInventory

    project, layout, wheel_path = _write_project_with_generated_tree(tmp_path)
    profile = host_extension_profile(detect_host_target_triple())
    plan = _plan(project, profile, project / "app.py")
    snap = _snapshot(project, layout, plan)
    sbom_path = wheel_path.with_suffix(wheel_path.suffix + ".cdx.json")
    provenance_path = wheel_path.with_suffix(wheel_path.suffix + ".intoto.json")
    provenance_path.write_bytes(b"owner-provenance")
    inventory = CargoInventory(
        target_triple=profile.target_triple,
        root_package="rextio_generated_native",
        packages=(),
        dependencies=(),
        lockfile_present=True,
    )
    monkeypatch.setattr(sc, "resolve_cargo_inventory", lambda *_a, **_k: inventory)

    def fail_after_sbom(**_kwargs):
        raise sc.ArtifactEvidenceError(
            "provenance construction failed", reason="evidence-internal-error"
        )

    monkeypatch.setattr(sc, "build_intoto_provenance_document", fail_after_sbom)
    evidence = emit_host_extension_wheel_evidence(
        project_root=project,
        layout=layout,
        plan=plan,
        wheel_build=WheelBuildResult(status="built", path=str(wheel_path), message="ok"),
        native_build=NativeBuildResult(status="built", tool="cargo", message="ok"),
        input_snapshot=snap,
    )
    assert evidence is not None
    assert evidence.status == "unavailable"
    assert evidence.reason == "evidence-internal-error"
    assert not sbom_path.exists()
    assert provenance_path.read_bytes() == b"owner-provenance"


def test_cleanup_failure_cannot_escape_evidence_emission(
    tmp_path: Path, monkeypatch: pytest.MonkeyPatch
) -> None:
    from rextio.build import supply_chain as sc

    project, layout, wheel_path = _write_project_with_generated_tree(tmp_path)
    profile = host_extension_profile(detect_host_target_triple())
    plan = _plan(project, profile, project / "app.py")
    snap = _snapshot(project, layout, plan)

    def fail_inventory(*_args, **_kwargs):
        raise sc.ArtifactEvidenceError(
            "inventory failed", reason="cargo-metadata-failed"
        )

    def fail_cleanup(*_args, **_kwargs) -> None:
        raise OSError("cleanup must not escape")

    monkeypatch.setattr(sc, "resolve_cargo_inventory", fail_inventory)
    monkeypatch.setattr(sc, "cleanup_created_sidecars", fail_cleanup)
    evidence = emit_host_extension_wheel_evidence(
        project_root=project,
        layout=layout,
        plan=plan,
        wheel_build=WheelBuildResult(status="built", path=str(wheel_path), message="ok"),
        native_build=NativeBuildResult(status="built", tool="cargo", message="ok"),
        input_snapshot=snap,
    )
    assert evidence is not None
    assert evidence.status == "unavailable"
    assert evidence.reason == "cargo-metadata-failed"
    assert wheel_path.is_file()


def test_illegal_logical_path_segment_marks_unavailable_not_crash(tmp_path: Path) -> None:
    """SourceModule-legal paths that fail evidence path rules must not abort builds."""
    project = tmp_path / "project"
    project.mkdir()
    # Space is legal for SourceModule relative paths but illegal for evidence
    # logical references (strict segment charset).
    source = project / "my file.py"
    source.write_text("def add(a: int, b: int) -> int:\n    return a + b\n", encoding="utf-8")
    source_bytes = source.read_bytes()
    module = SourceModule(
        module_name="my_file",
        path="my file.py",
        is_package_init=False,
        source_origin=SourceOrigin.PROJECT,
        sha256=_sha(source_bytes),
        dependency_depth=0,
    )
    graph = SourceModuleGraph(modules=(module,))
    host_plan = HostSourcePlan(graph=graph, module_initializers=(), unavailable_reason=None)
    plan = BuildPlan(
        analysis=ProjectAnalysis(
            project_root=project,
            modules=[ModuleAnalysis(module_name="my_file", file_path=str(source))],
        ),
        native=NativePlan(accepted_functions=(), rejected_functions=()),
        fallback=FallbackPlan(backend="cpython", modules=()),
        host_source_plan=host_plan,
        artifact_profiles=(host_extension_profile(detect_host_target_triple()),),
    )
    snap = capture_project_source_snapshot(project_root=project, plan=plan)
    assert snap.unavailable_reason == "source-input-unreadable"
    layout = ArtifactLayout(project)
    layout.dist_dir.mkdir(parents=True)
    wheel_path = layout.dist_dir / "demo-0.1.0-py3-none-any.whl"
    # Minimal valid ZIP wheel for inventory/hash paths if emit proceeds.
    import zipfile

    with zipfile.ZipFile(wheel_path, "w") as archive:
        archive.writestr("demo/__init__.py", b"")
    evidence = emit_host_extension_wheel_evidence(
        project_root=project,
        layout=layout,
        plan=plan,
        wheel_build=WheelBuildResult(status="built", path=str(wheel_path), message="ok"),
        native_build=NativeBuildResult(status="built", tool="cargo", message="ok"),
        input_snapshot=snap,
    )
    assert evidence is not None
    assert evidence.status == "unavailable"
    assert evidence.reason == "source-input-unreadable"


def test_host_extension_kind_is_required() -> None:
    assert ArtifactKind.HOST_EXTENSION.value == "host-extension"


def test_wheel_mutation_after_snapshot_marks_unavailable(tmp_path: Path, monkeypatch) -> None:
    """Wheel digest/size change after snapshot must yield wheel-bytes-mutated."""
    cargo = pytest.importorskip("shutil").which("cargo")
    if cargo is None:
        pytest.skip("cargo is required")

    from rextio.artifacts import evidence as evidence_mod
    from rextio.build import supply_chain as sc

    project, layout, wheel_path = _write_project_with_generated_tree(tmp_path)
    profile = host_extension_profile(detect_host_target_triple())
    plan = _plan(project, profile, project / "app.py")
    snap = _snapshot(project, layout, plan)

    real_hash = evidence_mod.hash_regular_file
    call_count = {"n": 0}

    def flaky_hash(path, *, max_bytes=evidence_mod.MAX_EVIDENCE_FILE_BYTES):
        # load_wheel_snapshot does not use hash_regular_file; the first hash of
        # the wheel is the final confirmation re-read — flip it to simulate mutation.
        digest, size = real_hash(path, max_bytes=max_bytes)
        if Path(path).resolve() == wheel_path.resolve():
            call_count["n"] += 1
            return ("f" * 64, size)
        return digest, size

    monkeypatch.setattr(sc, "hash_regular_file", flaky_hash)
    evidence = emit_host_extension_wheel_evidence(
        project_root=project,
        layout=layout,
        plan=plan,
        wheel_build=WheelBuildResult(status="built", path=str(wheel_path), message="ok"),
        native_build=NativeBuildResult(status="built", tool="cargo", message="ok"),
        input_snapshot=snap,
    )
    assert evidence is not None
    assert evidence.status == "unavailable"
    assert evidence.reason == "wheel-bytes-mutated"
    # Partial sidecars must be cleaned up.
    assert not list(layout.dist_dir.glob("*.cdx.json"))
    assert not list(layout.dist_dir.glob("*.intoto.json"))


def test_input_mutation_after_cargo_marks_unavailable(tmp_path: Path, monkeypatch) -> None:
    """Inputs mutated after cargo metadata must fail re-verify before sidecars."""
    cargo = pytest.importorskip("shutil").which("cargo")
    if cargo is None:
        pytest.skip("cargo is required")

    from rextio.build import supply_chain as sc

    project, layout, wheel_path = _write_project_with_generated_tree(tmp_path)
    profile = host_extension_profile(detect_host_target_triple())
    plan = _plan(project, profile, project / "app.py")
    snap = _snapshot(project, layout, plan)

    real_resolve = sc.resolve_cargo_inventory

    def mutate_then_resolve(*args, **kwargs):
        inv = real_resolve(*args, **kwargs)
        # Mutate a captured project input after cargo returns.
        (project / "app.py").write_text(
            "def add(a: int, b: int) -> int:\n    return a - b\n",
            encoding="utf-8",
        )
        return inv

    monkeypatch.setattr(sc, "resolve_cargo_inventory", mutate_then_resolve)
    evidence = emit_host_extension_wheel_evidence(
        project_root=project,
        layout=layout,
        plan=plan,
        wheel_build=WheelBuildResult(status="built", path=str(wheel_path), message="ok"),
        native_build=NativeBuildResult(status="built", tool="cargo", message="ok"),
        input_snapshot=snap,
    )
    assert evidence is not None
    assert evidence.status == "unavailable"
    assert evidence.reason == "source-snapshot-mismatch"
    assert not list(layout.dist_dir.glob("*.cdx.json"))


def test_bounded_py_walk_counts_entries_before_sort(tmp_path: Path) -> None:
    from rextio.build import supply_chain as sc

    root = tmp_path / "py"
    root.mkdir()
    # Direct unit: max_files=2 with 3 .py files must exceed.
    for i in range(3):
        (root / f"f{i:02d}.py").write_text(f"x = {i}\n", encoding="utf-8")
    walked = sc._bounded_py_walk(root, max_files=2)
    assert walked == "input-count-exceeded"

    # Overflow of children before sort: max_files=1 => max_children_per_dir=64.
    bulk = tmp_path / "bulk"
    bulk.mkdir()
    for i in range(300):
        (bulk / f"n{i}.txt").write_text("x", encoding="utf-8")
    walked2 = sc._bounded_py_walk(bulk, max_files=1)
    assert walked2 == "input-count-exceeded"
