"""Unit tests for sanitized reachable Cargo inventory resolution."""

from __future__ import annotations

import json
import textwrap
from pathlib import Path

import pytest

from rextio.artifacts.evidence import ArtifactEvidenceError, REASON_CARGO_GRAPH_INVALID
from rextio.build.cargo_inventory import resolve_cargo_inventory, _inventory_from_metadata


def _write_minimal_crate(rust_dir: Path, *, with_registry: bool = False) -> None:
    rust_dir.mkdir(parents=True, exist_ok=True)
    (rust_dir / "Cargo.toml").write_text(
        textwrap.dedent(
            """
            [package]
            name = "rextio_generated_native"
            version = "0.1.0"
            edition = "2021"

            [lib]
            name = "_rextio_native"
            crate-type = ["cdylib"]

            [dependencies]
            """
        ).lstrip(),
        encoding="utf-8",
    )
    (rust_dir / "src").mkdir(exist_ok=True)
    (rust_dir / "src" / "lib.rs").write_text("pub fn dummy() {}\n", encoding="utf-8")
    lock = textwrap.dedent(
        """
        # This file is automatically @generated by Cargo.
        version = 4

        [[package]]
        name = "rextio_generated_native"
        version = "0.1.0"
        """
    ).lstrip()
    if with_registry:
        lock += textwrap.dedent(
            """
            [[package]]
            name = "cfg-if"
            version = "1.0.0"
            source = "registry+https://github.com/rust-lang/crates.io-index"
            checksum = "baf1de4339761588bc0619e3cbc0120ee582ebb74b53b4efbf79117bd2da40fd"
            """
        )
    (rust_dir / "Cargo.lock").write_text(lock, encoding="utf-8")


def test_resolve_cargo_inventory_offline_locked(tmp_path: Path) -> None:
    cargo = pytest.importorskip("shutil").which("cargo")
    if cargo is None:
        pytest.skip("cargo is required")

    rust_dir = tmp_path / "rust"
    _write_minimal_crate(rust_dir)
    inventory = resolve_cargo_inventory(
        rust_dir,
        target_triple="aarch64-apple-darwin",
    )
    assert inventory.lockfile_present is True
    assert inventory.root_package == "rextio_generated_native"
    names = [package.name for package in inventory.packages]
    assert "rextio_generated_native" in names
    root_pkgs = [p for p in inventory.packages if p.kind == "path-root"]
    assert len(root_pkgs) == 1
    payload = json.dumps(inventory.to_dict())
    assert str(rust_dir) not in payload
    assert "/Users/" not in payload
    assert "token" not in payload


def test_resolve_cargo_inventory_requires_lockfile(tmp_path: Path) -> None:
    rust_dir = tmp_path / "rust"
    _write_minimal_crate(rust_dir)
    (rust_dir / "Cargo.lock").unlink()
    with pytest.raises(ArtifactEvidenceError, match="Cargo.lock"):
        resolve_cargo_inventory(rust_dir, target_triple="x86_64-unknown-linux-gnu")


def test_resolve_cargo_inventory_rejects_bad_target(tmp_path: Path) -> None:
    rust_dir = tmp_path / "rust"
    _write_minimal_crate(rust_dir)
    with pytest.raises(ArtifactEvidenceError, match="target triple"):
        resolve_cargo_inventory(rust_dir, target_triple="../escape")


def test_inventory_rejects_non_root_path_and_git_packages() -> None:
    root_id = "path+file://generated#rextio_generated_native@0.1.0"
    other_path = "path+file:///tmp/other#other@1.0.0"
    git_id = "git+https://github.com/example/repo#gitpkg@1.0.0"
    lock_checksums: dict[tuple[str, str, str | None], str] = {}
    payload = {
        "packages": [
            {
                "name": "rextio_generated_native",
                "version": "0.1.0",
                "source": None,
                "id": root_id,
            },
            {
                "name": "other",
                "version": "1.0.0",
                "source": None,
                "id": other_path,
            },
        ],
        "resolve": {
            "root": root_id,
            "nodes": [
                {"id": root_id, "dependencies": [other_path], "features": []},
                {"id": other_path, "dependencies": [], "features": []},
            ],
        },
    }
    with pytest.raises(ArtifactEvidenceError) as exc:
        _inventory_from_metadata(
            payload,
            lock_checksums=lock_checksums,
            target_triple="aarch64-apple-darwin",
            expected_root_name="rextio_generated_native",
        )
    assert exc.value.reason == REASON_CARGO_GRAPH_INVALID

    payload_git = {
        "packages": [
            {
                "name": "rextio_generated_native",
                "version": "0.1.0",
                "source": None,
                "id": root_id,
            },
            {
                "name": "gitpkg",
                "version": "1.0.0",
                "source": "git+https://github.com/example/repo",
                "id": git_id,
            },
        ],
        "resolve": {
            "root": root_id,
            "nodes": [
                {"id": root_id, "dependencies": [git_id], "features": []},
                {"id": git_id, "dependencies": [], "features": []},
            ],
        },
    }
    with pytest.raises(ArtifactEvidenceError) as exc2:
        _inventory_from_metadata(
            payload_git,
            lock_checksums=lock_checksums,
            target_triple="aarch64-apple-darwin",
            expected_root_name="rextio_generated_native",
        )
    assert "git" in str(exc2.value).lower() or exc2.value.reason == REASON_CARGO_GRAPH_INVALID


def test_inventory_requires_registry_checksum_and_records_edges() -> None:
    root_id = "path+file://generated#rextio_generated_native@0.1.0"
    reg_id = "registry+https://github.com/rust-lang/crates.io-index#cfg-if@1.0.0"
    source = "registry+https://github.com/rust-lang/crates.io-index"
    checksum = "baf1de4339761588bc0619e3cbc0120ee582ebb74b53b4efbf79117bd2da40fd"
    payload = {
        "packages": [
            {
                "name": "rextio_generated_native",
                "version": "0.1.0",
                "source": None,
                "id": root_id,
            },
            {
                "name": "cfg-if",
                "version": "1.0.0",
                "source": source,
                "id": reg_id,
                "license": "MIT/Apache-2.0",
            },
        ],
        "resolve": {
            "root": root_id,
            "nodes": [
                {
                    "id": root_id,
                    "dependencies": [reg_id],
                    "features": [],
                },
                {
                    "id": reg_id,
                    "dependencies": [],
                    "features": ["default"],
                },
            ],
        },
    }
    with pytest.raises(ArtifactEvidenceError, match="checksum"):
        _inventory_from_metadata(
            payload,
            lock_checksums={},
            target_triple="aarch64-apple-darwin",
            expected_root_name="rextio_generated_native",
        )

    inventory = _inventory_from_metadata(
        payload,
        lock_checksums={("cfg-if", "1.0.0", source): checksum},
        target_triple="aarch64-apple-darwin",
        expected_root_name="rextio_generated_native",
    )
    assert inventory.root_package == "rextio_generated_native"
    assert any(pkg.name == "cfg-if" and pkg.checksum == checksum for pkg in inventory.packages)
    cfg = next(pkg for pkg in inventory.packages if pkg.name == "cfg-if")
    root_pkg = next(pkg for pkg in inventory.packages if pkg.name == "rextio_generated_native")
    assert any(
        edge.dependent_ref == root_pkg.bom_ref() and edge.dependency_ref == cfg.bom_ref()
        for edge in inventory.dependencies
    )
    assert "default" in cfg.features
    assert cfg.license == "MIT/Apache-2.0"
    assert cfg.source == source  # internal only
    report = inventory.to_dict()
    assert "user:" not in json.dumps(report)
    cfg_report = next(pkg for pkg in report["packages"] if pkg["name"] == "cfg-if")
    assert "source" not in cfg_report
    assert cfg_report["source_fingerprint"] is not None
    assert len(cfg_report["source_fingerprint"]) == 64


@pytest.mark.parametrize(
    ("license_value", "expected"),
    [
        (None, None),
        ("", None),
        ("   ", None),
        ("\t", None),
        ("\n", None),
        (" UNKNOWN ", " UNKNOWN "),
        ("NOASSERTION", "NOASSERTION"),
        ("MIT OR Apache-2.0", "MIT OR Apache-2.0"),
    ],
)
def test_inventory_preserves_nonblank_license_metadata_verbatim(
    license_value: str | None,
    expected: str | None,
) -> None:
    root_id = "path+file://generated#rextio_generated_native@0.1.0"
    inventory = _inventory_from_metadata(
        {
            "packages": [
                {
                    "name": "rextio_generated_native",
                    "version": "0.1.0",
                    "source": None,
                    "id": root_id,
                    "license": license_value,
                }
            ],
            "resolve": {
                "root": root_id,
                "nodes": [{"id": root_id, "dependencies": [], "features": []}],
            },
        },
        lock_checksums={},
        target_triple="aarch64-apple-darwin",
        expected_root_name="rextio_generated_native",
    )
    assert inventory.packages[0].license == expected


def test_inventory_rejects_license_control_characters() -> None:
    root_id = "path+file://generated#rextio_generated_native@0.1.0"
    with pytest.raises(ArtifactEvidenceError) as exc:
        _inventory_from_metadata(
            {
                "packages": [
                    {
                        "name": "rextio_generated_native",
                        "version": "0.1.0",
                        "source": None,
                        "id": root_id,
                        "license": "MIT\x00hidden",
                    }
                ],
                "resolve": {
                    "root": root_id,
                    "nodes": [{"id": root_id, "dependencies": [], "features": []}],
                },
            },
            lock_checksums={},
            target_triple="aarch64-apple-darwin",
            expected_root_name="rextio_generated_native",
        )
    assert exc.value.reason == REASON_CARGO_GRAPH_INVALID


def test_inventory_rejects_credential_registry_uri() -> None:
    root_id = "path+file://generated#rextio_generated_native@0.1.0"
    dirty = "registry+https://user:token@github.com/rust-lang/crates.io-index"
    reg_id = f"{dirty}#cfg-if@1.0.0"
    payload = {
        "packages": [
            {
                "name": "rextio_generated_native",
                "version": "0.1.0",
                "source": None,
                "id": root_id,
            },
            {
                "name": "cfg-if",
                "version": "1.0.0",
                "source": dirty,
                "id": reg_id,
            },
        ],
        "resolve": {
            "root": root_id,
            "nodes": [
                {"id": root_id, "dependencies": [reg_id], "features": []},
                {"id": reg_id, "dependencies": [], "features": []},
            ],
        },
    }
    with pytest.raises(ArtifactEvidenceError) as exc:
        _inventory_from_metadata(
            payload,
            lock_checksums={
                (
                    "cfg-if",
                    "1.0.0",
                    "registry+https://github.com/rust-lang/crates.io-index",
                ): "baf1de4339761588bc0619e3cbc0120ee582ebb74b53b4efbf79117bd2da40fd"
            },
            target_triple="aarch64-apple-darwin",
            expected_root_name="rextio_generated_native",
        )
    assert "credential" in str(exc.value).lower() or exc.value.reason == REASON_CARGO_GRAPH_INVALID


def test_inventory_rejects_duplicate_package_ids() -> None:
    root_id = "path+file://generated#rextio_generated_native@0.1.0"
    payload = {
        "packages": [
            {
                "name": "rextio_generated_native",
                "version": "0.1.0",
                "source": None,
                "id": root_id,
            },
            {
                "name": "other",
                "version": "1.0.0",
                "source": None,
                "id": root_id,
            },
        ],
        "resolve": {
            "root": root_id,
            "nodes": [{"id": root_id, "dependencies": [], "features": []}],
        },
    }
    with pytest.raises(ArtifactEvidenceError, match="duplicated"):
        _inventory_from_metadata(
            payload,
            lock_checksums={},
            target_triple="aarch64-apple-darwin",
            expected_root_name="rextio_generated_native",
        )


def test_inventory_rejects_cross_registry_checksum_fallback() -> None:
    root_id = "path+file://generated#rextio_generated_native@0.1.0"
    reg_id = "registry+https://github.com/rust-lang/crates.io-index#cfg-if@1.0.0"
    source = "registry+https://github.com/rust-lang/crates.io-index"
    other = "registry+https://other.example/index"
    checksum = "baf1de4339761588bc0619e3cbc0120ee582ebb74b53b4efbf79117bd2da40fd"
    payload = {
        "packages": [
            {
                "name": "rextio_generated_native",
                "version": "0.1.0",
                "source": None,
                "id": root_id,
            },
            {
                "name": "cfg-if",
                "version": "1.0.0",
                "source": source,
                "id": reg_id,
            },
        ],
        "resolve": {
            "root": root_id,
            "nodes": [
                {"id": root_id, "dependencies": [reg_id], "features": []},
                {"id": reg_id, "dependencies": [], "features": []},
            ],
        },
    }
    # Checksum registered under a different registry must not bind.
    with pytest.raises(ArtifactEvidenceError, match="checksum"):
        _inventory_from_metadata(
            payload,
            lock_checksums={("cfg-if", "1.0.0", other): checksum},
            target_triple="aarch64-apple-darwin",
            expected_root_name="rextio_generated_native",
        )


def _duplicate_dependency_payload(count: int) -> tuple[dict[str, object], str, str, str]:
    root_id = "path+file://generated#rextio_generated_native@0.1.0"
    source = "registry+https://github.com/rust-lang/crates.io-index"
    dep_id = f"{source}#cfg-if@1.0.0"
    checksum = "baf1de4339761588bc0619e3cbc0120ee582ebb74b53b4efbf79117bd2da40fd"
    payload: dict[str, object] = {
        "packages": [
            {
                "name": "rextio_generated_native",
                "version": "0.1.0",
                "source": None,
                "id": root_id,
            },
            {
                "name": "cfg-if",
                "version": "1.0.0",
                "source": source,
                "id": dep_id,
            },
        ],
        "resolve": {
            "root": root_id,
            "nodes": [
                {"id": root_id, "dependencies": [dep_id] * count, "features": []},
                {"id": dep_id, "dependencies": [], "features": []},
            ],
        },
    }
    return payload, source, dep_id, checksum


def test_raw_dependency_reference_bound_fails_before_queue_growth(
    monkeypatch: pytest.MonkeyPatch,
) -> None:
    from rextio.build import cargo_inventory as cargo_inventory_mod

    payload, _source, _dep_id, _checksum = _duplicate_dependency_payload(5)
    monkeypatch.setattr(cargo_inventory_mod, "MAX_CARGO_EDGES", 4)

    class QueueMustNotBeConstructed:
        def __init__(self, *_args, **_kwargs) -> None:
            raise AssertionError("BFS queue must not be reached after raw-bound failure")

    monkeypatch.setattr(cargo_inventory_mod, "deque", QueueMustNotBeConstructed)
    with pytest.raises(ArtifactEvidenceError, match="reference count exceeds"):
        _inventory_from_metadata(
            payload,
            lock_checksums={},
            target_triple="aarch64-apple-darwin",
            expected_root_name="rextio_generated_native",
        )


def test_valid_duplicate_dependency_ids_are_deduplicated() -> None:
    payload, source, _dep_id, checksum = _duplicate_dependency_payload(3)
    inventory = _inventory_from_metadata(
        payload,
        lock_checksums={("cfg-if", "1.0.0", source): checksum},
        target_triple="aarch64-apple-darwin",
        expected_root_name="rextio_generated_native",
    )
    assert len(inventory.packages) == 2
    assert len(inventory.dependencies) == 1
