from __future__ import annotations

import stat
import subprocess

import pytest
import sys
import zipfile
from pathlib import Path

from rextio.build.executable_builder import (
    build_nuitka_executable,
    build_rust_executable,
    build_zipapp_executable,
)


def test_build_zipapp_executable_runs_entrypoint(tmp_path: Path) -> None:
    python_dir = tmp_path / "python"
    dist_dir = tmp_path / "dist"
    package = python_dir / "demo_app"
    package.mkdir(parents=True)
    (package / "__init__.py").write_text("", encoding="utf-8")
    (package / "cli.py").write_text(
        """
def main() -> int:
    print("hello from zipapp")
    return 0
""",
        encoding="utf-8",
    )

    result = build_zipapp_executable(
        python_dir,
        dist_dir,
        entrypoint="demo_app.cli:main",
        executable_name="demo-tool",
    )

    assert result.status == "built"
    assert result.entrypoint == "demo_app.cli:main"
    executable = Path(result.path or "")
    assert executable == dist_dir / "demo-tool.pyz"
    assert executable.exists()
    with zipfile.ZipFile(executable) as archive:
        assert "__main__.py" in archive.namelist()
        assert "demo_app/cli.py" in archive.namelist()

    completed = subprocess.run(
        [sys.executable, str(executable)],
        check=True,
        capture_output=True,
        text=True,
    )
    assert completed.stdout.strip() == "hello from zipapp"


def test_build_zipapp_executable_skips_without_entrypoint(tmp_path: Path) -> None:
    result = build_zipapp_executable(tmp_path / "python", tmp_path / "dist", entrypoint=None)

    assert result.status == "skipped"
    assert result.path is None
    assert result.entrypoint is None


def test_build_zipapp_executable_rejects_invalid_entrypoint(tmp_path: Path) -> None:
    python_dir = tmp_path / "python"
    python_dir.mkdir()

    result = build_zipapp_executable(
        python_dir,
        tmp_path / "dist",
        entrypoint="not-a-module",
    )

    assert result.status == "failed"
    assert "Use module:function" in result.message


def test_build_zipapp_executable_reports_missing_python_artifact(tmp_path: Path) -> None:
    result = build_zipapp_executable(
        tmp_path / "missing",
        tmp_path / "dist",
        entrypoint="demo.cli:main",
    )

    assert result.status == "failed"
    assert "Python build artifact was missing" in result.message


def test_build_rust_executable_accepts_windows_exe_suffix(
    tmp_path: Path,
    monkeypatch,
) -> None:
    crate_dir = tmp_path / "crate"
    crate_dir.mkdir()
    (crate_dir / "Cargo.toml").write_text("[package]\nname = \"demo\"\n", encoding="utf-8")
    bin_dir = tmp_path / "bin"
    bin_dir.mkdir()
    cargo = bin_dir / "cargo"
    cargo.write_text(
        f"""#!{sys.executable}
from pathlib import Path

release = Path.cwd() / "target" / "release"
release.mkdir(parents=True, exist_ok=True)
(release / "demo-tool.exe").write_bytes(b"exe")
""",
        encoding="utf-8",
    )
    cargo.chmod(0o755)
    monkeypatch.setenv("PATH", str(bin_dir))

    result = build_rust_executable(
        crate_dir,
        tmp_path / "dist",
        "demo-tool",
        "app:main",
    )

    assert result.status == "built"
    assert Path(result.path or "") == tmp_path / "dist" / "demo-tool.exe"
    assert (tmp_path / "dist" / "demo-tool.exe").read_bytes() == b"exe"


def test_build_nuitka_standalone_executable_uses_nuitka(
    tmp_path: Path,
    monkeypatch,
) -> None:
    python_dir = _python_app(tmp_path)
    nuitka = _fake_nuitka(tmp_path)
    monkeypatch.setenv("PATH", f"{nuitka.parent}")

    result = build_nuitka_executable(
        python_dir,
        tmp_path / "dist",
        entrypoint="demo_app.cli:main",
        executable_name="demo-tool",
        mode="standalone",
    )

    assert result.status == "built"
    assert result.backend == "nuitka"
    assert result.entrypoint == "demo_app.cli:main"
    assert Path(result.path or "") == tmp_path / "dist" / "demo-tool.dist" / "demo-tool"
    assert result.command
    assert "--standalone" in result.command
    assert "--output-filename=demo-tool" in result.command
    assert (python_dir / "__rextio_executable__.py").read_text(encoding="utf-8").startswith(
        "# Generated by Rextio. Do not edit manually."
    )
    # Nuitka named the directory after the launcher script; the builder must
    # have renamed it to the documented <name>.dist layout.
    assert not (tmp_path / "dist" / "__rextio_executable__.dist").exists()


def test_build_nuitka_standalone_replaces_stale_dist_directory(
    tmp_path: Path,
    monkeypatch,
) -> None:
    # A rebuild must replace a stale dist/<name>.dist left by a previous
    # build instead of failing the rename or resolving the old binary.
    python_dir = _python_app(tmp_path)
    nuitka = _fake_nuitka(tmp_path)
    monkeypatch.setenv("PATH", f"{nuitka.parent}")
    stale = tmp_path / "dist" / "demo-tool.dist"
    stale.mkdir(parents=True)
    (stale / "demo-tool").write_text("stale binary", encoding="utf-8")

    result = build_nuitka_executable(
        python_dir,
        tmp_path / "dist",
        entrypoint="demo_app.cli:main",
        executable_name="demo-tool",
        mode="standalone",
    )

    assert result.status == "built"
    produced = tmp_path / "dist" / "demo-tool.dist" / "demo-tool"
    assert Path(result.path or "") == produced
    assert "fake nuitka" in produced.read_text(encoding="utf-8")


def test_build_nuitka_onefile_executable_uses_nuitka(
    tmp_path: Path,
    monkeypatch,
) -> None:
    python_dir = _python_app(tmp_path)
    nuitka = _fake_nuitka(tmp_path)
    monkeypatch.setenv("PATH", f"{nuitka.parent}")

    result = build_nuitka_executable(
        python_dir,
        tmp_path / "dist",
        entrypoint="demo_app.cli:main",
        executable_name="demo-tool",
        mode="onefile",
    )

    assert result.status == "built"
    assert Path(result.path or "") == tmp_path / "dist" / "demo-tool"
    assert result.command
    assert "--onefile" in result.command


def test_build_nuitka_executable_reports_missing_nuitka(
    tmp_path: Path,
    monkeypatch,
) -> None:
    python_dir = _python_app(tmp_path)
    monkeypatch.setenv("PATH", "")

    result = build_nuitka_executable(
        python_dir,
        tmp_path / "dist",
        entrypoint="demo_app.cli:main",
    )

    assert result.status == "failed"
    assert result.backend == "nuitka"
    assert "Nuitka is not installed" in result.message


def test_build_nuitka_executable_rejects_invalid_mode(
    tmp_path: Path,
    monkeypatch,
) -> None:
    python_dir = _python_app(tmp_path)
    nuitka = _fake_nuitka(tmp_path)
    monkeypatch.setenv("PATH", f"{nuitka.parent}")

    result = build_nuitka_executable(
        python_dir,
        tmp_path / "dist",
        entrypoint="demo_app.cli:main",
        mode="invalid",
    )

    assert result.status == "failed"
    assert 'Use "standalone" or "onefile"' in result.message


def _python_app(tmp_path: Path) -> Path:
    python_dir = tmp_path / "python"
    package = python_dir / "demo_app"
    package.mkdir(parents=True)
    (package / "__init__.py").write_text("", encoding="utf-8")
    (package / "cli.py").write_text(
        """
def main() -> int:
    print("hello from executable")
    return 0
""",
        encoding="utf-8",
    )
    return python_dir


def _fake_nuitka(tmp_path: Path) -> Path:
    bin_dir = tmp_path / "bin"
    bin_dir.mkdir()
    nuitka = bin_dir / "nuitka"
    nuitka.write_text(
        f"""#!{sys.executable}
import sys
from pathlib import Path

args = sys.argv[1:]
if "--version" in args:
    print("2.4.8")
    sys.exit(0)
out = Path(next(arg.split("=", 1)[1] for arg in args if arg.startswith("--output-dir=")))
name = next(arg.split("=", 1)[1] for arg in args if arg.startswith("--output-filename="))
script = Path(next(arg for arg in args if arg.endswith(".py")))
out.mkdir(parents=True, exist_ok=True)
if "--onefile" in args:
    target = out / name
else:
    # Real Nuitka names the standalone directory after the compiled SCRIPT
    # (--output-filename only names the binary inside it).
    target = out / f"{{script.stem}}.dist" / name
    target.parent.mkdir(parents=True, exist_ok=True)
target.write_text("#!/usr/bin/env python3\\nprint('fake nuitka')\\n", encoding="utf-8")
target.chmod(0o755)
""",
        encoding="utf-8",
    )
    nuitka.chmod(0o755)
    return nuitka


def test_nuitka_executable_fails_early_for_externally_accelerated_modules(
    tmp_path: Path,
    monkeypatch,
) -> None:
    # A Nuitka executable cannot serve numba-decorated functions (compiled
    # functions expose no bytecode and the accelerator is not bundled); the
    # build must fail at build time with guidance, not at the first call.
    import stat

    bin_dir = tmp_path / "fake-nuitka-bin"
    bin_dir.mkdir()
    nuitka = bin_dir / "nuitka"
    nuitka.write_text("#!/bin/sh\nexit 0\n", encoding="utf-8")
    nuitka.chmod(nuitka.stat().st_mode | stat.S_IEXEC)
    monkeypatch.setenv("PATH", f"{bin_dir}:/usr/bin:/bin")

    python_dir = tmp_path / "python"
    (python_dir / "app").mkdir(parents=True)
    (python_dir / "app" / "__init__.py").write_text("", encoding="utf-8")
    (python_dir / "app" / "cli.py").write_text(
        "def main():\n    return 0\n", encoding="utf-8"
    )
    (python_dir / "app" / "kernels.py").write_text(
        "from numba import njit\n\n@njit\ndef f(x: int) -> int:\n    return x\n",
        encoding="utf-8",
    )

    result = build_nuitka_executable(python_dir, tmp_path / "dist", "app.cli:main")

    assert result.status == "failed"
    assert "external" in result.message and "accelerator" in result.message
    assert "app/kernels.py" in result.message
    assert not (tmp_path / "dist").exists() or not any((tmp_path / "dist").iterdir())

def test_nuitka_standalone_without_binary_is_a_failed_build(
    tmp_path: Path, monkeypatch: pytest.MonkeyPatch
) -> None:
    # A fake nuitka that produces the .dist directory but no launcher binary:
    # a partial standalone build must be reported as failed, not as a "built"
    # artifact whose path is a directory nobody can execute.
    bin_dir = tmp_path / "bin"
    bin_dir.mkdir()
    fake = bin_dir / "nuitka"
    fake.write_text(
        "#!/bin/sh\n"
        'out=""; name=""\n'
        'for arg in "$@"; do\n'
        '  case "$arg" in\n'
        '    --output-dir=*) out="${arg#--output-dir=}";;\n'
        '    --output-filename=*) name="${arg#--output-filename=}";;\n'
        "  esac\n"
        "done\n"
        'mkdir -p "$out/$name.dist"\n',
        encoding="utf-8",
    )
    fake.chmod(fake.stat().st_mode | stat.S_IEXEC)
    monkeypatch.setenv("PATH", f"{bin_dir}:/usr/bin:/bin")

    python_dir = tmp_path / "python"
    python_dir.mkdir()
    (python_dir / "app.py").write_text("def main():\n    return 0\n", encoding="utf-8")

    result = build_nuitka_executable(
        python_dir,
        tmp_path / "dist",
        "app:main",
        executable_name="demo-tool",
    )

    assert result.status == "failed"
    assert "not found" in result.message


def test_pre_2_nuitka_fails_the_executable_build(
    tmp_path: Path,
    monkeypatch,
) -> None:
    # The executable path enforces the same Nuitka >= 2.0 floor as the
    # fallback path, before any real compilation is attempted.
    python_dir = _python_app(tmp_path)
    bin_dir = tmp_path / "old-nuitka-bin"
    bin_dir.mkdir()
    nuitka = bin_dir / "nuitka"
    nuitka.write_text(
        '#!/bin/sh\nif [ "$1" = --version ]; then echo 1.9.7; exit 0; fi\n',
        encoding="utf-8",
    )
    nuitka.chmod(0o755)
    monkeypatch.setenv("PATH", str(bin_dir))

    result = build_nuitka_executable(
        python_dir,
        tmp_path / "dist",
        entrypoint="demo_app.cli:main",
        executable_name="demo-tool",
        mode="standalone",
    )

    assert result.status == "failed"
    assert "Nuitka 1.9.7 is too old" in (result.message or "")
    assert ">= 2.0" in (result.message or "")
