"""Deterministic project source graph contracts and builders."""

from rextio.source.graph import (
    OwnerMapping,
    SourceGraphError,
    build_source_module_graph,
    build_source_module_graph_from_analysis,
    resolve_import_from_base,
    source_module_graph_from_analysis,
)
from rextio.source.external_analysis import (
    ExternalFunctionBinding,
    ExternalScalarParameter,
    ExternalSourceAnalysisError,
    ExternalSourceNativePlan,
    ExternalSourceSnapshot,
    analyze_external_source_snapshot,
)
from rextio.source.models import (
    DistributionMetadata,
    ExternalImportReference,
    ImportAlias,
    ImportKind,
    ImportOwnership,
    ImportRecord,
    LocalImportEdge,
    SourceModule,
    SourceModuleGraph,
    SourceOrigin,
    SourcePosition,
    SourceRange,
    StronglyConnectedComponent,
)

__all__ = [
    "DistributionMetadata",
    "ExternalImportReference",
    "ExternalFunctionBinding",
    "ExternalScalarParameter",
    "ExternalSourceAnalysisError",
    "ExternalSourceNativePlan",
    "ExternalSourceSnapshot",
    "ImportAlias",
    "ImportKind",
    "ImportOwnership",
    "ImportRecord",
    "LocalImportEdge",
    "OwnerMapping",
    "SourceGraphError",
    "SourceModule",
    "SourceModuleGraph",
    "SourceOrigin",
    "SourcePosition",
    "SourceRange",
    "StronglyConnectedComponent",
    "build_source_module_graph",
    "build_source_module_graph_from_analysis",
    "analyze_external_source_snapshot",
    "resolve_import_from_base",
    "source_module_graph_from_analysis",
]
