from __future__ import annotations

import os
from pathlib import Path

import pytest


@pytest.fixture
def fake_cargo(tmp_path: Path, monkeypatch: pytest.MonkeyPatch) -> Path:
    bin_dir = tmp_path / "fake-bin"
    bin_dir.mkdir()
    cargo = bin_dir / "cargo"
    cargo.write_text(
        """#!/usr/bin/env python3
import json
import sys
import tomllib
from pathlib import Path

argv = sys.argv[1:]
manifest = Path.cwd() / "Cargo.toml"
if "--manifest-path" in argv:
    manifest = Path(argv[argv.index("--manifest-path") + 1])
package = {}
if manifest.exists():
    package = tomllib.loads(manifest.read_text(encoding="utf-8")).get("package", {})
name = str(package.get("name", "rextio_generated_native"))
version = str(package.get("version", "0.1.0"))
crate_name = name.replace("-", "_")

# C6.2 evidence uses `cargo metadata --locked --offline --filter-platform`.
if argv and argv[0] == "metadata":
    package_id = f"path+file://generated#{name}@{version}"
    print(
        json.dumps(
            {
                "packages": [
                    {
                        "name": name,
                        "version": version,
                        "source": None,
                        "id": package_id,
                        "license": None,
                    }
                ],
                "resolve": {
                    "root": package_id,
                    "nodes": [
                        {
                            "id": package_id,
                            "dependencies": [],
                            "features": [],
                        }
                    ],
                },
                "version": 1,
            }
        )
    )
    raise SystemExit(0)

# Ordinary builds still only need a fake release artifact. Also leave a
# minimal Cargo.lock so post-build C6.2 inventory can resolve honestly.
release = Path.cwd() / "target" / "release"
if "--manifest-path" in argv:
    release = manifest.parent / "target" / "release"
release.mkdir(parents=True, exist_ok=True)
for artifact in (
    "lib_rextio_native.dylib",
    "lib_rextio_native.so",
    "_rextio_native.dll",
    "_rextio_native.pyd",
):
    (release / artifact).write_bytes(b"fake native library")
(release / f"lib{crate_name}.rlib").write_bytes(b"fake rust library")
lock_path = (manifest.parent if manifest.exists() else Path.cwd()) / "Cargo.lock"
if not lock_path.exists():
    lock_path.write_text(
        (
            "# This file is automatically @generated by Cargo.\\n"
            "version = 4\\n\\n"
            "[[package]]\\n"
            f'name = "{name}"\\n'
            f'version = "{version}"\\n'
        ),
        encoding="utf-8",
    )
""",
        encoding="utf-8",
    )
    cargo.chmod(0o755)
    monkeypatch.setenv("PATH", f"{bin_dir}{os.pathsep}{os.environ.get('PATH', '')}")

    # Higher-level build tests exercise evidence policy/transactions with fake
    # artifact bytes. Keep them compiler-independent while retaining the exact
    # installed-path -> wheel-member hash/size binding. Dedicated runtime tests
    # do not request this fixture and therefore run the real header/parser code.
    from rextio.artifacts.evidence import (
        REASON_RUNTIME_WHEEL_MEMBER_MISMATCH,
        ArtifactEvidenceError,
        NativeRuntimeInventory,
        WheelEntryRef,
        hash_regular_file,
    )
    from rextio.build import supply_chain as supply_chain_module

    def synthetic_runtime_inventory(
        *,
        installed_path: Path | None,
        expected_python_root: Path,
        wheel_entries: tuple[WheelEntryRef, ...],
        target_triple: str,
        timeout: float,
    ) -> NativeRuntimeInventory:
        del timeout
        if installed_path is None:
            raise ArtifactEvidenceError(
                "synthetic native binary is missing",
                reason=REASON_RUNTIME_WHEEL_MEMBER_MISMATCH,
            )
        binary = Path(installed_path).resolve(strict=True)
        root = expected_python_root.resolve(strict=True)
        member_name = binary.relative_to(root).as_posix()
        matches = [entry for entry in wheel_entries if entry.name == member_name]
        digest, size = hash_regular_file(binary)
        if (
            len(matches) != 1
            or matches[0].sha256 != digest
            or matches[0].uncompressed_size != size
        ):
            raise ArtifactEvidenceError(
                "synthetic wheel member does not match the installed binary",
                reason=REASON_RUNTIME_WHEEL_MEMBER_MISMATCH,
            )
        arch_token = target_triple.split("-", 1)[0].lower()
        if arch_token in {"aarch64", "arm64"}:
            architecture = "aarch64"
        elif arch_token == "x86_64":
            architecture = "x86_64"
        elif arch_token.startswith("arm") or arch_token.startswith("thumb"):
            architecture = "arm"
        else:
            architecture = "x86"
        format_name = "mach-o" if "apple-darwin" in target_triple else "elf"
        entry = matches[0]
        return NativeRuntimeInventory(
            format=format_name,
            architecture=architecture,
            inspector="otool" if format_name == "mach-o" else "readelf",
            subject_basename=binary.name,
            subject_sha256=digest,
            subject_size=size,
            wheel_member=entry.name,
            wheel_member_sha256=entry.sha256,
            wheel_member_size=entry.uncompressed_size,
        )

    monkeypatch.setattr(
        supply_chain_module,
        "inspect_native_runtime_inventory",
        synthetic_runtime_inventory,
    )
    return cargo


@pytest.fixture
def fake_maturin(tmp_path: Path, monkeypatch: pytest.MonkeyPatch) -> Path:
    bin_dir = tmp_path / "fake-maturin-bin"
    bin_dir.mkdir()
    maturin = bin_dir / "maturin"
    maturin.write_text(
        """#!/usr/bin/env python3
import sys
import zipfile
from pathlib import Path

out = Path(sys.argv[sys.argv.index("--out") + 1])
out.mkdir(parents=True, exist_ok=True)
wheel = out / "rextio_generated_native-0.1.0-py3-none-any.whl"
with zipfile.ZipFile(wheel, "w") as archive:
    archive.writestr("_rextio_native.cpython-311-darwin.so", b"fake native library")
""",
        encoding="utf-8",
    )
    maturin.chmod(0o755)
    monkeypatch.setenv("PATH", f"{bin_dir}{os.pathsep}{os.environ.get('PATH', '')}")
    return maturin


@pytest.fixture
def fake_nuitka(tmp_path: Path, monkeypatch: pytest.MonkeyPatch) -> Path:
    bin_dir = tmp_path / "fake-nuitka-bin"
    bin_dir.mkdir()
    nuitka = bin_dir / "nuitka"
    nuitka.write_text(
        """#!/usr/bin/env python3
import sys
from pathlib import Path

args = sys.argv[1:]
if "--version" in args:
    print("2.4.8")
    sys.exit(0)
source = Path(args[args.index("--module") + 1])
output_arg = next(arg for arg in args if arg == "--output-dir" or arg.startswith("--output-dir="))
if output_arg == "--output-dir":
    out = Path(args[args.index("--output-dir") + 1])
else:
    out = Path(output_arg.split("=", 1)[1])
out.mkdir(parents=True, exist_ok=True)
(out / f"{source.stem}.cpython-311-darwin.so").write_bytes(b"fake nuitka module")
log = Path(__file__).with_name("nuitka.log")
with log.open("a", encoding="utf-8") as handle:
    handle.write(" ".join(args) + "\\n")
""",
        encoding="utf-8",
    )
    nuitka.chmod(0o755)
    monkeypatch.setenv("PATH", f"{bin_dir}{os.pathsep}{os.environ.get('PATH', '')}")
    return nuitka
