"""Rendering of Cargo/pyproject manifests for the generated Rust project."""

from __future__ import annotations

# Crate names the generated manifests always declare themselves. Plugins may
# not inject dependencies with these names: the loader rejects the collision
# up front (docs/specs/plugin-lowering.md section 5) instead of leaving it to
# a confusing cargo resolver error.
CORE_CRATE_NAMES = frozenset({"base64", "chrono", "log", "pyo3", "sha2", "serde", "serde_json"})


def render_cargo_toml(
    package_name: str = "rextio_generated_native",
    extra_dependencies: tuple[tuple[str, str, tuple[str, ...]], ...] = (),
) -> str:
    """Render the Cargo.toml for the generated native extension crate.

    ``extra_dependencies`` are plugin-injected ``(name, exact_version_pin,
    features)`` triples (docs/specs/plugin-lowering.md section 5), appended to
    the ``[dependencies]`` block sorted by name. Two plugins may legitimately
    pin the same crate at the same version (the loader rejects version
    CONFLICTS only), so entries are merged per crate here — a duplicate TOML
    key would break cargo (council round 5) — with features unioned sorted.
    """
    extra_lines = _render_extra_dependency_lines(extra_dependencies)
    return f"""# Generated by Rextio. Do not edit manually.

[package]
name = "{package_name}"
version = "0.1.0"
edition = "2021"
# Documented MSRV (PyO3 0.29 floor); cargo enforces it at build time.
rust-version = "1.83"

[lib]
name = "_rextio_native"
crate-type = ["cdylib"]

# Preserve Python integer semantics: i64 arithmetic that overflows is a real error
# (Python ints are arbitrary precision), so overflow must panic — PyO3 converts the
# panic into a Python exception — instead of silently wrapping in release builds.
[profile.release]
overflow-checks = true

[dependencies]
base64 = "0.22"
chrono = "0.4"
log = "0.4"
pyo3 = {{ version = "0.29", features = ["extension-module"] }}
sha2 = "0.10"
{extra_lines}"""


def _render_extra_dependency_lines(
    extra_dependencies: tuple[tuple[str, str, tuple[str, ...]], ...] = (),
) -> str:
    """Merge and render plugin-injected ``(name, pin, features)`` triples."""
    merged: dict[tuple[str, str], set[str]] = {}
    for name, version, features in extra_dependencies:
        merged.setdefault((name, version), set()).update(features)
    lines = ""
    for (name, version), feature_set in sorted(merged.items()):
        if feature_set:
            feature_list = ", ".join(f'"{feature}"' for feature in sorted(feature_set))
            lines += f'{name} = {{ version = "{version}", features = [{feature_list}] }}\n'
        else:
            lines += f'{name} = "{version}"\n'
    return lines


def render_importable_cargo_toml(
    package_name: str = "rextio_generated_rust",
    extra_dependencies: tuple[tuple[str, str, tuple[str, ...]], ...] = (),
) -> str:
    """Render the Cargo.toml for the Rust-importable crate.

    ``extra_dependencies`` are profile-specific plugin capability crates for
    standalone-capable plugin functions (plugin API 1.4), never the host-
    extension ``crate_dependencies()`` surface.
    """
    extra_lines = _render_extra_dependency_lines(extra_dependencies)
    return f"""# Generated by Rextio. Do not edit manually.

[package]
name = "{package_name}"
version = "0.1.0"
edition = "2021"
# Uniform documented MSRV shared with the extension template (whose floor
# is set by PyO3 0.29); this crate itself has no PyO3 dependency.
rust-version = "1.83"

[lib]
name = "{package_name.replace("-", "_")}"

# Integer overflow is an error (Python ints are arbitrary precision), so it must
# panic rather than silently wrap, even in release builds.
[profile.release]
overflow-checks = true

[dependencies]
base64 = "0.22"
chrono = "0.4"
log = "0.4"
sha2 = "0.10"
{extra_lines}"""


def render_binary_cargo_toml(
    package_name: str = "rextio_generated_bin",
    binary_name: str = "rextio_app",
    *,
    hybrid: bool = False,
    extra_dependencies: tuple[tuple[str, str, tuple[str, ...]], ...] = (),
) -> str:
    """Render the Cargo.toml for the generated Rust executable (bin) crate.

    A standalone native binary (no PyO3). When ``hybrid`` is set, the binary
    delegates non-native calls to an external CPython process and needs
    ``serde``/``serde_json`` for the wire protocol. The binary lives in
    ``src/main.rs``. ``extra_dependencies`` are profile-specific plugin
    capability crates (plugin API 1.4).
    """
    hybrid_dependencies = (
        'serde = { version = "1", features = ["derive"] }\nserde_json = "1"\n' if hybrid else ""
    )
    extra_lines = _render_extra_dependency_lines(extra_dependencies)
    return f"""# Generated by Rextio. Do not edit manually.

[package]
name = "{package_name}"
version = "0.1.0"
edition = "2021"
# Uniform documented MSRV shared with the extension template (whose floor
# is set by PyO3 0.29); this crate itself has no PyO3 dependency.
rust-version = "1.83"

[[bin]]
name = "{binary_name}"
path = "src/main.rs"

# Integer overflow is an error (Python ints are arbitrary precision), so it must
# panic rather than silently wrap, even in release builds.
[profile.release]
overflow-checks = true

[dependencies]
base64 = "0.22"
chrono = "0.4"
log = "0.4"
sha2 = "0.10"
{hybrid_dependencies}{extra_lines}"""


def render_pyproject_toml() -> str:
    """Render the pyproject.toml for the maturin/PyO3 build."""
    return """# Generated by Rextio. Do not edit manually.

[build-system]
requires = ["maturin>=1.0,<2.0"]
build-backend = "maturin"

[project]
name = "rextio-generated-native"
version = "0.1.0"
requires-python = ">=3.11"
"""


def render_cargo_config_toml() -> str:
    """Render the Cargo config.toml for the generated build.

    Only macOS needs extra link flags. A PyO3 ``extension-module`` cdylib must
    leave the CPython C-API symbols undefined (they are resolved when the host
    interpreter loads the module), and the macOS linker rejects undefined symbols
    by default, so ``-undefined dynamic_lookup`` is required there. Linux and
    Windows need no flags: a Linux cdylib permits undefined symbols by default,
    and on Windows the PyO3 build script links the Python import library and
    produces a ``.dll`` directly. The sections below are target-scoped, so they
    apply only on the matching Apple targets while other platforms fall through to
    Cargo's defaults. (The compiled artifact is then located per-platform --
    ``lib_rextio_native.dylib`` / ``.so`` or ``_rextio_native.dll`` -- in
    ``cargo_builder._find_cargo_artifact``.)
    """
    return """# Generated by Rextio. Do not edit manually.

[target.aarch64-apple-darwin]
rustflags = ["-C", "link-arg=-undefined", "-C", "link-arg=dynamic_lookup"]

[target.x86_64-apple-darwin]
rustflags = ["-C", "link-arg=-undefined", "-C", "link-arg=dynamic_lookup"]
"""
