from __future__ import annotations


def render_cargo_toml(package_name: str = "rextio_generated_native") -> str:
    return f"""# Generated by Rextio. Do not edit manually.

[package]
name = "{package_name}"
version = "0.1.0"
edition = "2021"

[lib]
name = "_rextio_native"
crate-type = ["cdylib"]

[dependencies]
pyo3 = {{ version = "0.22", features = ["extension-module"] }}
"""


def render_pyproject_toml() -> str:
    return """# Generated by Rextio. Do not edit manually.

[build-system]
requires = ["maturin>=1.0,<2.0"]
build-backend = "maturin"

[project]
name = "rextio-generated-native"
version = "0.1.0"
requires-python = ">=3.11"
"""
