"""Render the strict installed-distribution runtime guard."""

from __future__ import annotations

import base64

from rextio.codegen.rust.rust_format import rust_string_literal
from rextio.source.external_linkage import ExternalRuntimeGuard


def render_external_runtime_guard(guard: ExternalRuntimeGuard) -> str:
    """Render one fail-closed guard without importing external Python code.

    The reached callable identities have already been proven against the signed
    source snapshot and lowered into private Rust helpers.  Runtime validation
    therefore verifies only the installed distribution/version/member and the
    exact source bytes.  Importing the original module here would execute its
    top-level Python before the guard could report a mismatch.
    """
    if type(guard) is not ExternalRuntimeGuard:
        raise TypeError("external runtime guard has an invalid type")
    distribution = rust_string_literal(guard.distribution)
    version = rust_string_literal(guard.version)
    dist_info_root = rust_string_literal(guard.dist_info_root)
    metadata_member = rust_string_literal(guard.metadata_member)
    metadata_sha256 = rust_string_literal(guard.metadata_sha256)
    record_member = rust_string_literal(guard.record_member)
    expected_record_rows = [
        (
            guard.metadata_member,
            "sha256="
            + base64.urlsafe_b64encode(bytes.fromhex(guard.metadata_sha256))
            .decode("ascii")
            .rstrip("="),
            str(guard.metadata_size),
        ),
        *(
            (
                module.source_member,
                "sha256="
                + base64.urlsafe_b64encode(bytes.fromhex(module.source_sha256))
                .decode("ascii")
                .rstrip("="),
                str(module.source_size),
            )
            for module in guard.modules
        ),
        (guard.record_member, "", ""),
    ]
    lines = [
        "fn __rextio_external_guard_error() -> PyErr {",
        "    pyo3::exceptions::PyImportError::new_err(",
        '        "RXT060 external source runtime identity verification failed",',
        "    )",
        "}",
        "",
        "fn __rextio_normalize_distribution_name(value: &str) -> String {",
        "    let mut result = String::with_capacity(value.len());",
        "    let mut separator = false;",
        "    for character in value.chars() {",
        "        if matches!(character, '-' | '_' | '.') {",
        "            separator = !result.is_empty();",
        "        } else {",
        "            if separator {",
        "                result.push('-');",
        "                separator = false;",
        "            }",
        "            result.push(character.to_ascii_lowercase());",
        "        }",
        "    }",
        "    result",
        "}",
        "",
        "fn __rextio_distribution_name_is_safe(value: &str) -> bool {",
        "    value.len() <= 128",
        "        && value",
        "            .as_bytes()",
        "            .first()",
        "            .is_some_and(|byte| byte.is_ascii_alphanumeric())",
        "        && value",
        "            .as_bytes()",
        "            .last()",
        "            .is_some_and(|byte| byte.is_ascii_alphanumeric())",
        "        && value.bytes().all(|byte| {",
        "            byte.is_ascii_alphanumeric() || matches!(byte, b'-' | b'_' | b'.')",
        "        })",
        "}",
        "",
        '#[cfg(target_os = "linux")]',
        "const __REXTIO_O_NOFOLLOW: i32 = 0o400000;",
        '#[cfg(target_os = "linux")]',
        "const __REXTIO_O_DIRECTORY: i32 = 0o200000;",
        '#[cfg(target_os = "linux")]',
        "const __REXTIO_O_CLOEXEC: i32 = 0o2000000;",
        '#[cfg(target_os = "linux")]',
        "const __REXTIO_O_NONBLOCK: i32 = 0o4000;",
        '#[cfg(target_os = "macos")]',
        "const __REXTIO_O_NOFOLLOW: i32 = 0x00000100;",
        '#[cfg(target_os = "macos")]',
        "const __REXTIO_O_DIRECTORY: i32 = 0x00100000;",
        '#[cfg(target_os = "macos")]',
        "const __REXTIO_O_CLOEXEC: i32 = 0x01000000;",
        '#[cfg(target_os = "macos")]',
        "const __REXTIO_O_NONBLOCK: i32 = 0x00000004;",
        "",
        '#[cfg(any(target_os = "linux", target_os = "macos"))]',
        'unsafe extern "C" {',
        '    #[link_name = "openat"]',
        "    fn __rextio_openat(",
        "        directory_fd: std::os::raw::c_int,",
        "        path: *const std::os::raw::c_char,",
        "        flags: std::os::raw::c_int,",
        "        ...",
        "    ) -> std::os::raw::c_int;",
        "}",
        "",
        '#[cfg(any(target_os = "linux", target_os = "macos"))]',
        "fn __rextio_open_external_filesystem_root() -> PyResult<std::fs::File> {",
        "    use std::os::unix::fs::OpenOptionsExt as _;",
        "    let directory = std::fs::OpenOptions::new()",
        "        .read(true)",
        "        .custom_flags(",
        "            __REXTIO_O_NOFOLLOW | __REXTIO_O_DIRECTORY | __REXTIO_O_CLOEXEC,",
        "        )",
        '        .open(std::path::Path::new("/"))',
        "        .map_err(|_| __rextio_external_guard_error())?;",
        "    let metadata = directory",
        "        .metadata()",
        "        .map_err(|_| __rextio_external_guard_error())?;",
        "    if !metadata.is_dir() {",
        "        return Err(__rextio_external_guard_error());",
        "    }",
        "    Ok(directory)",
        "}",
        "",
        '#[cfg(any(target_os = "linux", target_os = "macos"))]',
        "fn __rextio_open_external_at(",
        "    directory: &std::fs::File,",
        "    component: &str,",
        "    expect_directory: bool,",
        ") -> PyResult<std::fs::File> {",
        "    use std::os::fd::{AsRawFd as _, FromRawFd as _};",
        "    let component = std::ffi::CString::new(component)",
        "        .map_err(|_| __rextio_external_guard_error())?;",
        "    let mut flags = __REXTIO_O_NOFOLLOW | __REXTIO_O_CLOEXEC;",
        "    if expect_directory {",
        "        flags |= __REXTIO_O_DIRECTORY;",
        "    } else {",
        "        flags |= __REXTIO_O_NONBLOCK;",
        "    }",
        "    // SAFETY: `component` is a live NUL-terminated C string, the",
        "    // directory descriptor remains owned for this call, and O_CREAT",
        "    // is absent so openat consumes no variadic mode argument.",
        "    let descriptor = unsafe {",
        "        __rextio_openat(directory.as_raw_fd(), component.as_ptr(), flags)",
        "    };",
        "    if descriptor < 0 {",
        "        return Err(__rextio_external_guard_error());",
        "    }",
        "    // SAFETY: a non-negative openat result is a new owned descriptor",
        "    // which is transferred exactly once into File for RAII close.",
        "    let file = unsafe { std::fs::File::from_raw_fd(descriptor) };",
        "    if expect_directory",
        "        && !file",
        "            .metadata()",
        "            .map_err(|_| __rextio_external_guard_error())?",
        "            .is_dir()",
        "    {",
        "        return Err(__rextio_external_guard_error());",
        "    }",
        "    Ok(file)",
        "}",
        "",
        '#[cfg(any(target_os = "linux", target_os = "macos"))]',
        "fn __rextio_open_external_root(",
        "    path: &std::path::Path,",
        ") -> PyResult<std::fs::File> {",
        "    let raw = path",
        "        .to_str()",
        "        .ok_or_else(__rextio_external_guard_error)?;",
        '    if !raw.starts_with(\'/\') || (raw != "/" && raw.ends_with(\'/\')) {',
        "        return Err(__rextio_external_guard_error());",
        "    }",
        "    let mut directory = __rextio_open_external_filesystem_root()?;",
        '    if raw == "/" {',
        "        return Ok(directory);",
        "    }",
        "    for component in raw[1..].split('/') {",
        '        if component.is_empty() || component == "." || component == ".." {',
        "            return Err(__rextio_external_guard_error());",
        "        }",
        "        directory = __rextio_open_external_at(&directory, component, true)?;",
        "    }",
        "    Ok(directory)",
        "}",
        "",
        '#[cfg(any(target_os = "linux", target_os = "macos"))]',
        "fn __rextio_read_external_member(",
        "    root: &std::path::Path,",
        "    member: &str,",
        "    minimum_size: u64,",
        "    maximum_size: u64,",
        ") -> PyResult<Vec<u8>> {",
        "    use std::io::Read as _;",
        "    use std::os::unix::fs::MetadataExt as _;",
        "    let mut directory = __rextio_open_external_root(root)?;",
        "    let mut parts = member.split('/').peekable();",
        "    while let Some(part) = parts.next() {",
        '        if part.is_empty() || part == "." || part == ".." {',
        "            return Err(__rextio_external_guard_error());",
        "        }",
        "        if parts.peek().is_some() {",
        "            directory = __rextio_open_external_at(&directory, part, true)?;",
        "            continue;",
        "        }",
        "        let mut source = __rextio_open_external_at(&directory, part, false)?;",
        "        let before = source",
        "            .metadata()",
        "            .map_err(|_| __rextio_external_guard_error())?;",
        "        if !before.is_file()",
        "            || before.nlink() != 1",
        "            || minimum_size > maximum_size",
        "            || before.len() < minimum_size",
        "            || before.len() > maximum_size",
        "        {",
        "            return Err(__rextio_external_guard_error());",
        "        }",
        "        let capacity = usize::try_from(before.len())",
        "            .map_err(|_| __rextio_external_guard_error())?;",
        "        let mut bytes = Vec::with_capacity(capacity);",
        "        source",
        "            .by_ref()",
        "            .take(maximum_size + 1)",
        "            .read_to_end(&mut bytes)",
        "            .map_err(|_| __rextio_external_guard_error())?;",
        "        let after = source",
        "            .metadata()",
        "            .map_err(|_| __rextio_external_guard_error())?;",
        "        if bytes.len() != capacity",
        "            || before.dev() != after.dev()",
        "            || before.ino() != after.ino()",
        "            || before.nlink() != after.nlink()",
        "            || before.len() != after.len()",
        "            || before.mtime() != after.mtime()",
        "            || before.mtime_nsec() != after.mtime_nsec()",
        "            || before.ctime() != after.ctime()",
        "            || before.ctime_nsec() != after.ctime_nsec()",
        "        {",
        "            return Err(__rextio_external_guard_error());",
        "        }",
        "        return Ok(bytes);",
        "    }",
        "    Err(__rextio_external_guard_error())",
        "}",
        "",
        '#[cfg(not(any(target_os = "linux", target_os = "macos")))]',
        "fn __rextio_read_external_member(",
        "    _root: &std::path::Path,",
        "    _member: &str,",
        "    _minimum_size: u64,",
        "    _maximum_size: u64,",
        ") -> PyResult<Vec<u8>> {",
        "    Err(__rextio_external_guard_error())",
        "}",
        "",
        "const __REXTIO_EXTERNAL_RECORD_MAX_BYTES: u64 = 8 * 1024 * 1024;",
        "const __REXTIO_EXTERNAL_RECORD_MAX_ROWS: usize = 4096;",
        "const __REXTIO_EXTERNAL_RECORD_MAX_FIELD_BYTES: usize = 512;",
        "const __REXTIO_EXTERNAL_METADATA_MAX_ROWS: usize = 4096;",
        "const __REXTIO_EXTERNAL_METADATA_MAX_LINE_BYTES: usize = 8192;",
        "const __REXTIO_EXTERNAL_METADATA_MAX_VALUE_BYTES: usize = 4096;",
        "",
        "fn __rextio_verify_external_metadata(",
        "    bytes: &[u8],",
        "    expected_name: &str,",
        "    expected_version: &str,",
        ") -> PyResult<()> {",
        "    let text = std::str::from_utf8(bytes)",
        "        .map_err(|_| __rextio_external_guard_error())?;",
        "    if bytes.contains(&0) {",
        "        return Err(__rextio_external_guard_error());",
        "    }",
        "    let mut name_seen = false;",
        "    let mut version_seen = false;",
        "    let mut previous_sensitive = false;",
        "    for (index, raw_line) in text.split('\\n').enumerate() {",
        "        if index >= __REXTIO_EXTERNAL_METADATA_MAX_ROWS {",
        "            return Err(__rextio_external_guard_error());",
        "        }",
        "        let line = raw_line.strip_suffix('\\r').unwrap_or(raw_line);",
        "        if line.as_bytes().len() > __REXTIO_EXTERNAL_METADATA_MAX_LINE_BYTES",
        "            || line.contains('\\r')",
        "        {",
        "            return Err(__rextio_external_guard_error());",
        "        }",
        "        if line.is_empty() {",
        "            break;",
        "        }",
        "        if line.starts_with(' ') || line.starts_with('\\t') {",
        "            if previous_sensitive {",
        "                return Err(__rextio_external_guard_error());",
        "            }",
        "            continue;",
        "        }",
        "        let (key, raw_value) = line",
        "            .split_once(':')",
        "            .ok_or_else(__rextio_external_guard_error)?;",
        "        if key.is_empty()",
        "            || key.len() > 128",
        "            || !key",
        "                .bytes()",
        "                .all(|byte| byte.is_ascii_alphanumeric() || byte == b'-')",
        "        {",
        "            return Err(__rextio_external_guard_error());",
        "        }",
        "        let value = raw_value",
        "            .trim_matches(|character| character == ' ' || character == '\\t');",
        "        if value.as_bytes().len() > __REXTIO_EXTERNAL_METADATA_MAX_VALUE_BYTES {",
        "            return Err(__rextio_external_guard_error());",
        "        }",
        "        let is_name = key.eq_ignore_ascii_case(\"Name\");",
        "        let is_version = key.eq_ignore_ascii_case(\"Version\");",
        "        previous_sensitive = is_name || is_version;",
        "        if is_name {",
        "            if key != \"Name\"",
        "                || name_seen",
        "                || !__rextio_distribution_name_is_safe(value)",
        "                || __rextio_normalize_distribution_name(value)",
        "                    != __rextio_normalize_distribution_name(expected_name)",
        "            {",
        "                return Err(__rextio_external_guard_error());",
        "            }",
        "            name_seen = true;",
        "        } else if is_version {",
        "            if key != \"Version\" || version_seen || value != expected_version {",
        "                return Err(__rextio_external_guard_error());",
        "            }",
        "            version_seen = true;",
        "        }",
        "    }",
        "    if !name_seen || !version_seen {",
        "        return Err(__rextio_external_guard_error());",
        "    }",
        "    Ok(())",
        "}",
        "",
        "fn __rextio_finish_external_record_field(",
        "    fields: &mut Vec<String>,",
        "    field: &mut Vec<u8>,",
        ") -> PyResult<()> {",
        "    if fields.len() >= 3 || field.len() > __REXTIO_EXTERNAL_RECORD_MAX_FIELD_BYTES {",
        "        return Err(__rextio_external_guard_error());",
        "    }",
        "    let value = std::str::from_utf8(field)",
        "        .map_err(|_| __rextio_external_guard_error())?",
        "        .to_owned();",
        "    fields.push(value);",
        "    field.clear();",
        "    Ok(())",
        "}",
        "",
        "fn __rextio_finish_external_record_row<F>(",
        "    fields: &mut Vec<String>,",
        "    field: &mut Vec<u8>,",
        "    row_count: &mut usize,",
        "    visit: &mut F,",
        ") -> PyResult<()> ",
        "where",
        "    F: FnMut(&str, &str, &str) -> PyResult<()>,",
        "{",
        "    __rextio_finish_external_record_field(fields, field)?;",
        "    if fields.len() != 3 || *row_count >= __REXTIO_EXTERNAL_RECORD_MAX_ROWS {",
        "        return Err(__rextio_external_guard_error());",
        "    }",
        "    *row_count += 1;",
        "    visit(&fields[0], &fields[1], &fields[2])?;",
        "    fields.clear();",
        "    Ok(())",
        "}",
        "",
        "fn __rextio_parse_external_record<F>(bytes: &[u8], mut visit: F) -> PyResult<()> ",
        "where",
        "    F: FnMut(&str, &str, &str) -> PyResult<()>,",
        "{",
        "    if bytes.is_empty() || bytes.len() > __REXTIO_EXTERNAL_RECORD_MAX_BYTES as usize {",
        "        return Err(__rextio_external_guard_error());",
        "    }",
        "    let mut index = 0usize;",
        "    let mut field = Vec::new();",
        "    let mut fields = Vec::with_capacity(3);",
        "    let mut row_count = 0usize;",
        "    let mut in_quotes = false;",
        "    let mut after_quote = false;",
        "    let mut at_field_start = true;",
        "    while index < bytes.len() {",
        "        let byte = bytes[index];",
        "        if in_quotes {",
        "            if byte == b'\"' {",
        "                if index + 1 < bytes.len() && bytes[index + 1] == b'\"' {",
        "                    if field.len() >= __REXTIO_EXTERNAL_RECORD_MAX_FIELD_BYTES {",
        "                        return Err(__rextio_external_guard_error());",
        "                    }",
        "                    field.push(b'\"');",
        "                    index += 2;",
        "                    continue;",
        "                }",
        "                in_quotes = false;",
        "                after_quote = true;",
        "                index += 1;",
        "                continue;",
        "            }",
        "            if field.len() >= __REXTIO_EXTERNAL_RECORD_MAX_FIELD_BYTES {",
        "                return Err(__rextio_external_guard_error());",
        "            }",
        "            field.push(byte);",
        "            index += 1;",
        "            continue;",
        "        }",
        "        if after_quote {",
        "            if byte == b',' {",
        "                __rextio_finish_external_record_field(&mut fields, &mut field)?;",
        "                after_quote = false;",
        "                at_field_start = true;",
        "                index += 1;",
        "                continue;",
        "            }",
        "            if byte == b'\\n' || byte == b'\\r' {",
        "                if byte == b'\\r'",
        "                    && (index + 1 >= bytes.len() || bytes[index + 1] != b'\\n')",
        "                {",
        "                    return Err(__rextio_external_guard_error());",
        "                }",
        "                __rextio_finish_external_record_row(",
        "                    &mut fields, &mut field, &mut row_count, &mut visit,",
        "                )?;",
        "                after_quote = false;",
        "                at_field_start = true;",
        "                index += if byte == b'\\r' { 2 } else { 1 };",
        "                continue;",
        "            }",
        "            return Err(__rextio_external_guard_error());",
        "        }",
        "        if byte == b'\"' {",
        "            if !at_field_start {",
        "                return Err(__rextio_external_guard_error());",
        "            }",
        "            in_quotes = true;",
        "            at_field_start = false;",
        "            index += 1;",
        "        } else if byte == b',' {",
        "            __rextio_finish_external_record_field(&mut fields, &mut field)?;",
        "            at_field_start = true;",
        "            index += 1;",
        "        } else if byte == b'\\n' || byte == b'\\r' {",
        "            if byte == b'\\r'",
        "                && (index + 1 >= bytes.len() || bytes[index + 1] != b'\\n')",
        "            {",
        "                return Err(__rextio_external_guard_error());",
        "            }",
        "            __rextio_finish_external_record_row(",
        "                &mut fields, &mut field, &mut row_count, &mut visit,",
        "            )?;",
        "            at_field_start = true;",
        "            index += if byte == b'\\r' { 2 } else { 1 };",
        "        } else {",
        "            if field.len() >= __REXTIO_EXTERNAL_RECORD_MAX_FIELD_BYTES {",
        "                return Err(__rextio_external_guard_error());",
        "            }",
        "            field.push(byte);",
        "            at_field_start = false;",
        "            index += 1;",
        "        }",
        "    }",
        "    if in_quotes {",
        "        return Err(__rextio_external_guard_error());",
        "    }",
        "    if !fields.is_empty() || !field.is_empty() || !at_field_start || after_quote {",
        "        __rextio_finish_external_record_row(",
        "            &mut fields, &mut field, &mut row_count, &mut visit,",
        "        )?;",
        "    }",
        "    if row_count == 0 {",
        "        return Err(__rextio_external_guard_error());",
        "    }",
        "    Ok(())",
        "}",
        "",
        "fn __rextio_external_record_path_is_safe(path: &str) -> bool {",
        "    !path.is_empty()",
        "        && path.len() <= __REXTIO_EXTERNAL_RECORD_MAX_FIELD_BYTES",
        "        && !path.starts_with('/')",
        "        && !path.contains('\\\\')",
        "        && !path",
        "            .chars()",
        "            .any(|character| character.is_control())",
        "        && path",
        "            .split('/')",
        "            .all(|part| !part.is_empty() && part != \".\" && part != \"..\")",
        "}",
        "",
        "fn __rextio_external_record_binding_is_safe(hash: &str, size: &str) -> bool {",
        "    if hash.is_empty() || size.is_empty() {",
        "        return hash.is_empty() && size.is_empty();",
        "    }",
        "    let Some(digest) = hash.strip_prefix(\"sha256=\") else {",
        "        return false;",
        "    };",
        "    digest.len() == 43",
        "        && digest",
        "            .bytes()",
        "            .all(|byte| byte.is_ascii_alphanumeric() || byte == b'_' || byte == b'-')",
        "        && digest",
        "            .as_bytes()",
        "            .last()",
        "            .is_some_and(|byte| b\"AEIMQUYcgkosw048\".contains(byte))",
        "        && !size.is_empty()",
        "        && size.bytes().all(|byte| byte.is_ascii_digit())",
        "        && size",
        "            .parse::<u64>()",
        "            .is_ok_and(|value| value <= 50_000_000)",
        "}",
        "",
        "fn __rextio_verify_external_source(py: Python<'_>) -> PyResult<()> {",
        '    let importlib_metadata = PyModule::import(py, "importlib.metadata")',
        "        .map_err(|_| __rextio_external_guard_error())?;",
        f'    let distribution = importlib_metadata.call_method1("distribution", ({distribution},))',
        "        .map_err(|_| __rextio_external_guard_error())?;",
        '    let os = PyModule::import(py, "os")',
        "        .map_err(|_| __rextio_external_guard_error())?;",
        '    let located_root = distribution.call_method1("locate_file", ("",))',
        "        .map_err(|_| __rextio_external_guard_error())?;",
        '    let root_path: String = os.call_method1("fspath", (located_root,))',
        "        .and_then(|value| value.extract())",
        "        .map_err(|_| __rextio_external_guard_error())?;",
        "    let root_path = std::path::PathBuf::from(root_path);",
        "    if !root_path.is_absolute() {",
        "        return Err(__rextio_external_guard_error());",
        "    }",
        "    let metadata_bytes = __rextio_read_external_member(",
        "        &root_path,",
        f"        {metadata_member},",
        f"        {guard.metadata_size}u64,",
        f"        {guard.metadata_size}u64,",
        "    )?;",
        '    let metadata_digest = format!("{:x}", sha2::Sha256::digest(&metadata_bytes));',
        f"    if metadata_digest != {metadata_sha256} {{",
        "        return Err(__rextio_external_guard_error());",
        "    }",
        f"    __rextio_verify_external_metadata(&metadata_bytes, {distribution}, {version})?;",
        "    let record_bytes = __rextio_read_external_member(",
        "        &root_path,",
        f"        {record_member},",
        "        1u64,",
        "        __REXTIO_EXTERNAL_RECORD_MAX_BYTES,",
        "    )?;",
    ]
    lines.append(
        "    let mut expected_rows: [(&str, &str, &str, bool); "
        f"{len(expected_record_rows)}] = ["
    )
    for member, digest, size in expected_record_rows:
        lines.append(
            "        ("
            f"{rust_string_literal(member)}, {rust_string_literal(digest)}, "
            f"{rust_string_literal(size)}, false),"
        )
    lines.extend(
        [
            "    ];",
            "    __rextio_parse_external_record(&record_bytes, |name, hash, size| {",
            "        if !__rextio_external_record_path_is_safe(name)",
            "            || !__rextio_external_record_binding_is_safe(hash, size)",
            "        {",
            "            return Err(__rextio_external_guard_error());",
            "        }",
            "        for component in name.split('/') {",
            "            if component.to_ascii_lowercase().ends_with(\".dist-info\")",
            f"                && component != {dist_info_root}",
            "            {",
            "                return Err(__rextio_external_guard_error());",
            "            }",
            "        }",
            "        for expected in expected_rows.iter_mut() {",
            "            if name.eq_ignore_ascii_case(expected.0) {",
            "                if name != expected.0",
            "                    || expected.3",
            "                    || hash != expected.1",
            "                    || size != expected.2",
            "                {",
            "                    return Err(__rextio_external_guard_error());",
            "                }",
            "                expected.3 = true;",
            "            }",
            "        }",
            "        Ok(())",
            "    })?;",
            "    if expected_rows.iter().any(|expected| !expected.3) {",
            "        return Err(__rextio_external_guard_error());",
            "    }",
        ]
    )
    for module_index, module in enumerate(guard.modules):
        module_name = rust_string_literal(module.module_name)
        source_member = rust_string_literal(module.source_member)
        source_sha256 = rust_string_literal(module.source_sha256)
        suffix = str(module_index)
        lines.extend(
            [
                f"    let _signed_module_{suffix} = ({module_name}, {source_member}, {module.source_size}u64);",
            ]
        )
        for callable_index, callable_identity in enumerate(module.callables):
            qualname = rust_string_literal(callable_identity.qualname)
            lines.append(
                f"    let _signed_callable_{module_index}_{callable_index} = ({qualname}, {callable_identity.first_line}i64);"
            )
        lines.extend(
            [
                f"    let source_{suffix} = __rextio_read_external_member(",
                "        &root_path,",
                f"        {source_member},",
                f"        {module.source_size}u64,",
                f"        {module.source_size}u64,",
                "    )?;",
                f'    let digest_{suffix} = format!("{{:x}}", sha2::Sha256::digest(&source_{suffix}));',
                f"    if digest_{suffix} != {source_sha256} {{",
                "        return Err(__rextio_external_guard_error());",
                "    }",
            ]
        )
    lines.extend(["    Ok(())", "}"])
    return "\n".join(lines)


__all__ = ["render_external_runtime_guard"]
