"""Render the strict C5.2 installed-distribution runtime guard."""

from __future__ import annotations

from rextio.codegen.rust.rust_format import rust_string_literal
from rextio.source.external_linkage import ExternalRuntimeGuard


def render_external_runtime_guard(guard: ExternalRuntimeGuard) -> str:
    """Render one fail-closed guard without importing external Python code.

    The reached callable identities have already been proven against the signed
    source snapshot and lowered into private Rust helpers.  Runtime validation
    therefore verifies only the installed distribution/version/member and the
    exact source bytes.  Importing the original module here would execute its
    top-level Python before the guard could report a mismatch.
    """
    if type(guard) is not ExternalRuntimeGuard:
        raise TypeError("external runtime guard has an invalid type")
    distribution = rust_string_literal(guard.distribution)
    version = rust_string_literal(guard.version)
    lines = [
        "fn __rextio_external_guard_error() -> PyErr {",
        "    pyo3::exceptions::PyImportError::new_err(",
        '        "RXT060 external source runtime identity verification failed",',
        "    )",
        "}",
        "",
        "fn __rextio_normalize_distribution_name(value: &str) -> String {",
        "    let mut result = String::with_capacity(value.len());",
        "    let mut separator = false;",
        "    for character in value.chars() {",
        "        if matches!(character, '-' | '_' | '.') {",
        "            separator = !result.is_empty();",
        "        } else {",
        "            if separator {",
        "                result.push('-');",
        "                separator = false;",
        "            }",
        "            result.push(character.to_ascii_lowercase());",
        "        }",
        "    }",
        "    result",
        "}",
        "",
        '#[cfg(target_os = "linux")]',
        "const __REXTIO_O_NOFOLLOW: i32 = 0o400000;",
        '#[cfg(target_os = "linux")]',
        "const __REXTIO_O_DIRECTORY: i32 = 0o200000;",
        '#[cfg(target_os = "linux")]',
        "const __REXTIO_O_CLOEXEC: i32 = 0o2000000;",
        '#[cfg(target_os = "linux")]',
        "const __REXTIO_O_NONBLOCK: i32 = 0o4000;",
        '#[cfg(target_os = "macos")]',
        "const __REXTIO_O_NOFOLLOW: i32 = 0x00000100;",
        '#[cfg(target_os = "macos")]',
        "const __REXTIO_O_DIRECTORY: i32 = 0x00100000;",
        '#[cfg(target_os = "macos")]',
        "const __REXTIO_O_CLOEXEC: i32 = 0x01000000;",
        '#[cfg(target_os = "macos")]',
        "const __REXTIO_O_NONBLOCK: i32 = 0x00000004;",
        "",
        '#[cfg(any(target_os = "linux", target_os = "macos"))]',
        'unsafe extern "C" {',
        '    #[link_name = "openat"]',
        "    fn __rextio_openat(",
        "        directory_fd: std::os::raw::c_int,",
        "        path: *const std::os::raw::c_char,",
        "        flags: std::os::raw::c_int,",
        "        ...",
        "    ) -> std::os::raw::c_int;",
        "}",
        "",
        '#[cfg(any(target_os = "linux", target_os = "macos"))]',
        "fn __rextio_open_external_filesystem_root() -> PyResult<std::fs::File> {",
        "    use std::os::unix::fs::OpenOptionsExt as _;",
        "    let directory = std::fs::OpenOptions::new()",
        "        .read(true)",
        "        .custom_flags(",
        "            __REXTIO_O_NOFOLLOW | __REXTIO_O_DIRECTORY | __REXTIO_O_CLOEXEC,",
        "        )",
        '        .open(std::path::Path::new("/"))',
        "        .map_err(|_| __rextio_external_guard_error())?;",
        "    let metadata = directory",
        "        .metadata()",
        "        .map_err(|_| __rextio_external_guard_error())?;",
        "    if !metadata.is_dir() {",
        "        return Err(__rextio_external_guard_error());",
        "    }",
        "    Ok(directory)",
        "}",
        "",
        '#[cfg(any(target_os = "linux", target_os = "macos"))]',
        "fn __rextio_open_external_at(",
        "    directory: &std::fs::File,",
        "    component: &str,",
        "    expect_directory: bool,",
        ") -> PyResult<std::fs::File> {",
        "    use std::os::fd::{AsRawFd as _, FromRawFd as _};",
        "    let component = std::ffi::CString::new(component)",
        "        .map_err(|_| __rextio_external_guard_error())?;",
        "    let mut flags = __REXTIO_O_NOFOLLOW | __REXTIO_O_CLOEXEC;",
        "    if expect_directory {",
        "        flags |= __REXTIO_O_DIRECTORY;",
        "    } else {",
        "        flags |= __REXTIO_O_NONBLOCK;",
        "    }",
        "    // SAFETY: `component` is a live NUL-terminated C string, the",
        "    // directory descriptor remains owned for this call, and O_CREAT",
        "    // is absent so openat consumes no variadic mode argument.",
        "    let descriptor = unsafe {",
        "        __rextio_openat(directory.as_raw_fd(), component.as_ptr(), flags)",
        "    };",
        "    if descriptor < 0 {",
        "        return Err(__rextio_external_guard_error());",
        "    }",
        "    // SAFETY: a non-negative openat result is a new owned descriptor",
        "    // which is transferred exactly once into File for RAII close.",
        "    let file = unsafe { std::fs::File::from_raw_fd(descriptor) };",
        "    if expect_directory",
        "        && !file",
        "            .metadata()",
        "            .map_err(|_| __rextio_external_guard_error())?",
        "            .is_dir()",
        "    {",
        "        return Err(__rextio_external_guard_error());",
        "    }",
        "    Ok(file)",
        "}",
        "",
        '#[cfg(any(target_os = "linux", target_os = "macos"))]',
        "fn __rextio_open_external_root(",
        "    path: &std::path::Path,",
        ") -> PyResult<std::fs::File> {",
        "    let raw = path",
        "        .to_str()",
        "        .ok_or_else(__rextio_external_guard_error)?;",
        '    if !raw.starts_with(\'/\') || (raw != "/" && raw.ends_with(\'/\')) {',
        "        return Err(__rextio_external_guard_error());",
        "    }",
        "    let mut directory = __rextio_open_external_filesystem_root()?;",
        '    if raw == "/" {',
        "        return Ok(directory);",
        "    }",
        "    for component in raw[1..].split('/') {",
        '        if component.is_empty() || component == "." || component == ".." {',
        "            return Err(__rextio_external_guard_error());",
        "        }",
        "        directory = __rextio_open_external_at(&directory, component, true)?;",
        "    }",
        "    Ok(directory)",
        "}",
        "",
        '#[cfg(any(target_os = "linux", target_os = "macos"))]',
        "fn __rextio_read_external_member(",
        "    root: &std::path::Path,",
        "    member: &str,",
        "    expected_size: u64,",
        ") -> PyResult<Vec<u8>> {",
        "    use std::io::Read as _;",
        "    use std::os::unix::fs::MetadataExt as _;",
        "    let mut directory = __rextio_open_external_root(root)?;",
        "    let mut parts = member.split('/').peekable();",
        "    while let Some(part) = parts.next() {",
        '        if part.is_empty() || part == "." || part == ".." {',
        "            return Err(__rextio_external_guard_error());",
        "        }",
        "        if parts.peek().is_some() {",
        "            directory = __rextio_open_external_at(&directory, part, true)?;",
        "            continue;",
        "        }",
        "        let mut source = __rextio_open_external_at(&directory, part, false)?;",
        "        let before = source",
        "            .metadata()",
        "            .map_err(|_| __rextio_external_guard_error())?;",
        "        if !before.is_file() || before.nlink() != 1 || before.len() != expected_size {",
        "            return Err(__rextio_external_guard_error());",
        "        }",
        "        let capacity = usize::try_from(expected_size)",
        "            .map_err(|_| __rextio_external_guard_error())?;",
        "        let mut bytes = Vec::with_capacity(capacity);",
        "        source",
        "            .by_ref()",
        "            .take(expected_size + 1)",
        "            .read_to_end(&mut bytes)",
        "            .map_err(|_| __rextio_external_guard_error())?;",
        "        let after = source",
        "            .metadata()",
        "            .map_err(|_| __rextio_external_guard_error())?;",
        "        if bytes.len() != capacity",
        "            || before.dev() != after.dev()",
        "            || before.ino() != after.ino()",
        "            || before.nlink() != after.nlink()",
        "            || before.len() != after.len()",
        "            || before.mtime() != after.mtime()",
        "            || before.mtime_nsec() != after.mtime_nsec()",
        "            || before.ctime() != after.ctime()",
        "            || before.ctime_nsec() != after.ctime_nsec()",
        "        {",
        "            return Err(__rextio_external_guard_error());",
        "        }",
        "        return Ok(bytes);",
        "    }",
        "    Err(__rextio_external_guard_error())",
        "}",
        "",
        '#[cfg(not(any(target_os = "linux", target_os = "macos")))]',
        "fn __rextio_read_external_member(",
        "    _root: &std::path::Path,",
        "    _member: &str,",
        "    _expected_size: u64,",
        ") -> PyResult<Vec<u8>> {",
        "    Err(__rextio_external_guard_error())",
        "}",
        "",
        "fn __rextio_verify_external_source(py: Python<'_>) -> PyResult<()> {",
        '    let metadata = PyModule::import(py, "importlib.metadata")',
        "        .map_err(|_| __rextio_external_guard_error())?;",
        f'    let distribution = metadata.call_method1("distribution", ({distribution},))',
        "        .map_err(|_| __rextio_external_guard_error())?;",
        '    let installed_version: String = distribution.getattr("version")',
        "        .and_then(|value| value.extract())",
        "        .map_err(|_| __rextio_external_guard_error())?;",
        f"    if installed_version != {version} {{",
        "        return Err(__rextio_external_guard_error());",
        "    }",
        '    let installed_name: String = distribution.getattr("metadata")',
        '        .and_then(|value| value.get_item("Name"))',
        "        .and_then(|value| value.extract())",
        "        .map_err(|_| __rextio_external_guard_error())?;",
        "    if __rextio_normalize_distribution_name(&installed_name)",
        f"        != __rextio_normalize_distribution_name({distribution})",
        "    {",
        "        return Err(__rextio_external_guard_error());",
        "    }",
        '    let files = distribution.getattr("files")',
        "        .map_err(|_| __rextio_external_guard_error())?;",
        "    if files.is_none() {",
        "        return Err(__rextio_external_guard_error());",
        "    }",
        "    let mut installed_members = std::collections::HashSet::new();",
        "    for member in files",
        "        .try_iter()",
        "        .map_err(|_| __rextio_external_guard_error())?",
        "    {",
        "        let member = member.map_err(|_| __rextio_external_guard_error())?;",
        "        let member: String = member",
        "            .str()",
        "            .and_then(|value| value.extract())",
        "            .map_err(|_| __rextio_external_guard_error())?;",
        "        if !installed_members.insert(member) {",
        "            return Err(__rextio_external_guard_error());",
        "        }",
        "    }",
        '    let os = PyModule::import(py, "os")',
        "        .map_err(|_| __rextio_external_guard_error())?;",
        '    let located_root = distribution.call_method1("locate_file", ("",))',
        "        .map_err(|_| __rextio_external_guard_error())?;",
        '    let root_path: String = os.call_method1("fspath", (located_root,))',
        "        .and_then(|value| value.extract())",
        "        .map_err(|_| __rextio_external_guard_error())?;",
        "    let root_path = std::path::PathBuf::from(root_path);",
        "    if !root_path.is_absolute() {",
        "        return Err(__rextio_external_guard_error());",
        "    }",
    ]
    for module_index, module in enumerate(guard.modules):
        module_name = rust_string_literal(module.module_name)
        source_member = rust_string_literal(module.source_member)
        source_sha256 = rust_string_literal(module.source_sha256)
        suffix = str(module_index)
        lines.extend(
            [
                f"    let _signed_module_{suffix} = ({module_name}, {source_member}, {module.source_size}u64);",
            ]
        )
        for callable_index, callable_identity in enumerate(module.callables):
            qualname = rust_string_literal(callable_identity.qualname)
            lines.append(
                f"    let _signed_callable_{module_index}_{callable_index} = ({qualname}, {callable_identity.first_line}i64);"
            )
        lines.extend(
            [
                f"    if !installed_members.contains({source_member}) {{",
                "        return Err(__rextio_external_guard_error());",
                "    }",
                f'    let located_{suffix} = distribution.call_method1("locate_file", ({source_member},))',
                "        .map_err(|_| __rextio_external_guard_error())?;",
                f'    let located_path_{suffix}: String = os.call_method1("fspath", (located_{suffix},))',
                "        .and_then(|value| value.extract())",
                "        .map_err(|_| __rextio_external_guard_error())?;",
                f"    if std::path::PathBuf::from(located_path_{suffix}) != root_path.join({source_member}) {{",
                "        return Err(__rextio_external_guard_error());",
                "    }",
                f"    let source_{suffix} = __rextio_read_external_member(",
                "        &root_path,",
                f"        {source_member},",
                f"        {module.source_size}u64,",
                "    )?;",
                f'    let digest_{suffix} = format!("{{:x}}", sha2::Sha256::digest(&source_{suffix}));',
                f"    if digest_{suffix} != {source_sha256} {{",
                "        return Err(__rextio_external_guard_error());",
                "    }",
            ]
        )
    lines.extend(["    Ok(())", "}"])
    return "\n".join(lines)


__all__ = ["render_external_runtime_guard"]
