from __future__ import annotations

import json
import re

from rextio.codegen.native_names import native_function_name
from rextio.codegen.rust.pyo3 import render_pyo3_module
from rextio.codegen.rust.type_map import rust_type
from rextio.ir.nodes import (
    AppendIR,
    AssignIR,
    BinaryOpIR,
    BlockIR,
    BreakIR,
    CallIR,
    ComprehensionGeneratorIR,
    CompareIR,
    ContinueIR,
    DictComprehensionIR,
    DictIR,
    DictSetIR,
    EffectCallIR,
    ExprIR,
    ForIR,
    FunctionIR,
    IfIR,
    IndexIR,
    ListComprehensionIR,
    ListIR,
    LiteralIR,
    ModuleIR,
    NameIR,
    NamedExprIR,
    ReturnIR,
    SetComprehensionIR,
    SetIR,
    StatementIR,
    TargetIR,
    TupleIR,
    TupleTargetIR,
    UnaryOpIR,
    WhileIR,
)
from rextio.ir.types import (
    RxtBool,
    RxtBytes,
    RxtDict,
    RxtFloat,
    RxtInt,
    RxtList,
    RxtNone,
    RxtOptional,
    RxtSet,
    RxtStr,
    RxtTuple,
    RxtType,
)


class RustCodegenError(RuntimeError):
    pass


def generate_rust_module(module_ir: ModuleIR) -> str:
    names_by_qualname = {
        function.qualname: rust_identifier(native_function_name(function.qualname))
        for function in module_ir.functions
    }
    names_by_module_and_name = {
        (function.module_name, function.name): names_by_qualname[function.qualname]
        for function in module_ir.functions
    }
    return_types_by_qualname = {
        function.qualname: function.return_type for function in module_ir.functions
    }
    rendered = [
        (
            names_by_qualname[function.qualname],
            (
                _render_runtime_semantics_function(function)
                if function.native_runtime_semantics
                else _render_function(
                    function,
                    names_by_qualname,
                    names_by_module_and_name,
                    return_types_by_qualname,
                    mode="pyo3",
                )
            ),
        )
        for function in module_ir.functions
    ]
    return render_pyo3_module(rendered)


def generate_rust_crate_module(module_ir: ModuleIR) -> str:
    direct_functions = [function for function in module_ir.functions if not function.native_runtime_semantics]
    if not direct_functions:
        raise RustCodegenError("no direct Rust native functions are available for a Rust-importable crate")
    names_by_qualname = {
        function.qualname: rust_identifier(native_function_name(function.qualname))
        for function in direct_functions
    }
    names_by_module_and_name = {
        (function.module_name, function.name): names_by_qualname[function.qualname]
        for function in direct_functions
    }
    return_types_by_qualname = {
        function.qualname: function.return_type for function in direct_functions
    }
    rendered = [
        _render_function(
            function,
            names_by_qualname,
            names_by_module_and_name,
            return_types_by_qualname,
            mode="crate",
        )
        for function in direct_functions
    ]
    return _render_importable_crate_module(rendered)


def rust_identifier(value: str) -> str:
    identifier = re.sub(r"[^0-9a-zA-Z_]", "_", value)
    if not identifier:
        raise RustCodegenError("empty Rust identifier")
    if identifier[0].isdigit():
        identifier = f"_{identifier}"
    return identifier


def _render_runtime_semantics_function(function: FunctionIR) -> str:
    if function.runtime_fallback_module is None or not function.runtime_attr_path:
        raise RustCodegenError(f"missing runtime fallback metadata for {function.qualname}")
    rust_name = rust_identifier(native_function_name(function.qualname))
    attr_path = ", ".join(json.dumps(item) for item in function.runtime_attr_path)
    return "\n".join(
        [
            "#[pyfunction(signature = (*args, **kwargs))]",
            f"fn {rust_name}(",
            "    py: Python<'_>,",
            "    args: &Bound<'_, PyTuple>,",
            "    kwargs: Option<&Bound<'_, PyDict>>,",
            ") -> PyResult<PyObject> {",
            "    rextio_call_python_runtime(",
            "        py,",
            f"        {json.dumps(function.runtime_fallback_module)},",
            f"        &[{attr_path}],",
            "        args,",
            "        kwargs,",
            "    )",
            "}",
        ]
    )


def _render_importable_crate_module(function_sources: list[str]) -> str:
    lines = [
        "// Generated by Rextio. Do not edit manually.",
        "",
        "use base64::Engine;",
        "use sha2::Digest;",
        "use std::collections::HashMap;",
        "use std::collections::HashSet;",
        "",
        "#[derive(Debug, Clone, PartialEq, Eq)]",
        "pub struct RextioError {",
        "    message: String,",
        "}",
        "",
        "impl RextioError {",
        "    pub fn new(message: impl Into<String>) -> Self {",
        "        Self { message: message.into() }",
        "    }",
        "",
        "    pub fn message(&self) -> &str {",
        "        &self.message",
        "    }",
        "}",
        "",
        "impl std::fmt::Display for RextioError {",
        "    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {",
        "        write!(f, \"{}\", self.message)",
        "    }",
        "}",
        "",
        "impl std::error::Error for RextioError {}",
        "",
    ]
    for function_source in function_sources:
        lines.append(function_source)
        lines.append("")
    return "\n".join(lines)


class _FunctionRenderer:
    def __init__(
        self,
        function: FunctionIR,
        native_names_by_qualname: dict[str, str],
        native_names: dict[tuple[str, str], str],
        native_return_types: dict[str, RxtType],
        mode: str,
    ) -> None:
        self.function = function
        self.native_names_by_qualname = native_names_by_qualname
        self.native_names = native_names
        self.native_return_types = native_return_types
        self.mode = mode
        self.declared = {param.name for param in function.params}
        self.variable_types = {param.name: param.type for param in function.params}
        self.maybe_bound_types: dict[str, RxtType] = {}
        self.temp_index = 0

    def render(self) -> str:
        assigned_names = _assigned_names(self.function.body)
        params = ", ".join(
            f"{'mut ' if param.name in assigned_names else ''}{param.name}: {rust_type(param.type)}"
            for param in self.function.params
        )
        return_type = rust_type(self.function.return_type)
        rust_name = rust_identifier(native_function_name(self.function.qualname))
        if self.mode == "pyo3":
            lines = [
                "#[pyfunction]",
                f"fn {rust_name}({params}) -> PyResult<{return_type}> {{",
            ]
        else:
            lines = [
                f"pub fn {rust_name}({params}) -> Result<{return_type}, RextioError> {{",
            ]
        lines.extend(self.render_block(self.function.body, indent=1))
        if not _block_always_returns(self.function.body):
            lines.append(f"{_indent(1)}Ok({default_return(return_type)})")
        lines.append("}")
        return "\n".join(lines)

    def render_block(self, block: BlockIR, indent: int) -> list[str]:
        lines: list[str] = []
        for statement in block.statements:
            lines.extend(self.render_statement(statement, indent))
        return lines

    def render_statement(self, statement: StatementIR, indent: int) -> list[str]:
        prefix = _indent(indent)
        if isinstance(statement, AssignIR):
            lines = self.named_expr_prelude(statement.value, indent)
            target = statement.target.id
            target_type = statement.target_type or self.infer_expr_type(statement.value)
            value = strip_expr_if_safe(
                statement.value,
                self.render_expr_with_expected(statement.value, target_type),
            )
            if target_type is not None:
                self.variable_types[target] = target_type
            if target in self.maybe_bound_types:
                return [*lines, f"{prefix}{target} = Some({value});"]
            if target in self.declared:
                return [*lines, f"{prefix}{target} = {value};"]
            self.declared.add(target)
            if statement.target_type is not None and _needs_local_type_annotation(statement.value, statement.target_type):
                return [*lines, f"{prefix}let mut {target}: {rust_type(statement.target_type)} = {value};"]
            return [*lines, f"{prefix}let mut {target} = {value};"]
        if isinstance(statement, DictSetIR):
            lines = [
                *self.named_expr_prelude(statement.key, indent),
                *self.named_expr_prelude(statement.value, indent),
            ]
            self.declared.add(statement.target.id)
            return [
                *lines,
                f"{prefix}{statement.target.id}.insert("
                f"{strip_wrapping_parens(self.render_call_arg(statement.key))}, "
                f"{strip_wrapping_parens(self.render_call_arg(statement.value))});"
            ]
        if isinstance(statement, AppendIR):
            lines = self.named_expr_prelude(statement.value, indent)
            return [
                *lines,
                f"{prefix}{statement.target.id}.push("
                f"{strip_wrapping_parens(self.render_call_arg(statement.value))});"
            ]
        if isinstance(statement, EffectCallIR):
            lines = self.named_expr_prelude(statement.call, indent)
            return [*lines, f"{prefix}{self.render_call(statement.call)};"]
        if isinstance(statement, BreakIR):
            return [f"{prefix}break;"]
        if isinstance(statement, ContinueIR):
            return [f"{prefix}continue;"]
        if isinstance(statement, ReturnIR):
            if statement.value is None:
                return [f"{prefix}return Ok(());"]
            lines = self.named_expr_prelude(statement.value, indent)
            value = strip_expr_if_safe(
                statement.value,
                self.render_expr_with_expected(statement.value, self.function.return_type),
            )
            return [*lines, f"{prefix}return Ok({value});"]
        if isinstance(statement, IfIR):
            lines = self.named_expr_prelude(statement.condition, indent)
            condition = strip_wrapping_parens(self.render_expr(statement.condition))
            lines.append(f"{prefix}if {condition} {{")
            lines.extend(self.render_block(statement.body, indent + 1))
            if statement.orelse.statements:
                lines.append(f"{prefix}}} else {{")
                lines.extend(self.render_block(statement.orelse, indent + 1))
            lines.append(f"{prefix}}}")
            return lines
        if isinstance(statement, ForIR):
            lines = self.named_expr_prelude(statement.iterable, indent)
            iterable = self.render_iterable(statement.iterable)
            lines = [
                *lines,
                f"{prefix}for {self.render_loop_target(statement.target)} "
                f"in {iterable} {{"
            ]
            self.declared.update(target_names(statement.target))
            lines.extend(self.render_block(statement.body, indent + 1))
            lines.append(f"{prefix}}}")
            return lines
        if isinstance(statement, WhileIR):
            lines = self.named_expr_prelude(statement.condition, indent)
            condition = strip_wrapping_parens(self.render_expr(statement.condition))
            lines.append(f"{prefix}while {condition} {{")
            lines.extend(self.render_block(statement.body, indent + 1))
            lines.append(f"{prefix}}}")
            return lines
        raise RustCodegenError(f"unsupported statement IR: {type(statement).__name__}")

    def render_iterable(self, expr: ExprIR) -> str:
        if isinstance(expr, NameIR):
            return f"{expr.id}.iter().cloned()"
        if isinstance(expr, CallIR) and expr.function == "enumerate" and len(expr.args) == 1:
            return (
                f"{self.render_expr(expr.args[0])}.iter().cloned().enumerate()"
                ".map(|(i, value)| (i as i64, value))"
            )
        if isinstance(expr, CallIR) and expr.function == "zip" and len(expr.args) == 2:
            return (
                f"{self.render_expr(expr.args[0])}.iter().cloned()"
                f".zip({self.render_expr(expr.args[1])}.iter().cloned())"
            )
        if isinstance(expr, CallIR) and expr.function == "reversed" and len(expr.args) == 1:
            return f"{self.render_expr(expr.args[0])}.iter().rev().cloned()"
        if (
            isinstance(expr, CallIR)
            and expr.function == "range"
            and len(expr.args) == 1
            and isinstance(expr.args[0], CallIR)
            and expr.args[0].function == "len"
            and len(expr.args[0].args) == 1
        ):
            return f"0..({self.render_expr(expr.args[0].args[0])}.len() as i64)"
        if isinstance(expr, CallIR) and expr.function == "range" and len(expr.args) == 1:
            return f"0..{self.render_expr(expr.args[0])}"
        if isinstance(expr, CallIR) and expr.function == "range" and len(expr.args) == 2:
            return f"{self.render_expr(expr.args[0])}..{self.render_expr(expr.args[1])}"
        if isinstance(expr, CallIR) and expr.function == "range" and len(expr.args) == 3:
            return (
                f"({self.render_expr(expr.args[0])}..{self.render_expr(expr.args[1])})"
                f".step_by({strip_wrapping_parens(self.render_expr(expr.args[2]))} as usize)"
            )
        raise RustCodegenError("unsupported for-loop iterable")

    def render_loop_target(self, target: TargetIR) -> str:
        if isinstance(target, NameIR):
            return target.id
        if isinstance(target, TupleTargetIR):
            return f"({', '.join(item.id for item in target.items)})"
        raise RustCodegenError(f"unsupported loop target IR: {type(target).__name__}")

    def render_expr(self, expr: ExprIR) -> str:
        if isinstance(expr, LiteralIR):
            return render_literal(expr.value)
        if isinstance(expr, NameIR):
            if expr.id in self.maybe_bound_types:
                return self.render_maybe_bound_name(expr.id)
            return expr.id
        if isinstance(expr, ListIR):
            return f"vec![{', '.join(self.render_expr(item) for item in expr.items)}]"
        if isinstance(expr, ListComprehensionIR):
            return self.render_list_comprehension(expr)
        if isinstance(expr, TupleIR):
            if len(expr.items) == 1:
                return f"({self.render_expr(expr.items[0])},)"
            return f"({', '.join(self.render_expr(item) for item in expr.items)})"
        if isinstance(expr, DictIR):
            if not expr.items:
                return "HashMap::new()"
            lines = ["{"]
            lines.append("    let mut map = HashMap::new();")
            for key, value in expr.items:
                lines.append(
                    f"    map.insert({strip_wrapping_parens(self.render_call_arg(key))}, "
                    f"{strip_wrapping_parens(self.render_expr(value))});"
                )
            lines.append("    map")
            lines.append("}")
            return "\n".join(lines)
        if isinstance(expr, DictComprehensionIR):
            return self.render_dict_comprehension(expr)
        if isinstance(expr, SetIR):
            if not expr.items:
                return "HashSet::new()"
            if self.is_float_set_expr(expr):
                lines = ["{"]
                lines.append("    let mut set = Vec::new();")
                for item in expr.items:
                    temp = self.next_temp("__rextio_set_value")
                    value = strip_wrapping_parens(self.render_call_arg(item))
                    lines.append(f"    let {temp} = {value};")
                    lines.append(f"    if !set.contains(&{temp}) {{")
                    lines.append(f"        set.push({temp});")
                    lines.append("    }")
                lines.append("    set")
                lines.append("}")
                return "\n".join(lines)
            lines = ["{"]
            lines.append("    let mut set = HashSet::new();")
            for item in expr.items:
                lines.append(f"    set.insert({strip_wrapping_parens(self.render_call_arg(item))});")
            lines.append("    set")
            lines.append("}")
            return "\n".join(lines)
        if isinstance(expr, SetComprehensionIR):
            return self.render_set_comprehension(expr)
        if isinstance(expr, BinaryOpIR):
            op = {"and": "&&", "or": "||"}.get(expr.op, expr.op)
            return f"({self.render_expr(expr.left)} {op} {self.render_expr(expr.right)})"
        if isinstance(expr, UnaryOpIR):
            op = "!" if expr.op == "not" else expr.op
            return f"({op}{self.render_expr(expr.value)})"
        if isinstance(expr, CompareIR):
            return self.render_compare(expr)
        if isinstance(expr, CallIR):
            return self.render_call(expr)
        if isinstance(expr, IndexIR):
            return self.render_index_expr(expr)
        if isinstance(expr, NamedExprIR):
            return self.render_named_expr(expr)
        raise RustCodegenError(f"unsupported expression IR: {type(expr).__name__}")

    def render_list_comprehension(self, expr: ListComprehensionIR) -> str:
        target = self.next_temp("__rextio_list")
        lines = ["{"]
        lines.append(f"    let mut {target} = Vec::new();")
        lines.extend(
            self.render_comprehension_generators(
                expr.generators,
                1,
                lambda indent: [
                    f"{_indent(indent)}{target}.push("
                    f"{strip_wrapping_parens(self.render_call_arg(expr.item))});"
                ],
            )
        )
        lines.append(f"    {target}")
        lines.append("}")
        return "\n".join(lines)

    def render_dict_comprehension(self, expr: DictComprehensionIR) -> str:
        target = self.next_temp("__rextio_dict")
        lines = ["{"]
        lines.append(f"    let mut {target} = HashMap::new();")
        lines.extend(
            self.render_comprehension_generators(
                expr.generators,
                1,
                lambda indent: [
                    f"{_indent(indent)}{target}.insert("
                    f"{strip_wrapping_parens(self.render_call_arg(expr.key))}, "
                    f"{strip_wrapping_parens(self.render_call_arg(expr.value))});"
                ],
            )
        )
        lines.append(f"    {target}")
        lines.append("}")
        return "\n".join(lines)

    def render_set_comprehension(self, expr: SetComprehensionIR) -> str:
        target = self.next_temp("__rextio_set")
        lines = ["{"]
        is_float_set = self.is_float_set_expr(expr)
        collection_type = "Vec::new()" if is_float_set else "HashSet::new()"
        lines.append(f"    let mut {target} = {collection_type};")
        lines.extend(
            self.render_comprehension_generators(
                expr.generators,
                1,
                (
                    lambda indent: self.render_float_set_insert(target, expr.item, indent)
                    if is_float_set
                    else [
                        f"{_indent(indent)}{target}.insert("
                        f"{strip_wrapping_parens(self.render_call_arg(expr.item))});"
                    ]
                ),
            )
        )
        lines.append(f"    {target}")
        lines.append("}")
        return "\n".join(lines)

    def render_float_set_insert(self, target: str, item: ExprIR, indent: int) -> list[str]:
        temp = self.next_temp("__rextio_set_value")
        value = strip_wrapping_parens(self.render_call_arg(item))
        prefix = _indent(indent)
        return [
            f"{prefix}let {temp} = {value};",
            f"{prefix}if !{target}.contains(&{temp}) {{",
            f"{prefix}    {target}.push({temp});",
            f"{prefix}}}",
        ]

    def is_float_set_expr(self, expr: ExprIR) -> bool:
        expr_type = self.infer_expr_type(expr)
        return isinstance(expr_type, RxtSet) and isinstance(expr_type.item_type, RxtFloat)

    def render_comprehension_generators(
        self,
        generators: list[ComprehensionGeneratorIR],
        index: int,
        render_leaf: callable,
    ) -> list[str]:
        if index > len(generators):
            return render_leaf(index)
        generator = generators[index - 1]
        prefix = _indent(index)
        iterable = self.render_iterable(generator.iterable)
        lines = [
            f"{prefix}for {self.render_loop_target(generator.target)} in {iterable} {{"
        ]
        saved_types = dict(self.variable_types)
        self.bind_target_types(generator.target, self.iterable_target_types(generator.iterable))
        if generator.conditions:
            condition = " && ".join(
                strip_wrapping_parens(self.render_expr(condition))
                for condition in generator.conditions
            )
            lines.append(f"{_indent(index + 1)}if {condition} {{")
            lines.extend(self.render_comprehension_generators(generators, index + 1, render_leaf))
            lines.append(f"{_indent(index + 1)}}}")
        else:
            lines.extend(self.render_comprehension_generators(generators, index + 1, render_leaf))
        self.variable_types = saved_types
        lines.append(f"{prefix}}}")
        return lines

    def iterable_target_types(self, expr: ExprIR) -> list[RxtType]:
        if isinstance(expr, CallIR) and expr.function == "enumerate" and len(expr.args) == 1:
            item_type = self.iterable_item_type(expr.args[0])
            return [RxtInt(), item_type] if item_type is not None else []
        if isinstance(expr, CallIR) and expr.function == "zip" and len(expr.args) == 2:
            item_types = [self.iterable_item_type(arg) for arg in expr.args]
            return [item for item in item_types if item is not None]
        if isinstance(expr, CallIR) and expr.function == "range":
            return [RxtInt()]
        item_type = self.iterable_item_type(expr)
        return [item_type] if item_type is not None else []

    def iterable_item_type(self, expr: ExprIR) -> RxtType | None:
        value_type = self.infer_expr_type(expr)
        if isinstance(value_type, (RxtList, RxtSet)):
            return value_type.item_type
        return None

    def bind_target_types(self, target: TargetIR, item_types: list[RxtType]) -> None:
        if isinstance(target, NameIR) and len(item_types) == 1:
            self.variable_types[target.id] = item_types[0]
            return
        if isinstance(target, TupleTargetIR) and len(target.items) == len(item_types):
            for item, item_type in zip(target.items, item_types, strict=True):
                self.variable_types[item.id] = item_type

    def render_named_expr(self, expr: NamedExprIR) -> str:
        target = expr.target.id
        value = strip_expr_if_safe(
            expr.value,
            self.render_call_arg(expr.value),
        )
        if target in self.maybe_bound_types:
            return (
                f"{{ {target} = Some({value}); "
                f"{self.render_maybe_bound_name(target)} }}"
            )
        return f"{{ {target} = {value}; {target}.clone() }}"

    def render_maybe_bound_name(self, name: str) -> str:
        message = json.dumps(f"local variable '{name}' referenced before assignment")
        return (
            f"{name}.clone().ok_or_else(|| "
            f"{self.error_new(message, kind='unbound')})?"
        )

    def error_new(self, message: str, *, kind: str = "value") -> str:
        if self.mode == "pyo3":
            exception = {
                "key": "PyKeyError",
                "runtime": "PyRuntimeError",
                "unbound": "PyUnboundLocalError",
                "value": "PyValueError",
            }.get(kind, "PyValueError")
            return f"pyo3::exceptions::{exception}::new_err({message})"
        return f"RextioError::new({message})"

    def error_from_to_string(self, value: str, *, kind: str = "value") -> str:
        return self.error_new(f"{value}.to_string()", kind=kind)

    def map_err_to_error(self, *, kind: str = "value") -> str:
        if self.mode == "pyo3":
            exception = {
                "runtime": "PyRuntimeError",
                "value": "PyValueError",
            }.get(kind, "PyValueError")
            return f".map_err(|err| pyo3::exceptions::{exception}::new_err(err.to_string()))?"
        return ".map_err(|err| RextioError::new(err.to_string()))?"

    def next_temp(self, prefix: str) -> str:
        self.temp_index += 1
        return f"{prefix}_{self.temp_index}"

    def named_expr_prelude(self, expr: ExprIR, indent: int) -> list[str]:
        bindings = self.collect_named_expr_bindings(expr)
        lines: list[str] = []
        for name, binding_type in bindings.items():
            if name in self.declared:
                self.variable_types[name] = self.variable_types.get(name, binding_type)
                continue
            self.declared.add(name)
            self.variable_types[name] = binding_type
            self.maybe_bound_types[name] = binding_type
            lines.append(
                f"{_indent(indent)}let mut {name}: Option<{rust_type(binding_type)}> = None;"
            )
        return lines

    def collect_named_expr_bindings(self, expr: ExprIR) -> dict[str, RxtType]:
        bindings: dict[str, RxtType] = {}
        scope = dict(self.variable_types)
        self.collect_named_expr_bindings_in_expr(expr, scope, scope, bindings)
        return bindings

    def collect_named_expr_bindings_in_expr(
        self,
        expr: ExprIR,
        scope: dict[str, RxtType],
        binding_scope: dict[str, RxtType],
        bindings: dict[str, RxtType],
    ) -> None:
        if isinstance(expr, NamedExprIR):
            self.collect_named_expr_bindings_in_expr(expr.value, scope, binding_scope, bindings)
            value_type = self.infer_expr_type_in_scope(expr.value, scope)
            if value_type is None:
                raise RustCodegenError("cannot infer assignment expression type")
            bindings.setdefault(expr.target.id, value_type)
            scope[expr.target.id] = value_type
            binding_scope[expr.target.id] = value_type
            return
        if isinstance(expr, BinaryOpIR):
            self.collect_named_expr_bindings_in_expr(expr.left, scope, binding_scope, bindings)
            self.collect_named_expr_bindings_in_expr(expr.right, scope, binding_scope, bindings)
            return
        if isinstance(expr, UnaryOpIR):
            self.collect_named_expr_bindings_in_expr(expr.value, scope, binding_scope, bindings)
            return
        if isinstance(expr, CompareIR):
            self.collect_named_expr_bindings_in_expr(expr.left, scope, binding_scope, bindings)
            for comparator in expr.comparators:
                self.collect_named_expr_bindings_in_expr(comparator, scope, binding_scope, bindings)
            return
        if isinstance(expr, CallIR):
            for arg in expr.args:
                self.collect_named_expr_bindings_in_expr(arg, scope, binding_scope, bindings)
            return
        if isinstance(expr, IndexIR):
            self.collect_named_expr_bindings_in_expr(expr.value, scope, binding_scope, bindings)
            self.collect_named_expr_bindings_in_expr(expr.index, scope, binding_scope, bindings)
            return
        if isinstance(expr, ListIR):
            for item in expr.items:
                self.collect_named_expr_bindings_in_expr(item, scope, binding_scope, bindings)
            return
        if isinstance(expr, TupleIR):
            for item in expr.items:
                self.collect_named_expr_bindings_in_expr(item, scope, binding_scope, bindings)
            return
        if isinstance(expr, DictIR):
            for key, value in expr.items:
                self.collect_named_expr_bindings_in_expr(key, scope, binding_scope, bindings)
                self.collect_named_expr_bindings_in_expr(value, scope, binding_scope, bindings)
            return
        if isinstance(expr, SetIR):
            for item in expr.items:
                self.collect_named_expr_bindings_in_expr(item, scope, binding_scope, bindings)
            return
        if isinstance(expr, ListComprehensionIR):
            self.collect_named_expr_bindings_in_comprehension(
                expr.generators,
                [expr.item],
                scope,
                binding_scope,
                bindings,
            )
            return
        if isinstance(expr, DictComprehensionIR):
            self.collect_named_expr_bindings_in_comprehension(
                expr.generators,
                [expr.key, expr.value],
                scope,
                binding_scope,
                bindings,
            )
            return
        if isinstance(expr, SetComprehensionIR):
            self.collect_named_expr_bindings_in_comprehension(
                expr.generators,
                [expr.item],
                scope,
                binding_scope,
                bindings,
            )

    def collect_named_expr_bindings_in_comprehension(
        self,
        generators: list[ComprehensionGeneratorIR],
        result_exprs: list[ExprIR],
        scope: dict[str, RxtType],
        binding_scope: dict[str, RxtType],
        bindings: dict[str, RxtType],
    ) -> None:
        comp_scope = dict(scope)
        for generator in generators:
            self.collect_named_expr_bindings_in_expr(
                generator.iterable,
                comp_scope,
                binding_scope,
                bindings,
            )
            item_types = self.iterable_target_types_in_scope(generator.iterable, comp_scope)
            self.bind_target_types_to_scope(generator.target, item_types, comp_scope)
            for condition in generator.conditions:
                self.collect_named_expr_bindings_in_expr(
                    condition,
                    comp_scope,
                    binding_scope,
                    bindings,
                )
        for result_expr in result_exprs:
            self.collect_named_expr_bindings_in_expr(
                result_expr,
                comp_scope,
                binding_scope,
                bindings,
            )

    def infer_expr_type_in_scope(
        self,
        expr: ExprIR,
        scope: dict[str, RxtType],
    ) -> RxtType | None:
        saved_types = self.variable_types
        self.variable_types = scope
        try:
            return self.infer_expr_type(expr)
        finally:
            self.variable_types = saved_types

    def iterable_target_types_in_scope(
        self,
        expr: ExprIR,
        scope: dict[str, RxtType],
    ) -> list[RxtType]:
        saved_types = self.variable_types
        self.variable_types = scope
        try:
            return self.iterable_target_types(expr)
        finally:
            self.variable_types = saved_types

    def bind_target_types_to_scope(
        self,
        target: TargetIR,
        item_types: list[RxtType],
        scope: dict[str, RxtType],
    ) -> None:
        if isinstance(target, NameIR) and len(item_types) == 1:
            scope[target.id] = item_types[0]
            return
        if isinstance(target, TupleTargetIR) and len(target.items) == len(item_types):
            for item, item_type in zip(target.items, item_types, strict=True):
                scope[item.id] = item_type

    def render_index(self, expr: ExprIR) -> str:
        rendered = strip_wrapping_parens(self.render_expr(expr))
        return f"{rendered} as usize"

    def render_index_expr(self, expr: IndexIR) -> str:
        value_type = self.infer_expr_type(expr.value)
        if isinstance(value_type, RxtTuple):
            index = literal_int(expr.index)
            if index is None or index < 0 or index >= len(value_type.item_types):
                raise RustCodegenError("tuple index must be an in-range literal")
            return f"{self.render_expr(expr.value)}.{index}.clone()"
        if isinstance(value_type, RxtDict):
            key = strip_wrapping_parens(self.render_expr(expr.index))
            if self.mode == "pyo3":
                error = f"pyo3::exceptions::PyKeyError::new_err({key}.clone())"
            else:
                error = f"RextioError::new(format!(\"key not found: {{:?}}\", {key}))"
            return f"{self.render_expr(expr.value)}.get(&{key}).cloned().ok_or_else(|| {error})?"
        return f"{self.render_expr(expr.value)}[{self.render_index(expr.index)}].clone()"

    def render_compare(self, expr: CompareIR) -> str:
        if len(expr.ops) != len(expr.comparators):
            raise RustCodegenError("invalid comparison IR")
        left = expr.left
        parts: list[str] = []
        for op, comparator in zip(expr.ops, expr.comparators, strict=True):
            parts.append(f"({self.render_expr(left)} {op} {self.render_expr(comparator)})")
            left = comparator
        return " && ".join(parts)

    def render_call(self, expr: CallIR) -> str:
        if expr.function == "len" and len(expr.args) == 1:
            return f"({self.render_expr(expr.args[0])}.len() as i64)"
        if expr.function == "abs" and len(expr.args) == 1:
            return f"({self.render_expr(expr.args[0])}).abs()"
        if expr.function == "min" and len(expr.args) == 2:
            return f"({self.render_expr(expr.args[0])}).min({self.render_expr(expr.args[1])})"
        if expr.function == "max" and len(expr.args) == 2:
            return f"({self.render_expr(expr.args[0])}).max({self.render_expr(expr.args[1])})"
        if expr.function == "sum" and len(expr.args) == 1:
            return f"({self.render_expr(expr.args[0])}).iter().cloned().sum()"
        if expr.function == "all" and len(expr.args) == 1:
            return f"({self.render_expr(expr.args[0])}).iter().copied().all(|value| value)"
        if expr.function == "any" and len(expr.args) == 1:
            return f"({self.render_expr(expr.args[0])}).iter().copied().any(|value| value)"
        if expr.function == "sorted" and len(expr.args) == 1:
            return self.render_sorted(expr.args[0])
        if expr.function == "reversed" and len(expr.args) == 1:
            return self.render_reversed(expr.args[0])
        if expr.function == "math.pi" and not expr.args:
            return "std::f64::consts::PI"
        if expr.function == "math.e" and not expr.args:
            return "std::f64::consts::E"
        if expr.function in {
            "math.acos",
            "math.asin",
            "math.atan",
            "math.cos",
            "math.exp",
            "math.log10",
            "math.log2",
            "math.sin",
            "math.sqrt",
            "math.tan",
        } and len(expr.args) == 1:
            method = expr.function.rsplit(".", 1)[1]
            if method == "log":
                method = "ln"
            return f"({self.render_expr(expr.args[0])}).{method}()"
        if expr.function == "math.log":
            if len(expr.args) == 1:
                return f"({self.render_expr(expr.args[0])}).ln()"
            if len(expr.args) == 2:
                return f"({self.render_expr(expr.args[0])}).log({self.render_expr(expr.args[1])})"
        if expr.function == "math.atan2" and len(expr.args) == 2:
            return f"({self.render_expr(expr.args[0])}).atan2({self.render_expr(expr.args[1])})"
        if expr.function in {"math.ceil", "math.floor", "math.trunc"} and len(expr.args) == 1:
            method = expr.function.rsplit(".", 1)[1]
            return f"(({self.render_expr(expr.args[0])}).{method}() as i64)"
        if expr.function in {"math.isfinite", "math.isinf", "math.isnan"} and len(expr.args) == 1:
            method = {
                "math.isfinite": "is_finite",
                "math.isinf": "is_infinite",
                "math.isnan": "is_nan",
            }[expr.function]
            return f"({self.render_expr(expr.args[0])}).{method}()"
        if expr.function.startswith("str.") or expr.function.startswith("bytes."):
            return self.render_string_or_bytes_method(expr)
        if expr.function.startswith("list."):
            return self.render_list_method(expr)
        if expr.function in {"statistics.mean", "statistics.fmean"} and len(expr.args) == 1:
            return self.render_statistics_mean(expr.args[0])
        if expr.function == "print":
            return self.render_format_macro("println!", expr.args, allow_empty=True)
        if expr.function in {"logging.debug", "logging.info", "logging.warning", "logging.error"}:
            macro = {
                "logging.debug": "log::debug!",
                "logging.info": "log::info!",
                "logging.warning": "log::warn!",
                "logging.error": "log::error!",
            }[expr.function]
            return self.render_logging_macro(macro, expr.args)
        if expr.function == "datetime.datetime.now.isoformat" and not expr.args:
            return "chrono::Local::now().to_rfc3339()"
        if expr.function == "datetime.datetime.utcnow.isoformat" and not expr.args:
            return "chrono::Utc::now().to_rfc3339()"
        if expr.function == "datetime.datetime.now.timestamp" and not expr.args:
            return self.render_chrono_timestamp("chrono::Local::now()")
        if expr.function == "datetime.datetime.utcnow.timestamp" and not expr.args:
            return self.render_chrono_timestamp("chrono::Utc::now()")
        if expr.function == "time.time" and not expr.args:
            return (
                "std::time::SystemTime::now()"
                ".duration_since(std::time::UNIX_EPOCH)"
                f"{self.map_err_to_error(kind='runtime')}"
                ".as_secs_f64()"
            )
        if expr.function == "hashlib.sha256.hexdigest" and len(expr.args) == 1:
            return f"format!(\"{{:x}}\", sha2::Sha256::digest(&{strip_wrapping_parens(self.render_call_arg(expr.args[0]))}))"
        if expr.function == "base64.b64encode" and len(expr.args) == 1:
            return (
                "base64::engine::general_purpose::STANDARD"
                f".encode({strip_wrapping_parens(self.render_call_arg(expr.args[0]))}).into_bytes()"
            )
        if expr.function == "base64.b64decode" and len(expr.args) == 1:
            source = strip_wrapping_parens(self.render_call_arg(expr.args[0]))
            if isinstance(self.infer_expr_type(expr.args[0]), RxtStr):
                source = f"{source}.as_bytes()"
            return (
                "base64::engine::general_purpose::STANDARD"
                f".decode({source})"
                f"{self.map_err_to_error()}"
            )
        if expr.function == "json.dumps" and len(expr.args) == 1:
            return (
                f"serde_json::to_string(&{strip_wrapping_parens(self.render_call_arg(expr.args[0]))})"
                f"{self.map_err_to_error()}"
            )
        rust_name = self.native_names_by_qualname.get(expr.function)
        if rust_name is None:
            rust_name = self.native_names.get((self.function.module_name, expr.function))
        if rust_name is not None:
            args = ", ".join(self.render_call_arg(arg) for arg in expr.args)
            return f"{rust_name}({args})?"
        raise RustCodegenError(f"unsupported call during Rust codegen: {expr.function}")

    def render_sorted(self, expr: ExprIR) -> str:
        source = strip_wrapping_parens(self.render_call_arg(expr))
        expr_type = self.infer_expr_type(expr)
        if isinstance(expr_type, RxtList) and isinstance(expr_type.item_type, RxtFloat):
            return "\n".join(
                [
                    "{",
                    f"    let mut values = {source};",
                    "    if values.iter().any(|value| value.is_nan()) {",
                    f"        return Err({self.error_new(json.dumps('sorted() does not support NaN float values in native functions'))});",
                    "    }",
                    "    values.sort_by(|left, right| left.partial_cmp(right).expect(\"NaN was checked before sorting\"));",
                    "    values",
                    "}",
                ]
            )
        return "\n".join(
            [
                "{",
                f"    let mut values = {source};",
                "    values.sort();",
                "    values",
                "}",
            ]
        )

    def render_reversed(self, expr: ExprIR) -> str:
        source = strip_wrapping_parens(self.render_call_arg(expr))
        return "\n".join(
            [
                "{",
                f"    let mut values = {source};",
                "    values.reverse();",
                "    values",
                "}",
            ]
        )

    def render_string_or_bytes_method(self, expr: CallIR) -> str:
        receiver = strip_wrapping_parens(self.render_call_arg(expr.args[0]))
        if expr.function == "str.lower" and len(expr.args) == 1:
            return f"{receiver}.to_lowercase()"
        if expr.function == "str.upper" and len(expr.args) == 1:
            return f"{receiver}.to_uppercase()"
        if expr.function == "str.strip" and len(expr.args) == 1:
            return f"{receiver}.trim().to_string()"
        if expr.function == "str.encode" and len(expr.args) == 1:
            return f"{receiver}.as_bytes().to_vec()"
        if expr.function == "bytes.decode" and len(expr.args) == 1:
            return (
                f"String::from_utf8({receiver})"
                f"{self.map_err_to_error()}"
            )
        if expr.function in {"str.startswith", "str.endswith"} and len(expr.args) == 2:
            method = "starts_with" if expr.function == "str.startswith" else "ends_with"
            value = strip_wrapping_parens(self.render_call_arg(expr.args[1]))
            return f"{receiver}.{method}(&{value})"
        if expr.function == "str.replace" and len(expr.args) == 3:
            old = strip_wrapping_parens(self.render_call_arg(expr.args[1]))
            new = strip_wrapping_parens(self.render_call_arg(expr.args[2]))
            return f"{receiver}.replace(&{old}, &{new})"
        raise RustCodegenError(f"unsupported string/bytes method during Rust codegen: {expr.function}")

    def render_list_method(self, expr: CallIR) -> str:
        receiver = strip_wrapping_parens(self.render_call_arg(expr.args[0]))
        if expr.function == "list.copy" and len(expr.args) == 1:
            return receiver
        if expr.function == "list.count" and len(expr.args) == 2:
            needle = strip_wrapping_parens(self.render_call_arg(expr.args[1]))
            return f"({receiver}).iter().filter(|item| *item == &{needle}).count() as i64"
        if expr.function == "list.index" and len(expr.args) == 2:
            needle = strip_wrapping_parens(self.render_call_arg(expr.args[1]))
            return (
                f"({receiver}).iter().position(|item| item == &{needle})"
                ".map(|index| index as i64)"
                f".ok_or_else(|| {self.error_new(json.dumps('list.index(x): x not in list'))})?"
            )
        raise RustCodegenError(f"unsupported list method during Rust codegen: {expr.function}")

    def render_statistics_mean(self, expr: ExprIR) -> str:
        source = strip_wrapping_parens(self.render_call_arg(expr))
        item_type = None
        expr_type = self.infer_expr_type(expr)
        if isinstance(expr_type, RxtList):
            item_type = expr_type.item_type
        value_expr = "value" if isinstance(item_type, RxtFloat) else "value as f64"
        return "\n".join(
            [
                "{",
                f"    let values = {source};",
                "    if values.is_empty() {",
                f"        return Err({self.error_new(json.dumps('statistics.mean requires at least one data point'))});",
                "    }",
                f"    values.iter().copied().map(|value| {value_expr}).sum::<f64>() / values.len() as f64",
                "}",
            ]
        )

    def render_chrono_timestamp(self, now_expr: str) -> str:
        return "\n".join(
            [
                "{",
                f"    let value = {now_expr};",
                "    value.timestamp() as f64 + value.timestamp_subsec_nanos() as f64 / 1_000_000_000.0",
                "}",
            ]
        )

    def render_call_arg(self, expr: ExprIR) -> str:
        if isinstance(expr, NameIR):
            if expr.id in self.maybe_bound_types:
                return self.render_expr(expr)
            return f"{expr.id}.clone()"
        return self.render_expr(expr)

    def render_expr_with_expected(self, expr: ExprIR, expected_type: RxtType | None) -> str:
        if (
            isinstance(expr, CallIR)
            and expr.function == "json.loads"
            and len(expr.args) == 1
            and expected_type is not None
        ):
            source = strip_wrapping_parens(self.render_call_arg(expr.args[0]))
            return (
                f"serde_json::from_str::<{rust_type(expected_type)}>(&{source})"
                f"{self.map_err_to_error()}"
            )
        if isinstance(expected_type, RxtOptional):
            if isinstance(expr, LiteralIR) and expr.value is None:
                return "None"
            actual_type = self.infer_expr_type(expr)
            rendered = strip_expr_if_safe(expr, self.render_expr(expr))
            if same_type(actual_type, expected_type):
                return rendered
            if same_type(actual_type, expected_type.item_type):
                return f"Some({strip_expr_if_safe(expr, rendered)})"
            return rendered
        if isinstance(expected_type, RxtNone) and isinstance(expr, LiteralIR) and expr.value is None:
            return "()"
        return self.render_expr(expr)

    def infer_expr_type(self, expr: ExprIR) -> RxtType | None:
        if isinstance(expr, LiteralIR):
            if isinstance(expr.value, bool):
                return RxtBool()
            if isinstance(expr.value, int):
                return RxtInt()
            if isinstance(expr.value, float):
                return RxtFloat()
            if isinstance(expr.value, str):
                return RxtStr()
            if isinstance(expr.value, bytes):
                return RxtBytes()
            if expr.value is None:
                return RxtNone()
            return None
        if isinstance(expr, NameIR):
            return self.variable_types.get(expr.id)
        if isinstance(expr, ListIR):
            if not expr.items:
                return None
            item_type = self.infer_expr_type(expr.items[0])
            if item_type is None:
                return None
            return RxtList(item_type)
        if isinstance(expr, ListComprehensionIR):
            saved_types = dict(self.variable_types)
            self.bind_comprehension_generator_types(expr.generators)
            item_type = self.infer_expr_type(expr.item)
            self.variable_types = saved_types
            if item_type is None:
                return None
            return RxtList(item_type)
        if isinstance(expr, TupleIR):
            item_types: list[RxtType] = []
            for item in expr.items:
                item_type = self.infer_expr_type(item)
                if item_type is None:
                    return None
                item_types.append(item_type)
            return RxtTuple(tuple(item_types))
        if isinstance(expr, DictIR):
            if not expr.items:
                return None
            first_key, first_value = expr.items[0]
            key_type = self.infer_expr_type(first_key)
            value_type = self.infer_expr_type(first_value)
            if key_type is None or value_type is None:
                return None
            return RxtDict(key_type, value_type)
        if isinstance(expr, DictComprehensionIR):
            saved_types = dict(self.variable_types)
            self.bind_comprehension_generator_types(expr.generators)
            key_type = self.infer_expr_type(expr.key)
            value_type = self.infer_expr_type(expr.value)
            self.variable_types = saved_types
            if key_type is None or value_type is None:
                return None
            return RxtDict(key_type, value_type)
        if isinstance(expr, SetIR):
            if not expr.items:
                return None
            item_type = self.infer_expr_type(expr.items[0])
            if item_type is None:
                return None
            return RxtSet(item_type)
        if isinstance(expr, SetComprehensionIR):
            saved_types = dict(self.variable_types)
            self.bind_comprehension_generator_types(expr.generators)
            item_type = self.infer_expr_type(expr.item)
            self.variable_types = saved_types
            if item_type is None:
                return None
            return RxtSet(item_type)
        if isinstance(expr, BinaryOpIR):
            return self.infer_expr_type(expr.left)
        if isinstance(expr, UnaryOpIR):
            if expr.op == "not":
                return RxtBool()
            return self.infer_expr_type(expr.value)
        if isinstance(expr, CompareIR):
            return RxtBool()
        if isinstance(expr, IndexIR):
            value_type = self.infer_expr_type(expr.value)
            if isinstance(value_type, RxtList):
                return value_type.item_type
            if isinstance(value_type, RxtTuple):
                index = literal_int(expr.index)
                if index is not None and 0 <= index < len(value_type.item_types):
                    return value_type.item_types[index]
            if isinstance(value_type, RxtDict):
                return value_type.value_type
        if isinstance(expr, CallIR):
            return self.call_return_type(expr)
        if isinstance(expr, NamedExprIR):
            value_type = self.infer_expr_type(expr.value)
            if value_type is not None:
                self.variable_types[expr.target.id] = value_type
            return value_type
        return None

    def bind_comprehension_generator_types(
        self,
        generators: list[ComprehensionGeneratorIR],
    ) -> None:
        for generator in generators:
            self.bind_target_types(generator.target, self.iterable_target_types(generator.iterable))
            for condition in generator.conditions:
                self.infer_expr_type(condition)

    def call_return_type(self, expr: CallIR) -> RxtType | None:
        if expr.function == "len":
            return RxtInt()
        if expr.function in {"all", "any"}:
            return RxtBool()
        if expr.function in {"sorted", "reversed"} and expr.args:
            return self.infer_expr_type(expr.args[0])
        if expr.function in {"abs", "min", "max"} and expr.args:
            return self.infer_expr_type(expr.args[0])
        if expr.function == "sum" and expr.args:
            arg_type = self.infer_expr_type(expr.args[0])
            if isinstance(arg_type, RxtList):
                return arg_type.item_type
            return None
        if expr.function in {
            "math.acos",
            "math.asin",
            "math.atan",
            "math.atan2",
            "math.cos",
            "math.exp",
            "math.log",
            "math.log10",
            "math.log2",
            "math.sin",
            "math.sqrt",
            "math.tan",
            "math.e",
            "math.pi",
        }:
            return RxtFloat()
        if expr.function in {"math.ceil", "math.floor", "math.trunc"}:
            return RxtInt()
        if expr.function in {"math.isfinite", "math.isinf", "math.isnan"}:
            return RxtBool()
        if expr.function in {"str.lower", "str.upper", "str.strip", "str.replace"}:
            return RxtStr()
        if expr.function in {"str.startswith", "str.endswith"}:
            return RxtBool()
        if expr.function == "str.encode":
            return RxtBytes()
        if expr.function == "bytes.decode":
            return RxtStr()
        if expr.function in {"list.copy"} and expr.args:
            return self.infer_expr_type(expr.args[0])
        if expr.function in {"list.count", "list.index"}:
            return RxtInt()
        if expr.function in {"statistics.mean", "statistics.fmean"}:
            return RxtFloat()
        if expr.function == "print" or expr.function.startswith("logging."):
            return RxtNone()
        if expr.function in {
            "datetime.datetime.now.isoformat",
            "datetime.datetime.utcnow.isoformat",
        }:
            return RxtStr()
        if expr.function in {
            "datetime.datetime.now.timestamp",
            "datetime.datetime.utcnow.timestamp",
            "time.time",
        }:
            return RxtFloat()
        if expr.function == "hashlib.sha256.hexdigest":
            return RxtStr()
        if expr.function in {"base64.b64encode", "base64.b64decode"}:
            return RxtBytes()
        if expr.function == "json.dumps":
            return RxtStr()
        return self.native_return_types.get(expr.function)

    def render_format_macro(
        self,
        macro: str,
        args: list[ExprIR],
        *,
        allow_empty: bool,
    ) -> str:
        if not args:
            if allow_empty:
                return f"{macro}()"
            return f"{macro}(\"\")"
        placeholders = " ".join(self.format_placeholder(arg) for arg in args)
        rendered_args = ", ".join(
            strip_wrapping_parens(self.render_call_arg(arg))
            for arg in args
        )
        return f"{macro}({json.dumps(placeholders)}, {rendered_args})"

    def render_logging_macro(self, macro: str, args: list[ExprIR]) -> str:
        if (
            len(args) > 1
            and isinstance(args[0], LiteralIR)
            and isinstance(args[0].value, str)
        ):
            converted = python_logging_format_to_rust(args[0].value)
            if converted is not None:
                format_string, placeholder_count = converted
                if placeholder_count == len(args) - 1:
                    rendered_args = ", ".join(
                        strip_wrapping_parens(self.render_call_arg(arg))
                        for arg in args[1:]
                    )
                    return f"{macro}({json.dumps(format_string)}, {rendered_args})"
        return self.render_format_macro(macro, args, allow_empty=False)

    def format_placeholder(self, expr: ExprIR) -> str:
        expr_type = self.infer_expr_type(expr)
        if isinstance(expr_type, (RxtInt, RxtFloat, RxtBool, RxtStr)):
            return "{}"
        return "{:?}"


def _render_function(
    function: FunctionIR,
    native_names_by_qualname: dict[str, str],
    native_names: dict[tuple[str, str], str],
    native_return_types: dict[str, RxtType],
    mode: str,
) -> str:
    return _FunctionRenderer(
        function,
        native_names_by_qualname,
        native_names,
        native_return_types,
        mode,
    ).render()


def render_literal(value: object) -> str:
    if value is None:
        return "None"
    if isinstance(value, bool):
        return "true" if value else "false"
    if isinstance(value, str):
        return f"String::from({json.dumps(value)})"
    if isinstance(value, bytes):
        return f"vec![{', '.join(str(item) for item in value)}]"
    return repr(value)


def python_logging_format_to_rust(value: str) -> tuple[str, int] | None:
    output: list[str] = []
    placeholders = 0
    index = 0
    while index < len(value):
        char = value[index]
        if char == "%":
            if index + 1 >= len(value):
                return None
            specifier = value[index + 1]
            if specifier == "%":
                output.append("%")
                index += 2
                continue
            if specifier in {"s", "d", "i", "f"}:
                output.append("{}")
                placeholders += 1
                index += 2
                continue
            if specifier == "r":
                output.append("{:?}")
                placeholders += 1
                index += 2
                continue
            return None
        if char == "{":
            output.append("{{")
        elif char == "}":
            output.append("}}")
        else:
            output.append(char)
        index += 1
    return "".join(output), placeholders


def strip_wrapping_parens(value: str) -> str:
    if not value.startswith("(") or not value.endswith(")"):
        return value
    depth = 0
    for index, char in enumerate(value):
        if char == "(":
            depth += 1
        elif char == ")":
            depth -= 1
            if depth == 0 and index != len(value) - 1:
                return value
    if depth == 0:
        return value[1:-1]
    return value


def strip_expr_if_safe(expr: ExprIR, value: str) -> str:
    if isinstance(expr, TupleIR):
        return value
    return strip_wrapping_parens(value)


def default_return(return_type: str) -> str:
    if return_type == "()":
        return "()"
    if return_type == "bool":
        return "false"
    if return_type == "String":
        return "String::new()"
    if return_type.startswith("Vec<"):
        return "Vec::new()"
    if return_type.startswith("HashMap<"):
        return "HashMap::new()"
    if return_type.startswith("HashSet<"):
        return "HashSet::new()"
    if return_type.startswith("Option<"):
        return "None"
    if return_type == "i64":
        return "0"
    if return_type == "f64":
        return "0.0"
    return "Default::default()"


def _block_always_returns(block: BlockIR) -> bool:
    return bool(block.statements) and isinstance(block.statements[-1], ReturnIR)


def _indent(level: int) -> str:
    return "    " * level


def _assigned_names(block: BlockIR) -> set[str]:
    names: set[str] = set()
    for statement in block.statements:
        if isinstance(statement, AssignIR):
            names.add(statement.target.id)
            names.update(_expr_assigned_names(statement.value))
        elif isinstance(statement, DictSetIR):
            names.add(statement.target.id)
            names.update(_expr_assigned_names(statement.key))
            names.update(_expr_assigned_names(statement.value))
        elif isinstance(statement, AppendIR):
            names.add(statement.target.id)
            names.update(_expr_assigned_names(statement.value))
        elif isinstance(statement, EffectCallIR):
            names.update(_expr_assigned_names(statement.call))
        elif isinstance(statement, ReturnIR):
            if statement.value is not None:
                names.update(_expr_assigned_names(statement.value))
        elif isinstance(statement, IfIR):
            names.update(_expr_assigned_names(statement.condition))
            names.update(_assigned_names(statement.body))
            names.update(_assigned_names(statement.orelse))
        elif isinstance(statement, ForIR):
            names.update(target_names(statement.target))
            names.update(_expr_assigned_names(statement.iterable))
            names.update(_assigned_names(statement.body))
            names.update(_assigned_names(statement.orelse))
        elif isinstance(statement, WhileIR):
            names.update(_expr_assigned_names(statement.condition))
            names.update(_assigned_names(statement.body))
            names.update(_assigned_names(statement.orelse))
    return names


def _expr_assigned_names(expr: ExprIR) -> set[str]:
    if isinstance(expr, NamedExprIR):
        return {expr.target.id} | _expr_assigned_names(expr.value)
    if isinstance(expr, BinaryOpIR):
        return _expr_assigned_names(expr.left) | _expr_assigned_names(expr.right)
    if isinstance(expr, UnaryOpIR):
        return _expr_assigned_names(expr.value)
    if isinstance(expr, CompareIR):
        names = _expr_assigned_names(expr.left)
        for comparator in expr.comparators:
            names.update(_expr_assigned_names(comparator))
        return names
    if isinstance(expr, CallIR):
        names: set[str] = set()
        for arg in expr.args:
            names.update(_expr_assigned_names(arg))
        return names
    if isinstance(expr, IndexIR):
        return _expr_assigned_names(expr.value) | _expr_assigned_names(expr.index)
    if isinstance(expr, ListIR):
        names: set[str] = set()
        for item in expr.items:
            names.update(_expr_assigned_names(item))
        return names
    if isinstance(expr, TupleIR):
        names: set[str] = set()
        for item in expr.items:
            names.update(_expr_assigned_names(item))
        return names
    if isinstance(expr, DictIR):
        names: set[str] = set()
        for key, value in expr.items:
            names.update(_expr_assigned_names(key))
            names.update(_expr_assigned_names(value))
        return names
    if isinstance(expr, SetIR):
        names: set[str] = set()
        for item in expr.items:
            names.update(_expr_assigned_names(item))
        return names
    if isinstance(expr, ListComprehensionIR):
        return _comprehension_assigned_names(expr.generators, [expr.item])
    if isinstance(expr, DictComprehensionIR):
        return _comprehension_assigned_names(expr.generators, [expr.key, expr.value])
    if isinstance(expr, SetComprehensionIR):
        return _comprehension_assigned_names(expr.generators, [expr.item])
    return set()


def _comprehension_assigned_names(
    generators: list[ComprehensionGeneratorIR],
    result_exprs: list[ExprIR],
) -> set[str]:
    names: set[str] = set()
    for generator in generators:
        names.update(_expr_assigned_names(generator.iterable))
        for condition in generator.conditions:
            names.update(_expr_assigned_names(condition))
    for result_expr in result_exprs:
        names.update(_expr_assigned_names(result_expr))
    return names


def target_names(target: TargetIR) -> set[str]:
    if isinstance(target, NameIR):
        return {target.id}
    if isinstance(target, TupleTargetIR):
        return {item.id for item in target.items}
    return set()


def literal_int(expr: ExprIR) -> int | None:
    if isinstance(expr, LiteralIR) and isinstance(expr.value, int) and not isinstance(expr.value, bool):
        return expr.value
    return None


def same_type(left: RxtType | None, right: RxtType | None) -> bool:
    if left is None or right is None:
        return False
    return left.to_dict() == right.to_dict()


def _needs_local_type_annotation(expr: ExprIR, target_type: RxtType) -> bool:
    return (
        (isinstance(expr, (DictIR, ListIR, SetIR)) and not expr.items)
        or (isinstance(expr, LiteralIR) and expr.value is None)
        or isinstance(target_type, RxtOptional)
    )
