from __future__ import annotations

GENERATED_HEADER = "// Generated by Rextio. Do not edit manually."


def render_pyo3_module(functions: list[tuple[str, str]], module_name: str = "_rextio_native") -> str:
    lines = [
        GENERATED_HEADER,
        "",
        "use pyo3::prelude::*;",
        "use std::collections::HashMap;",
        "",
    ]
    for _rust_name, function_source in functions:
        lines.append(function_source)
        lines.append("")
    lines.extend(
        [
            "#[pymodule]",
            f"fn {module_name}(m: &Bound<'_, PyModule>) -> PyResult<()> {{",
        ]
    )
    for rust_name, _function_source in functions:
        lines.append(f"    m.add_function(wrap_pyfunction!({rust_name}, m)?)?;")
    lines.extend(
        [
            "    Ok(())",
            "}",
            "",
        ]
    )
    return "\n".join(lines)
