"""Rendering of the PyO3 module wiring."""

from __future__ import annotations

GENERATED_HEADER = "// Generated by Rextio. Do not edit manually."


def render_pyo3_module(
    functions: list[tuple[str, str]],
    module_name: str = "_rextio_native",
    exported_functions: list[str] | None = None,
    extra_prelude: list[str] | None = None,
) -> str:
    """Render the PyO3 module registration wiring for the generated functions."""
    exports = exported_functions if exported_functions is not None else [
        rust_name for rust_name, _function_source in functions
    ]
    lines = [
        GENERATED_HEADER,
        "",
        # pyo3 generates snake_case-violating function names (e.g. `app__f`) and
        # the prelude carries a few crate imports that a given module may not use;
        # silence those lints so a clean build does not bury the success line.
        "#![allow(non_snake_case, unused_imports)]",
        "",
        "use pyo3::prelude::*;",
        "use pyo3::types::{PyDict, PyTuple};",
        "use base64::Engine;",
        "use sha2::Digest;",
        "use std::collections::HashMap;",
        "use std::collections::HashSet;",
        "",
        *(extra_prelude or []),
        "" if extra_prelude else "",
        "fn rextio_call_python_runtime(",
        "    py: Python<'_>,",
        "    module_name: &str,",
        "    attr_path: &[&str],",
        "    args: &Bound<'_, PyTuple>,",
        "    kwargs: Option<&Bound<'_, PyDict>>,",
        ") -> PyResult<PyObject> {",
        "    let module = PyModule::import_bound(py, module_name)?;",
        "    let mut target = module.getattr(attr_path[0])?;",
        "    for attr in &attr_path[1..] {",
        "        target = target.getattr(*attr)?;",
        "    }",
        "    let value = target.call(args, kwargs)?;",
        "    Ok(value.unbind())",
        "}",
        "",
    ]
    for _rust_name, function_source in functions:
        lines.append(function_source)
        lines.append("")
    lines.extend(
        [
            "#[pymodule]",
            f"fn {module_name}(m: &Bound<'_, PyModule>) -> PyResult<()> {{",
        ]
    )
    for rust_name in exports:
        lines.append(f"    m.add_function(wrap_pyfunction!({rust_name}, m)?)?;")
    lines.extend(
        [
            "    Ok(())",
            "}",
            "",
        ]
    )
    return "\n".join(lines)
