from __future__ import annotations

from pathlib import Path

from rextio.analyzer.project_scanner import analyze_project
from rextio.codegen.python_wrapper.wrapper_gen import render_wrapper_module


def test_generates_wrapper_module_for_package_module(tmp_path: Path) -> None:
    source = tmp_path / "src" / "demo_pkg" / "scoring.py"
    source.parent.mkdir(parents=True)
    source.write_text(
        """
import rextio

@rextio.native
def add(a: int, b: int) -> int:
    return a + b

def helper(x: int) -> int:
    return x + 1
""",
        encoding="utf-8",
    )
    analysis = analyze_project(tmp_path)
    module = analysis.modules[0]

    wrapper = render_wrapper_module(module)

    assert wrapper.startswith("# Generated by Rextio. Do not edit manually.")
    assert "from rextio.runtime.boundary_fallback import boundary_fallback_required as _rextio_boundary_fallback_required" in wrapper
    assert "from rextio.runtime.flags import native_disabled as _rextio_native_disabled" in wrapper
    assert "from rextio.runtime.flags import native_required as _rextio_native_required" in wrapper
    assert "from . import _fallback_scoring as _rextio_fallback_module" in wrapper
    assert "from ._fallback_scoring import *  # noqa: F401,F403" in wrapper
    assert "from ._fallback_scoring import add as _rextio_fallback_fn_add" in wrapper
    assert "_rextio_native_fn_add = _rextio_load_native_function(" in wrapper
    assert 'function_name="demo_pkg__scoring__add"' in wrapper
    assert "def add(a: int, b: int) -> int:" in wrapper
    assert "if _rextio_native_required():" in wrapper
    assert "native mode requires generated native function: demo_pkg.scoring.add" in wrapper
    assert '_rextio_boundary_fallback_required("demo_pkg.scoring.add", 1000)' in wrapper
    assert "return _rextio_fallback_fn_add(a, b)" in wrapper
    assert "return _rextio_native_fn_add(a, b)" in wrapper
    assert "_rextio_fallback_module.add = add" in wrapper


def test_wrapper_uses_lazy_annotations(tmp_path: Path) -> None:
    # Council round 7 (antigravity): wrapper defs reproduce user annotations
    # verbatim, and the names are only present via the fallback star-import -
    # which misses anything hidden by __all__ or an underscore alias. Eager
    # annotation evaluation then broke the whole generated module with
    # NameError at import; PEP 563 string annotations never evaluate.
    source = tmp_path / "src" / "demo_pkg" / "scoring.py"
    source.parent.mkdir(parents=True)
    source.write_text(
        """
import rextio

__all__ = ["add"]

@rextio.native
def add(a: int, b: int) -> int:
    return a + b
""",
        encoding="utf-8",
    )
    analysis = analyze_project(tmp_path)
    wrapper = render_wrapper_module(analysis.modules[0])

    header, _, _ = wrapper.partition("def add")
    assert "from __future__ import annotations" in header
    # The future import must precede every other import to be valid Python.
    compile(wrapper, "<wrapper>", "exec")


def test_wrapper_wraps_native_set_return_as_python_set(tmp_path: Path) -> None:
    # The native side returns a Rust HashSet; the wrapper normalizes it back to a
    # Python `set`. (set[float] is not native -- it stays on the Python fallback --
    # so the boundary only handles int/bool/str sets, which pass through as-is.)
    source = tmp_path / "app.py"
    source.write_text(
        """
import rextio

@rextio.native
def unique(values: list[int]) -> set[int]:
    return {value for value in values}
""",
        encoding="utf-8",
    )
    analysis = analyze_project(tmp_path)
    module = analysis.modules[0]

    wrapper = render_wrapper_module(module)

    assert "def unique(values: list[int]) -> set[int]:" in wrapper
    assert "return _rextio_fallback_fn_unique(values)" in wrapper
    assert "return set(_rextio_native_fn_unique(values))" in wrapper


def test_wrapper_selects_native_top_level_fallback_module(tmp_path: Path) -> None:
    source = tmp_path / "app.py"
    source.write_text(
        """
total: int = 41
""",
        encoding="utf-8",
    )
    analysis = analyze_project(tmp_path, native_top_level=True)
    module = analysis.modules[0]

    wrapper = render_wrapper_module(module)

    assert 'function_name="app____rextio_top_level"' in wrapper
    assert '_REXTIO_FALLBACK_MODULE_NAME = "_fallback_app"' in wrapper
    assert '_REXTIO_NATIVE_TOP_LEVEL_FALLBACK_MODULE_NAME = "_native_top_level_fallback_app"' in wrapper
    assert "return _rextio_import_fallback_module(_REXTIO_FALLBACK_MODULE_NAME)" in wrapper
    assert "module.__dict__.update(updates)" in wrapper
    assert "globals().update(updates)" in wrapper


def test_wrapper_preserves_private_default_and_module_all_and_doc(tmp_path: Path) -> None:
    # Council round 8: defaults are eagerly evaluated even under PEP 563, so a
    # private-constant default must be bound in the wrapper namespace; the
    # module __doc__ and __all__ must be mirrored; and the runtime helpers must
    # not leak into `from module import *`.
    source = tmp_path / "src" / "demo_pkg" / "scoring.py"
    source.parent.mkdir(parents=True)
    source.write_text(
        '''"""Scoring module docstring."""
import rextio

__all__ = ["add", "PUBLIC_MAX"]

_PRIVATE_MAX = 7
PUBLIC_MAX = 9

@rextio.native
def add(a: int, b: int = _PRIVATE_MAX) -> int:
    return a + b
''',
        encoding="utf-8",
    )
    analysis = analyze_project(tmp_path)
    wrapper = render_wrapper_module(analysis.modules[0])

    # Council round 9: defaults are copied from the fallback function's
    # __defaults__ (not reproduced as expressions), so the private default
    # name never appears in the wrapper source and cannot NameError.
    assert "_PRIVATE_MAX" not in wrapper
    assert "add.__defaults__ = _rextio_fallback_fn_add.__defaults__" in wrapper
    # Docstring and __all__ are mirrored.
    assert "__doc__ = _rextio_fallback_module.__doc__" in wrapper
    assert "__all__ = list(_rextio_fallback_module.__all__)" in wrapper
    # Runtime helpers are aliased under _rextio_ so they cannot be clobbered or
    # leaked through the star-import.
    assert "import native_disabled as _rextio_native_disabled" in wrapper
    assert "import boundary_fallback_required as _rextio_boundary_fallback_required" in wrapper
    # The whole wrapper is valid Python (defaults resolve, future import first).
    compile(wrapper, "<wrapper>", "exec")



def test_wrapper_default_referencing_star_import_excluded_function(tmp_path: Path) -> None:
    # Council round 9 (glm/codex): a default referencing an accepted function
    # excluded from the fallback star-import (via __all__) that sorts AFTER the
    # referencing function used to NameError the whole module at import,
    # defeating the fallback. Defaults are now copied, not reproduced.
    source = tmp_path / "src" / "demo_pkg" / "mod.py"
    source.parent.mkdir(parents=True)
    source.write_text(
        '''"""m."""
import rextio

__all__ = ["aaa"]

@rextio.native
def zzz(x: int) -> int:
    return x + 1

@rextio.native
def aaa(x: int = zzz(0)) -> int:
    return x
''',
        encoding="utf-8",
    )
    analysis = analyze_project(tmp_path)
    wrapper = render_wrapper_module(analysis.modules[0])
    # No reproduced default expression referencing zzz; compiles cleanly.
    assert "= zzz(0)" not in wrapper
    assert "aaa.__defaults__ = _rextio_fallback_fn_aaa.__defaults__" in wrapper
    compile(wrapper, "<wrapper>", "exec")


def test_wrapper_preserves_positional_only_marker(tmp_path: Path) -> None:
    # Council round 9 (antigravity): dropping the `/` marker let the wrapper
    # accept positional-only params as keywords, diverging from CPython.
    source = tmp_path / "src" / "demo_pkg" / "mod.py"
    source.parent.mkdir(parents=True)
    source.write_text(
        """
import rextio

@rextio.native
def po(a: int, b: int, /, c: int) -> int:
    return a + b + c
""",
        encoding="utf-8",
    )
    analysis = analyze_project(tmp_path)
    wrapper = render_wrapper_module(analysis.modules[0])
    assert "def po(a: int, b: int, /, c: int)" in wrapper


def test_wrapper_rejects_static_and_class_methods(tmp_path: Path) -> None:
    # Council round 9 (claude/codex): @rextio.native on a static/classmethod
    # produced a wrapper that stripped the descriptor; the analyzer now rejects
    # these (only instance methods are supported), so the wrapper never
    # replaces them and their calling convention is preserved.
    source = tmp_path / "src" / "demo_pkg" / "mod.py"
    source.parent.mkdir(parents=True)
    source.write_text(
        """
import rextio

class C:
    @staticmethod
    @rextio.native
    def sm(x: int) -> int:
        return x + 1

    @classmethod
    @rextio.native
    def cm(cls, x: int) -> int:
        return x + 2

    @rextio.native
    def im(self, x: int) -> int:
        return x + 3
""",
        encoding="utf-8",
    )
    analysis = analyze_project(tmp_path)
    by_name = {f.qualname: f for m in analysis.modules for f in m.functions}
    assert by_name["demo_pkg.mod.C.sm"].accepted is False
    assert by_name["demo_pkg.mod.C.cm"].accepted is False
    assert by_name["demo_pkg.mod.C.im"].accepted is True
    # The rejected static/class methods are not wrapped (only C.im is).
    wrapper = render_wrapper_module(analysis.modules[0])
    assert "C.im" in wrapper
    assert "C.sm" not in wrapper
    assert "C.cm" not in wrapper


def test_wrapper_rejects_all_descriptor_method_shapes(tmp_path: Path) -> None:
    # Council round 10: the round-9 name-based static/classmethod rejection was
    # evaded by aliased decorators, @property/@cached_property, implicit
    # descriptor dunders, and class-body reassignment - all of which the
    # wrapper would strip. The generalized check rejects every non-plain
    # instance method; only the plain instance method survives.
    source = tmp_path / "src" / "demo_pkg" / "mod.py"
    source.parent.mkdir(parents=True)
    source.write_text(
        """
import rextio
import functools

sm = staticmethod
cm = classmethod

class C:
    @sm
    @rextio.native
    def aliased_sm(x: int) -> int:
        return x

    @cm
    @rextio.native
    def aliased_cm(cls, x: int) -> int:
        return x

    @property
    @rextio.native
    def prop(self) -> int:
        return 1

    @functools.cached_property
    @rextio.native
    def cached(self) -> int:
        return 2

    @rextio.native
    def __new__(cls) -> object:
        return object.__new__(cls)

    @rextio.native
    def __init_subclass__(cls, **kw) -> None:
        return None

    @rextio.native
    def moved(x: int) -> int:
        return x
    moved = staticmethod(moved)

    @rextio.native
    def im(self, x: int) -> int:
        return x + 3
""",
        encoding="utf-8",
    )
    analysis = analyze_project(tmp_path)
    accepted = {
        f.qualname: f.accepted for m in analysis.modules for f in m.functions
    }
    rejected = [
        "demo_pkg.mod.C.aliased_sm",
        "demo_pkg.mod.C.aliased_cm",
        "demo_pkg.mod.C.prop",
        "demo_pkg.mod.C.cached",
        "demo_pkg.mod.C.__new__",
        "demo_pkg.mod.C.__init_subclass__",
        "demo_pkg.mod.C.moved",
    ]
    for qualname in rejected:
        assert accepted[qualname] is False, qualname
    assert accepted["demo_pkg.mod.C.im"] is True

    # Only the plain instance method is wrapped; descriptor methods are left alone.
    wrapper = render_wrapper_module(analysis.modules[0])
    assert "C.im" in wrapper
    for name in ("aliased_sm", "aliased_cm", "prop", "cached", "__new__", "moved"):
        assert f"C.{name}" not in wrapper


def test_wrapper_rejects_evasive_method_reassignment_spellings(tmp_path: Path) -> None:
    # Council round 11 (kimi, glm): the round-10 class-body reassignment scan
    # only matched a bare `name = staticmethod(name)` Assign whose call was the
    # literal wrapper name. Three spellings evaded it and were wrongly accepted,
    # emitting a wrapper that stripped the descriptor and crashed at call time:
    #   - annotated assignment:   `im: staticmethod = staticmethod(im)`
    #   - tuple/list unpacking:   `im, _ = staticmethod(im), 0`
    #   - aliased wrapper name:   `sm = staticmethod; im = sm(im)`
    # The scan now rejects ANY reassignment of the method name after its def.
    source = tmp_path / "src" / "demo_pkg" / "mod.py"
    source.parent.mkdir(parents=True)
    source.write_text(
        """
import rextio

sm = staticmethod

def _mk(x: int) -> int:
    return x

class Ann:
    @rextio.native
    def im(self, x: int) -> int:
        return x + 1
    im: staticmethod = staticmethod(_mk)

class Unpack:
    @rextio.native
    def im(self, x: int) -> int:
        return x + 1
    im, _spare = staticmethod(_mk), 0

class Alias:
    @rextio.native
    def im(self, x: int) -> int:
        return x + 1
    im = sm(im)
""",
        encoding="utf-8",
    )
    analysis = analyze_project(tmp_path)
    accepted = {f.qualname: f.accepted for m in analysis.modules for f in m.functions}
    for cls in ("Ann", "Unpack", "Alias"):
        assert accepted[f"demo_pkg.mod.{cls}.im"] is False, cls
    wrapper = render_wrapper_module(analysis.modules[0])
    for cls in ("Ann", "Unpack", "Alias"):
        assert f"{cls}.im" not in wrapper, cls


def test_wrapper_accepts_plain_instance_method_despite_unrelated_reassignment(
    tmp_path: Path,
) -> None:
    # Council round 11: the conservative reassignment scan must not false-reject
    # a plain instance method when (a) an UNRELATED name is reassigned, (b) an
    # assignment to the same name appears BEFORE the def (the def wins), or
    # (c) a bare annotation with no value (which does not rebind) is present.
    source = tmp_path / "src" / "demo_pkg" / "mod.py"
    source.parent.mkdir(parents=True)
    source.write_text(
        """
import rextio

def _helper(x: int) -> int:
    return x

class Unrelated:
    @rextio.native
    def im(self, x: int) -> int:
        return x + 1
    other = staticmethod(_helper)

class PreDef:
    im = staticmethod(_helper)
    @rextio.native
    def im(self, x: int) -> int:
        return x + 1

class BareAnn:
    @rextio.native
    def im(self, x: int) -> int:
        return x + 1
    im: int
""",
        encoding="utf-8",
    )
    analysis = analyze_project(tmp_path)
    accepted = {f.qualname: f.accepted for m in analysis.modules for f in m.functions}
    for cls in ("Unrelated", "PreDef", "BareAnn"):
        assert accepted[f"demo_pkg.mod.{cls}.im"] is True, cls


def test_wrapper_rejects_native_method_in_nested_class(tmp_path: Path) -> None:
    # Council round 11 (antigravity, kimi): a @rextio.native method inside a
    # class nested in another class was collected by neither the analyzer nor
    # the wrapper generator - the marker was dropped silently, neither honored
    # nor rejected. It is now rejected with an RXT010 diagnostic (honor-or-
    # reject reporting contract), at any nesting depth.
    source = tmp_path / "src" / "demo_pkg" / "mod.py"
    source.parent.mkdir(parents=True)
    source.write_text(
        """
import rextio

class Outer:
    class Inner:
        @rextio.native
        def im(self, x: int) -> int:
            return x + 1

class A:
    class B:
        class C:
            @rextio.native
            def deep(self, x: int) -> int:
                return x
""",
        encoding="utf-8",
    )
    analysis = analyze_project(tmp_path)
    by_qual = {f.qualname: f for m in analysis.modules for f in m.functions}
    for qual in ("demo_pkg.mod.Outer.Inner.im", "demo_pkg.mod.A.B.C.deep"):
        assert qual in by_qual, qual
        assert by_qual[qual].accepted is False, qual
        assert any(d.code == "RXT010" for d in by_qual[qual].diagnostics), qual


def test_wrapper_rejects_reassignment_inside_class_body_control_flow(
    tmp_path: Path,
) -> None:
    # Council round 12 (8 members): the round-11 reassignment scan iterated only
    # the DIRECT children of the class body, so a descriptor reassignment nested
    # inside a class-body compound statement (if/for/while/with/try) - or a
    # walrus/augmented assignment - evaded it and wrongly ACCEPTed the method,
    # reopening the descriptor-stripping crash. The scan now walks compound
    # statements (up to nested-scope boundaries) and covers `:=`/`+=`.
    source = tmp_path / "src" / "demo_pkg" / "mod.py"
    source.parent.mkdir(parents=True)
    source.write_text(
        """
import rextio
import contextlib

def _mk(x: int) -> int:
    return x

class IfC:
    @rextio.native
    def im(self, x: int) -> int:
        return x + 1
    if True:
        im = staticmethod(_mk)

class ForC:
    @rextio.native
    def im(self, x: int) -> int:
        return x + 1
    for _ in range(1):
        im = staticmethod(_mk)

class TryC:
    @rextio.native
    def im(self, x: int) -> int:
        return x + 1
    try:
        im = staticmethod(_mk)
    except Exception:
        pass

class WalrusC:
    @rextio.native
    def im(self, x: int) -> int:
        return x + 1
    if (im := staticmethod(_mk)):
        pass

class AugC:
    @rextio.native
    def im(self, x: int) -> int:
        return x + 1
    im += 1
""",
        encoding="utf-8",
    )
    analysis = analyze_project(tmp_path)
    accepted = {f.qualname: f.accepted for m in analysis.modules for f in m.functions}
    for cls in ("IfC", "ForC", "TryC", "WalrusC", "AugC"):
        assert accepted[f"demo_pkg.mod.{cls}.im"] is False, cls
    wrapper = render_wrapper_module(analysis.modules[0])
    for cls in ("IfC", "ForC", "TryC", "WalrusC", "AugC"):
        assert f"{cls}.im" not in wrapper, cls


def test_reassignment_scan_no_false_positive_from_control_flow(tmp_path: Path) -> None:
    # Council round 12: the compound-statement-aware scan must not over-reject.
    # An UNRELATED name reassigned in a control-flow block, and a local variable
    # of the same name inside a nested function (a separate scope), must both
    # leave the plain instance method accepted.
    source = tmp_path / "src" / "demo_pkg" / "mod.py"
    source.parent.mkdir(parents=True)
    source.write_text(
        """
import rextio

def _mk(x: int) -> int:
    return x

class Unrelated:
    @rextio.native
    def im(self, x: int) -> int:
        return x + 1
    if True:
        other = staticmethod(_mk)

class NestedScope:
    @rextio.native
    def im(self, x: int) -> int:
        return x + 1
    def _helper():
        im = 5
        return im
""",
        encoding="utf-8",
    )
    analysis = analyze_project(tmp_path)
    accepted = {f.qualname: f.accepted for m in analysis.modules for f in m.functions}
    assert accepted["demo_pkg.mod.Unrelated.im"] is True
    assert accepted["demo_pkg.mod.NestedScope.im"] is True


def test_wrapper_rejects_native_method_in_control_flow_nested_class(
    tmp_path: Path,
) -> None:
    # Council round 12 (codex): the round-11 nested-class rejection also scanned
    # only DIRECT class-body children, so a class nested UNDER a class-body
    # compound statement (if/for/try/...) was silently dropped again. The walk
    # now finds it and emits RXT010.
    source = tmp_path / "src" / "demo_pkg" / "mod.py"
    source.parent.mkdir(parents=True)
    source.write_text(
        """
import rextio

class IfOuter:
    if True:
        class Inner:
            @rextio.native
            def im(self, x: int) -> int:
                return x + 1

class TryOuter:
    try:
        class Inner:
            @rextio.native
            def im(self, x: int) -> int:
                return x + 1
    except Exception:
        pass
""",
        encoding="utf-8",
    )
    analysis = analyze_project(tmp_path)
    by_qual = {f.qualname: f for m in analysis.modules for f in m.functions}
    for qual in ("demo_pkg.mod.IfOuter.Inner.im", "demo_pkg.mod.TryOuter.Inner.im"):
        assert qual in by_qual, qual
        assert by_qual[qual].accepted is False, qual
        assert any(d.code == "RXT010" for d in by_qual[qual].diagnostics), qual


def test_nested_class_malformed_marker_reports_marker_error(tmp_path: Path) -> None:
    # Council round 12 (glm, minimax): a malformed @rextio.native marker on a
    # nested-class method was rejected with only the generic nested-class message,
    # losing the specific marker-shape error (both carry code RXT010 at the same
    # site, so they cannot coexist). The marker-error message is now preserved so
    # the user fixes the marker itself first.
    source = tmp_path / "src" / "demo_pkg" / "mod.py"
    source.parent.mkdir(parents=True)
    source.write_text(
        """
import rextio

class Outer:
    class Inner:
        @rextio.native(target="cobol")
        def im(self, x: int) -> int:
            return x + 1
""",
        encoding="utf-8",
    )
    analysis = analyze_project(tmp_path)
    by_qual = {f.qualname: f for m in analysis.modules for f in m.functions}
    fn = by_qual["demo_pkg.mod.Outer.Inner.im"]
    assert fn.accepted is False
    messages = " ".join(d.message for d in fn.diagnostics)
    assert "cobol" in messages, messages
    assert "nested" not in messages, messages


def test_wrapper_mirrors_control_flow_defined_all(tmp_path: Path) -> None:
    # Council round 10 (codex): __all__ defined by control flow (or import) was
    # missed by the AST heuristic; it is now mirrored at runtime.
    source = tmp_path / "src" / "demo_pkg" / "mod.py"
    source.parent.mkdir(parents=True)
    source.write_text(
        """
import rextio
if True:
    __all__ = ["keep"]
EXTRA = 1
@rextio.native
def keep(x: int) -> int:
    return x
""",
        encoding="utf-8",
    )
    analysis = analyze_project(tmp_path)
    wrapper = render_wrapper_module(analysis.modules[0])
    assert 'if hasattr(_rextio_fallback_module, "__all__"):' in wrapper
    compile(wrapper, "<wrapper>", "exec")
