from __future__ import annotations

from pathlib import Path

from rextio.analyzer.project_scanner import analyze_project
from rextio.codegen.rust.generator import generate_rust_module
from rextio.ir.lowering import lower_project


def test_generates_deterministic_pyo3_rust_for_native_functions(tmp_path: Path) -> None:
    (tmp_path / "app.py").write_text(
        """
import rextio

@rextio.native
def square(x: float) -> float:
    return x * x

@rextio.native
def sum_squares(xs: list[float]) -> float:
    total = 0.0
    for x in xs:
        total += square(x)
    return total
""",
        encoding="utf-8",
    )

    source = generate_rust_module(lower_project(analyze_project(tmp_path)))

    assert source.startswith("// Generated by Rextio. Do not edit manually.")
    assert "#[pyfunction]\nfn app__square(x: f64) -> PyResult<f64> {" in source
    assert "fn app__sum_squares(xs: Vec<f64>) -> PyResult<f64> {" in source
    assert "for x in xs.iter().cloned() {" in source
    assert "return Ok(x * x);" in source
    assert "total = total + app__square(x.clone())?;" in source
    assert "fn _rextio_native(m: &Bound<'_, PyModule>) -> PyResult<()> {" in source
    assert "m.add_function(wrap_pyfunction!(app__square, m)?)?;" in source
    assert "m.add_function(wrap_pyfunction!(app__sum_squares, m)?)?;" in source


def test_generates_rust_for_cross_module_native_calls(tmp_path: Path) -> None:
    math_ops = tmp_path / "src" / "demo_codegen" / "math_ops.py"
    scoring = tmp_path / "src" / "demo_codegen" / "scoring.py"
    math_ops.parent.mkdir(parents=True)
    math_ops.write_text(
        """
import rextio

@rextio.native
def square(x: float) -> float:
    return x * x
""",
        encoding="utf-8",
    )
    scoring.write_text(
        """
import rextio

from .math_ops import square

@rextio.native
def score(x: float) -> float:
    return square(x) + 1.0
""",
        encoding="utf-8",
    )

    source = generate_rust_module(lower_project(analyze_project(tmp_path)))

    assert "fn demo_codegen__math_ops__square(x: f64) -> PyResult<f64> {" in source
    assert "fn demo_codegen__scoring__score(x: f64) -> PyResult<f64> {" in source
    assert "return Ok(demo_codegen__math_ops__square(x.clone())? + 1.0);" in source


def test_native_call_clones_name_arguments_to_avoid_moving_reused_values(tmp_path: Path) -> None:
    (tmp_path / "app.py").write_text(
        """
import rextio

@rextio.native
def total(values: list[float]) -> float:
    result = 0.0
    for value in values:
        result += value
    return result

@rextio.native
def compute(values: list[float]) -> float:
    subtotal = total(values)
    return subtotal + values[0]
""",
        encoding="utf-8",
    )

    source = generate_rust_module(lower_project(analyze_project(tmp_path)))

    assert "let mut subtotal = app__total(values.clone())?;" in source
    assert "return Ok(subtotal + values[0 as usize].clone());" in source


def test_generates_rust_for_contextually_inferred_signatures(tmp_path: Path) -> None:
    (tmp_path / "app.py").write_text(
        """
def add_one(x):
    return x + 1

def sum_squares(xs):
    total = 0
    for x in xs:
        total += x * x
    return total
""",
        encoding="utf-8",
    )

    source = generate_rust_module(lower_project(analyze_project(tmp_path)))

    assert "fn app__add_one(x: i64) -> PyResult<i64> {" in source
    assert "return Ok(x + 1);" in source
    assert "fn app__sum_squares(xs: Vec<i64>) -> PyResult<i64> {" in source
    assert "for x in xs.iter().cloned() {" in source


def test_generates_rust_using_sibling_pyi_signatures(tmp_path: Path) -> None:
    source = tmp_path / "src" / "stubbed" / "ops.py"
    source.parent.mkdir(parents=True)
    source.write_text(
        """
def dot(xs, ys):
    total = 0.0
    for x, y in zip(xs, ys):
        total += x * y
    return total
""",
        encoding="utf-8",
    )
    source.with_suffix(".pyi").write_text(
        """
def dot(xs: list[float], ys: list[float]) -> float: ...
""",
        encoding="utf-8",
    )

    source = generate_rust_module(lower_project(analyze_project(tmp_path)))

    assert "fn stubbed__ops__dot(xs: Vec<f64>, ys: Vec<f64>) -> PyResult<f64> {" in source
    assert "for (x, y) in xs.iter().cloned().zip(ys.iter().cloned()) {" in source


def test_generates_rust_for_if_range_len_indexing_and_while(tmp_path: Path) -> None:
    (tmp_path / "app.py").write_text(
        """
import rextio

@rextio.native
def count_positive(xs: list[int]) -> int:
    count = 0
    for i in range(len(xs)):
        if xs[i] > 0:
            count += 1
    return count

@rextio.native
def decrement_to_zero(n: int) -> int:
    while n > 0:
        n -= 1
    return n
""",
        encoding="utf-8",
    )

    source = generate_rust_module(lower_project(analyze_project(tmp_path)))

    assert "fn app__count_positive(xs: Vec<i64>) -> PyResult<i64> {" in source
    assert "for i in 0..(xs.len() as i64) {" in source
    assert "if xs[i as usize].clone() > 0 {" in source
    assert "count = count + 1;" in source
    assert "fn app__decrement_to_zero(mut n: i64) -> PyResult<i64> {" in source
    assert "while n > 0 {" in source
    assert "n = n - 1;" in source


def test_generates_rust_for_string_literal_and_string_indexing(tmp_path: Path) -> None:
    (tmp_path / "app.py").write_text(
        """
import rextio

@rextio.native
def default_label() -> str:
    return "ready"

@rextio.native
def first_label(values: list[str]) -> str:
    return values[0]
""",
        encoding="utf-8",
    )

    source = generate_rust_module(lower_project(analyze_project(tmp_path)))

    assert 'return Ok(String::from("ready"));' in source
    assert "return Ok(values[0 as usize].clone());" in source


def test_range_len_index_can_be_used_as_public_1_int(tmp_path: Path) -> None:
    (tmp_path / "app.py").write_text(
        """
import rextio

@rextio.native
def sum_indices(xs: list[int]) -> int:
    total = 0
    for i in range(len(xs)):
        total += i
        total += xs[i]
    return total
""",
        encoding="utf-8",
    )

    source = generate_rust_module(lower_project(analyze_project(tmp_path)))

    assert "for i in 0..(xs.len() as i64) {" in source
    assert "total = total + i;" in source
    assert "total = total + xs[i as usize].clone();" in source


def test_generates_rust_for_range_variants_break_and_continue(tmp_path: Path) -> None:
    (tmp_path / "app.py").write_text(
        """
import rextio

@rextio.native
def stepped_total(n: int) -> int:
    total = 0
    for i in range(1, n, 2):
        if i > 10:
            break
        if i == 5:
            continue
        total += i
    return total
""",
        encoding="utf-8",
    )

    source = generate_rust_module(lower_project(analyze_project(tmp_path)))

    assert "for i in (1..n).step_by(2 as usize) {" in source
    assert "break;" in source
    assert "continue;" in source
    assert "total = total + i;" in source


def test_generates_rust_for_list_literals_and_append(tmp_path: Path) -> None:
    (tmp_path / "app.py").write_text(
        """
import rextio

@rextio.native
def collect_positive(xs: list[int]) -> list[int]:
    out: list[int] = []
    for x in xs:
        if x > 0:
            out.append(x)
    return out

@rextio.native
def labels() -> list[str]:
    return ["ready", "set"]
""",
        encoding="utf-8",
    )

    source = generate_rust_module(lower_project(analyze_project(tmp_path)))

    assert "let mut out: Vec<i64> = vec![];" in source
    assert "out.push(x.clone());" in source
    assert 'return Ok(vec![String::from("ready"), String::from("set")]);' in source


def test_generates_rust_for_fixed_tuples_limited_dicts_and_optional_types(
    tmp_path: Path,
) -> None:
    (tmp_path / "app.py").write_text(
        """
from typing import Optional
import rextio

@rextio.native
def first_value(pair: tuple[int, float]) -> int:
    return pair[0]

@rextio.native
def make_pair(x: int, y: float) -> tuple[int, float]:
    return (x, y)

@rextio.native
def read_score(scores: dict[str, int], key: str) -> int:
    return scores[key]

@rextio.native
def build_weights() -> dict[str, float]:
    weights: dict[str, float] = {}
    weights["a"] = 1.5
    return weights

@rextio.native
def maybe(flag: bool, x: int) -> Optional[int]:
    if flag:
        return x
    return None

@rextio.native
def echo(value: int | None) -> int | None:
    if value is None:
        return None
    return value
""",
        encoding="utf-8",
    )

    source = generate_rust_module(lower_project(analyze_project(tmp_path)))

    assert "use std::collections::HashMap;" in source
    assert "fn app__first_value(pair: (i64, f64)) -> PyResult<i64> {" in source
    assert "return Ok(pair.0.clone());" in source
    assert "fn app__make_pair(x: i64, y: f64) -> PyResult<(i64, f64)> {" in source
    assert "return Ok((x, y));" in source
    assert "fn app__read_score(scores: HashMap<String, i64>, key: String) -> PyResult<i64> {" in source
    assert "scores.get(&key).cloned().ok_or_else(|| pyo3::exceptions::PyKeyError::new_err(key.clone()))?" in source
    assert "let mut weights: HashMap<String, f64> = HashMap::new();" in source
    assert 'weights.insert(String::from("a"), 1.5);' in source
    assert "fn app__maybe(flag: bool, x: i64) -> PyResult<Option<i64>> {" in source
    assert "return Ok(Some(x));" in source
    assert "return Ok(None);" in source
    assert "fn app__echo(value: Option<i64>) -> PyResult<Option<i64>> {" in source
    assert "if value == None {" in source


def test_generates_rust_for_enumerate_and_zip_batch_loops(tmp_path: Path) -> None:
    (tmp_path / "app.py").write_text(
        """
import rextio

@rextio.native
def indexed_offsets(xs: list[int]) -> list[int]:
    out: list[int] = []
    for i, x in enumerate(xs):
        out.append(i + x)
    return out

@rextio.native
def dot(xs: list[float], ys: list[float]) -> float:
    total = 0.0
    for x, y in zip(xs, ys):
        total += x * y
    return total
""",
        encoding="utf-8",
    )

    source = generate_rust_module(lower_project(analyze_project(tmp_path)))

    assert (
        "for (i, x) in xs.iter().cloned().enumerate()"
        ".map(|(i, value)| (i as i64, value)) {"
    ) in source
    assert "out.push(i + x);" in source
    assert "for (x, y) in xs.iter().cloned().zip(ys.iter().cloned()) {" in source
    assert "total = total + (x * y);" in source


def test_generates_rust_for_comprehensions_and_nested_collections(tmp_path: Path) -> None:
    (tmp_path / "app.py").write_text(
        """
import rextio

@rextio.native
def inc(x: int) -> int:
    return x + 1

@rextio.native
def squares(xs: list[int]) -> list[int]:
    return [inc(x) for x in xs if x > 0]

@rextio.native
def indexed(xs: list[int]) -> list[int]:
    return [i + x for i, x in enumerate(xs)]

@rextio.native
def flatten(rows: list[list[int]]) -> list[int]:
    return [x for row in rows for x in row]

@rextio.native
def nested(rows: list[list[int]]) -> list[list[int]]:
    return [[x + 1 for x in row] for row in rows]

@rextio.native
def labels(xs: list[str]) -> dict[str, str]:
    return {x: x for x in xs}

@rextio.native
def lookup(scores: dict[str, int], xs: list[str]) -> list[int]:
    return [scores[x] for x in xs]

@rextio.native
def unique(xs: list[int]) -> set[int]:
    return {x for x in xs if x > 0}

@rextio.native
def unique_float(xs: list[float]) -> set[float]:
    return {x for x in xs if x > 0.0}

@rextio.native
def by_index(xs: list[int]) -> dict[int, float]:
    return {i: 1.5 for i, x in enumerate(xs) if x > 0}

@rextio.native
def flags(xs: list[int]) -> dict[bool, str]:
    return {x > 0: "seen" for x in xs}

@rextio.native
def last_positive(xs: list[int]) -> int:
    out = [y for x in xs if (y := x) > 0]
    return y
""",
        encoding="utf-8",
    )

    source = generate_rust_module(lower_project(analyze_project(tmp_path)))

    assert "fn app__nested(rows: Vec<Vec<i64>>) -> PyResult<Vec<Vec<i64>>> {" in source
    assert "let mut __rextio_list_1 = Vec::new();" in source
    assert "for row in rows.iter().cloned() {" in source
    assert "for x in row.iter().cloned() {" in source
    assert "__rextio_list_1.push(app__inc(x.clone())?);" in source
    assert (
        "for (i, x) in xs.iter().cloned().enumerate()"
        ".map(|(i, value)| (i as i64, value)) {"
    ) in source
    assert "fn app__labels(xs: Vec<String>) -> PyResult<HashMap<String, String>> {" in source
    assert "__rextio_dict_1.insert(x.clone(), x.clone());" in source
    assert "fn app__by_index(xs: Vec<i64>) -> PyResult<HashMap<i64, f64>> {" in source
    assert "fn app__flags(xs: Vec<i64>) -> PyResult<HashMap<bool, String>> {" in source
    assert "scores.get(&x).cloned().ok_or_else(|| pyo3::exceptions::PyKeyError::new_err(x.clone()))?" in source
    assert "fn app__unique(xs: Vec<i64>) -> PyResult<HashSet<i64>> {" in source
    assert "fn app__unique_float(xs: Vec<f64>) -> PyResult<Vec<f64>> {" in source
    assert "let mut __rextio_set_1 = Vec::new();" in source
    assert "if !__rextio_set_1.contains(&__rextio_set_value_" in source
    assert "let mut y: Option<i64> = None;" in source
    assert "y = Some(x.clone());" in source
    assert "PyUnboundLocalError" in source


def test_generates_native_helpers_before_callers(tmp_path: Path) -> None:
    (tmp_path / "app.py").write_text(
        """
import rextio

@rextio.native
def a_compute(x: int) -> int:
    return z_helper(x) + 1

@rextio.native
def z_helper(x: int) -> int:
    return x * 2
""",
        encoding="utf-8",
    )

    source = generate_rust_module(lower_project(analyze_project(tmp_path)))

    assert source.index("fn app__z_helper") < source.index("fn app__a_compute")
    assert "return Ok(app__z_helper(x.clone())? + 1);" in source


def test_generates_rust_for_limited_builtins_and_math_subset(tmp_path: Path) -> None:
    (tmp_path / "app.py").write_text(
        """
import math
import rextio

@rextio.native
def numeric(values: list[float], x: float) -> float:
    total: float = sum(values)
    return math.sqrt(x) + math.sin(x) + math.cos(x) + max(total, abs(x))

@rextio.native
def lower(x: float, y: float) -> int:
    return min(math.floor(x), math.floor(y))
""",
        encoding="utf-8",
    )

    source = generate_rust_module(lower_project(analyze_project(tmp_path)))

    assert "let mut total = (values).iter().cloned().sum();" in source
    assert "(x).sqrt()" in source
    assert "(x).sin()" in source
    assert "(x).cos()" in source
    assert "(total).max((x).abs())" in source
    assert "return Ok((((x).floor() as i64)).min(((y).floor() as i64)));" in source


def test_len_lowers_to_public_1_int(tmp_path: Path) -> None:
    (tmp_path / "app.py").write_text(
        """
import rextio

@rextio.native
def size_plus_first(xs: list[int]) -> int:
    return len(xs) + xs[0]
""",
        encoding="utf-8",
    )

    source = generate_rust_module(lower_project(analyze_project(tmp_path)))

    assert "return Ok((xs.len() as i64) + xs[0 as usize].clone());" in source


def test_generates_rust_for_supported_native_top_level(tmp_path: Path) -> None:
    (tmp_path / "app.py").write_text(
        """
total: int = 0
i: int = 0
while i < 4:
    total += i
    i += 1
""",
        encoding="utf-8",
    )

    source = generate_rust_module(lower_project(analyze_project(tmp_path, native_top_level=True)))

    assert "fn app____rextio_top_level() -> PyResult<HashMap<String, i64>> {" in source
    assert "let mut total = 0;" in source
    assert "while i < 4 {" in source
    assert 'map.insert(String::from("i"), i);' in source
    assert 'map.insert(String::from("total"), total);' in source
    assert "m.add_function(wrap_pyfunction!(app____rextio_top_level, m)?)?;" in source
