from __future__ import annotations

from pathlib import Path

from rextio.analyzer.project_scanner import analyze_project
from rextio.codegen.python_wrapper.wrapper_gen import render_wrapper_module


def test_generates_wrapper_module_for_package_module(tmp_path: Path) -> None:
    source = tmp_path / "src" / "demo_pkg" / "scoring.py"
    source.parent.mkdir(parents=True)
    source.write_text(
        """
import rextio

@rextio.native
def add(a: int, b: int) -> int:
    return a + b

def helper(x: int) -> int:
    return x + 1
""",
        encoding="utf-8",
    )
    analysis = analyze_project(tmp_path)
    module = analysis.modules[0]

    wrapper = render_wrapper_module(module)

    assert wrapper.startswith("# Generated by Rextio. Do not edit manually.")
    assert "from rextio.runtime.boundary_fallback import boundary_fallback_required" in wrapper
    assert "from rextio.runtime.flags import native_disabled, native_required" in wrapper
    assert "from . import _fallback_scoring as _rextio_fallback_module" in wrapper
    assert "from ._fallback_scoring import *  # noqa: F401,F403" in wrapper
    assert "from ._fallback_scoring import add as _fallback_add" in wrapper
    assert "_native_add = load_native_function(" in wrapper
    assert 'function_name="demo_pkg__scoring__add"' in wrapper
    assert "def add(a: int, b: int) -> int:" in wrapper
    assert "if native_required():" in wrapper
    assert "native mode requires generated native function: demo_pkg.scoring.add" in wrapper
    assert 'boundary_fallback_required("demo_pkg.scoring.add", 1000)' in wrapper
    assert "return _fallback_add(a, b)" in wrapper
    assert "return _native_add(a, b)" in wrapper
    assert "_rextio_fallback_module.add = add" in wrapper


def test_wrapper_wraps_native_set_return_as_python_set(tmp_path: Path) -> None:
    # The native side returns a Rust HashSet; the wrapper normalizes it back to a
    # Python `set`. (set[float] is not native -- it stays on the Python fallback --
    # so the boundary only handles int/bool/str sets, which pass through as-is.)
    source = tmp_path / "app.py"
    source.write_text(
        """
import rextio

@rextio.native
def unique(values: set[int]) -> set[int]:
    return {value for value in values}
""",
        encoding="utf-8",
    )
    analysis = analyze_project(tmp_path)
    module = analysis.modules[0]

    wrapper = render_wrapper_module(module)

    assert "def unique(values: set[int]) -> set[int]:" in wrapper
    assert "return _fallback_unique(values)" in wrapper
    assert "return set(_native_unique(values))" in wrapper


def test_wrapper_selects_native_top_level_fallback_module(tmp_path: Path) -> None:
    source = tmp_path / "app.py"
    source.write_text(
        """
total: int = 41
""",
        encoding="utf-8",
    )
    analysis = analyze_project(tmp_path, native_top_level=True)
    module = analysis.modules[0]

    wrapper = render_wrapper_module(module)

    assert 'function_name="app____rextio_top_level"' in wrapper
    assert '_REXTIO_FALLBACK_MODULE_NAME = "_fallback_app"' in wrapper
    assert '_REXTIO_NATIVE_TOP_LEVEL_FALLBACK_MODULE_NAME = "_native_top_level_fallback_app"' in wrapper
    assert "return _rextio_import_fallback_module(_REXTIO_FALLBACK_MODULE_NAME)" in wrapper
    assert "module.__dict__.update(updates)" in wrapper
    assert "globals().update(updates)" in wrapper
