from __future__ import annotations

from pathlib import Path

from rextio.analyzer.project_scanner import analyze_project
from rextio.codegen.rust.generator import generate_rust_module
from rextio.ir.lowering import lower_project


def test_generates_deterministic_pyo3_rust_for_native_functions(tmp_path: Path) -> None:
    (tmp_path / "app.py").write_text(
        """
import rextio

@rextio.native
def square(x: float) -> float:
    return x * x

@rextio.native
def sum_squares(xs: list[float]) -> float:
    total = 0.0
    for x in xs:
        total += square(x)
    return total
""",
        encoding="utf-8",
    )

    source = generate_rust_module(lower_project(analyze_project(tmp_path)))

    assert source.startswith("// Generated by Rextio. Do not edit manually.")
    assert "#[pyfunction]\nfn app__square(x: f64) -> PyResult<f64> {" in source
    assert "fn app__sum_squares(xs: Vec<f64>) -> PyResult<f64> {" in source
    assert "for x in xs.iter().cloned() {" in source
    assert "return Ok(x * x);" in source
    assert "total = total + app__square(x.clone())?;" in source
    assert "fn _rextio_native(m: &Bound<'_, PyModule>) -> PyResult<()> {" in source
    assert "m.add_function(wrap_pyfunction!(app__square, m)?)?;" in source
    assert "m.add_function(wrap_pyfunction!(app__sum_squares, m)?)?;" in source


def test_generates_rust_for_cross_module_native_calls(tmp_path: Path) -> None:
    math_ops = tmp_path / "src" / "demo_codegen" / "math_ops.py"
    scoring = tmp_path / "src" / "demo_codegen" / "scoring.py"
    math_ops.parent.mkdir(parents=True)
    math_ops.write_text(
        """
import rextio

@rextio.native
def square(x: float) -> float:
    return x * x
""",
        encoding="utf-8",
    )
    scoring.write_text(
        """
import rextio

from .math_ops import square

@rextio.native
def score(x: float) -> float:
    return square(x) + 1.0
""",
        encoding="utf-8",
    )

    source = generate_rust_module(lower_project(analyze_project(tmp_path)))

    assert "fn demo_codegen__math_ops__square(x: f64) -> PyResult<f64> {" in source
    assert "fn demo_codegen__scoring__score(x: f64) -> PyResult<f64> {" in source
    assert "return Ok(demo_codegen__math_ops__square(x.clone())? + 1.0);" in source


def test_native_call_clones_name_arguments_to_avoid_moving_reused_values(tmp_path: Path) -> None:
    (tmp_path / "app.py").write_text(
        """
import rextio

@rextio.native
def total(values: list[float]) -> float:
    result = 0.0
    for value in values:
        result += value
    return result

@rextio.native
def compute(values: list[float]) -> float:
    subtotal = total(values)
    return subtotal + values[0]
""",
        encoding="utf-8",
    )

    source = generate_rust_module(lower_project(analyze_project(tmp_path)))

    assert "let mut subtotal = app__total(values.clone())?;" in source
    assert "return Ok(subtotal + values[0].clone());" in source


def test_generates_rust_for_if_range_len_indexing_and_while(tmp_path: Path) -> None:
    (tmp_path / "app.py").write_text(
        """
import rextio

@rextio.native
def count_positive(xs: list[int]) -> int:
    count = 0
    for i in range(len(xs)):
        if xs[i] > 0:
            count += 1
    return count

@rextio.native
def decrement_to_zero(n: int) -> int:
    while n > 0:
        n -= 1
    return n
""",
        encoding="utf-8",
    )

    source = generate_rust_module(lower_project(analyze_project(tmp_path)))

    assert "fn app__count_positive(xs: Vec<i64>) -> PyResult<i64> {" in source
    assert "for i in 0..xs.len() {" in source
    assert "if xs[i].clone() > 0 {" in source
    assert "count = count + 1;" in source
    assert "fn app__decrement_to_zero(mut n: i64) -> PyResult<i64> {" in source
    assert "while n > 0 {" in source
    assert "n = n - 1;" in source


def test_generates_rust_for_string_literal_and_string_indexing(tmp_path: Path) -> None:
    (tmp_path / "app.py").write_text(
        """
import rextio

@rextio.native
def default_label() -> str:
    return "ready"

@rextio.native
def first_label(values: list[str]) -> str:
    return values[0]
""",
        encoding="utf-8",
    )

    source = generate_rust_module(lower_project(analyze_project(tmp_path)))

    assert 'return Ok(String::from("ready"));' in source
    assert "return Ok(values[0].clone());" in source
