// Generated by Rextio. Do not edit manually.

use base64::Engine;
use sha2::Digest;
use std::collections::HashMap;
use std::collections::HashSet;

#[derive(Debug, Clone, PartialEq, Eq)]
pub struct RextioError {
    message: String,
}

impl RextioError {
    pub fn new(message: impl Into<String>) -> Self {
        Self { message: message.into() }
    }

    pub fn message(&self) -> &str {
        &self.message
    }
}

impl std::fmt::Display for RextioError {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        write!(f, "{}", self.message)
    }
}

impl std::error::Error for RextioError {}

pub fn app__at(xs: Vec<i64>, i: i64) -> Result<i64, RextioError> {
    return Ok({ let __rextio_seq_1 = &xs; let __rextio_len_3 = __rextio_seq_1.len() as i64; let __rextio_index_2 = (i) as i64; let __rextio_index_2 = if __rextio_index_2 < 0 { __rextio_index_2.checked_add(__rextio_len_3) } else { Some(__rextio_index_2) }; (match __rextio_index_2 { Some(__rextio_bound_4) if __rextio_bound_4 >= 0 && __rextio_bound_4 < __rextio_len_3 => __rextio_seq_1.get(__rextio_bound_4 as usize).cloned(), _ => None }).ok_or_else(|| RextioError::new("list index out of range"))? });
}

pub fn app__classify(n: i64) -> Result<String, RextioError> {
    if n > 0 {
        return Ok(String::from("positive"));
    }
    if n < 0 {
        return Ok(String::from("negative"));
    }
    return Ok(String::from("zero"));
}

pub fn app__doubled(xs: Vec<i64>) -> Result<Vec<i64>, RextioError> {
    return Ok({
    let mut __rextio_list_1 = Vec::new();
    for x in xs.iter().cloned() {
        __rextio_list_1.push(x * 2);
    }
    __rextio_list_1
});
}

pub fn app__lookup(scores: HashMap<String, i64>, key: String) -> Result<i64, RextioError> {
    return Ok({ let __rextio_map_1 = &scores; let __rextio_key_2 = key; __rextio_map_1.get(&__rextio_key_2).cloned().ok_or_else(|| RextioError::new(format!("key not found: {:?}", __rextio_key_2)))? });
}

pub fn app__total(xs: Vec<i64>) -> Result<i64, RextioError> {
    let mut acc = 0;
    for x in xs.iter().cloned() {
        acc = acc + x;
    }
    return Ok(acc);
}

pub fn app__sum_total(xs: Vec<i64>) -> Result<i64, RextioError> {
    return Ok(app__total(xs.clone())? + 1);
}
