// Generated by Rextio. Do not edit manually.

#![allow(non_snake_case, unused_imports)]

use pyo3::prelude::*;
use pyo3::types::{PyDict, PyTuple};
use base64::Engine;
use sha2::Digest;
use std::collections::HashMap;
use std::collections::HashSet;

fn __rextio_checked_add(a: i64, b: i64) -> PyResult<i64> {
    a.checked_add(b).ok_or_else(|| pyo3::exceptions::PyOverflowError::new_err("integer overflow"))
}

fn __rextio_checked_mul(a: i64, b: i64) -> PyResult<i64> {
    a.checked_mul(b).ok_or_else(|| pyo3::exceptions::PyOverflowError::new_err("integer overflow"))
}


fn rextio_call_python_runtime(
    py: Python<'_>,
    module_name: &str,
    attr_path: &[&str],
    args: &Bound<'_, PyTuple>,
    kwargs: Option<&Bound<'_, PyDict>>,
) -> PyResult<Py<PyAny>> {
    let module = PyModule::import(py, module_name)?;
    let mut target = module.getattr(attr_path[0])?;
    for attr in &attr_path[1..] {
        target = target.getattr(*attr)?;
    }
    let value = target.call(args, kwargs)?;
    Ok(value.unbind())
}

#[pyfunction]
fn app__at(xs: Vec<i64>, i: i64) -> PyResult<i64> {
    return Ok({ let __rextio_seq_1 = &xs; let __rextio_len_3 = __rextio_seq_1.len() as i64; let __rextio_index_2 = (i) as i64; let __rextio_index_2 = if __rextio_index_2 < 0 { __rextio_index_2.checked_add(__rextio_len_3) } else { Some(__rextio_index_2) }; (match __rextio_index_2 { Some(__rextio_bound_4) if __rextio_bound_4 >= 0 && __rextio_bound_4 < __rextio_len_3 => __rextio_seq_1.get(__rextio_bound_4 as usize).cloned(), _ => None }).ok_or_else(|| pyo3::exceptions::PyIndexError::new_err("list index out of range"))? });
}

#[pyfunction]
fn app__classify(n: i64) -> PyResult<String> {
    if n > 0 {
        return Ok(String::from("positive"));
    }
    if n < 0 {
        return Ok(String::from("negative"));
    }
    return Ok(String::from("zero"));
}

#[pyfunction]
fn app__doubled(xs: Vec<i64>) -> PyResult<Vec<i64>> {
    return Ok({
    let mut __rextio_list_1 = Vec::new();
    for x in xs.iter().cloned() {
        __rextio_list_1.push(__rextio_checked_mul(x, 2)?);
    }
    __rextio_list_1
});
}

#[pyfunction]
fn app__lookup(scores: HashMap<String, i64>, key: String) -> PyResult<i64> {
    return Ok({ let __rextio_map_1 = &scores; let __rextio_key_2 = key; __rextio_map_1.get(&__rextio_key_2).cloned().ok_or_else(|| pyo3::exceptions::PyKeyError::new_err(__rextio_key_2.clone()))? });
}

#[pyfunction]
fn app__total(xs: Vec<i64>) -> PyResult<i64> {
    let mut acc = 0;
    for x in xs.iter().cloned() {
        acc = __rextio_checked_add(acc, x)?;
    }
    return Ok(acc);
}

#[pyfunction]
fn app__sum_total(xs: Vec<i64>) -> PyResult<i64> {
    return Ok(__rextio_checked_add(app__total(xs.clone())?, 1)?);
}

#[pymodule]
fn _rextio_native(m: &Bound<'_, PyModule>) -> PyResult<()> {
    m.add_function(wrap_pyfunction!(app__at, m)?)?;
    m.add_function(wrap_pyfunction!(app__classify, m)?)?;
    m.add_function(wrap_pyfunction!(app__doubled, m)?)?;
    m.add_function(wrap_pyfunction!(app__lookup, m)?)?;
    m.add_function(wrap_pyfunction!(app__total, m)?)?;
    m.add_function(wrap_pyfunction!(app__sum_total, m)?)?;
    Ok(())
}
