"""The Python dispatcher for the Rust-``main`` executable's subprocess hybrid.

Phase 2 of the native Rust executable backend lets the standalone binary call a
project function left on the *Python fallback* -- one rejected from the native
subset (RXT072) or never a native candidate (RXT070) -- by delegating it to an
external CPython process. This module renders that dispatcher: a small,
self-contained Python program shipped next to the binary that the binary launches
once and talks to over stdio. (A runtime-shim function -- the RXT080 PyO3 path --
is *not* delegated: a native entry that depends on one is rejected, not built, so
delegation never silently changes shim semantics.)

Wire protocol (newline-delimited JSON, one message per line):

* request  (binary -> dispatcher):  ``{"call": "<qualname>", "args": [<arg>, ...]}``
* success  (dispatcher -> binary):  ``{"ok": <result>}``
* error    (dispatcher -> binary):  ``{"error": {"type": "<Exc>", "message": "<str>"}}``

Delegated arguments *and results* are immutable scalars (``int``/``float``/
``bool``/``str``/``None``). A mutable container (``list``/``dict``/``set``) is not
delegated in either direction: it crosses the wire by value (a JSON copy), which
severs the aliasing CPython preserves -- a callee's in-place mutation of an
argument, or the native caller's mutation of a returned container that aliased
Python state, would silently diverge. Non-finite floats and ``bytes``/``tuple``/
``dict``/``list``/``set`` are not carried (the former is rejected on both sides; the
latter need a tagged, reference-preserving encoding and are a follow-up). Only the
functions in the generated allow-list may be called, so a corrupt or unexpected
request cannot execute arbitrary code.
"""

from __future__ import annotations

import json

# Bump when the wire protocol changes so the Rust client and dispatcher agree.
PROTOCOL_VERSION = 1

# The generated dispatcher is shipped under this stem. The ``_rextio_`` prefix
# keeps a project module named ``dispatcher`` from colliding with (and overwriting)
# it when the project source is reconstructed into the runtime directory, and no
# stdlib module can shadow it.
DISPATCHER_STEM = "_rextio_dispatcher"


def render_dispatcher_script(allowed_qualnames: list[str]) -> str:
    """Render the dispatcher program that serves the allow-listed qualnames."""
    allowed_literal = json.dumps(sorted(set(allowed_qualnames)))
    return f'''# Generated by Rextio. Do not edit manually.
"""Rextio subprocess dispatcher (protocol v{PROTOCOL_VERSION}).

Reads newline-delimited JSON call requests on stdin and writes newline-delimited
JSON responses on the wire stdout, one per request. Only the allow-listed
functions may be invoked. See rextio.codegen.subprocess_dispatcher for the
protocol. The wire owns the original stdout: anything a delegated function writes
to stdout/stderr is redirected to this process's stderr so it can never corrupt
the JSON frames the binary parses.
"""

import importlib
import json
import os
import sys

PROTOCOL_VERSION = {PROTOCOL_VERSION}
_ALLOWED = frozenset({allowed_literal})


def _ensure_rextio():
    # The reconstructed project modules `import rextio` for its decorators. Prefer
    # the real package when it is importable; otherwise install a minimal no-op stub
    # so the modules still import under a stripped or bundled interpreter that has
    # no rextio installed (the decorators are markers -- identity is faithful here).
    try:
        import rextio  # noqa: F401
        return
    except ImportError:
        pass
    import types

    stub = types.ModuleType("rextio")

    def _identity(*args, **kwargs):
        if len(args) == 1 and not kwargs and callable(args[0]):
            return args[0]

        def _wrap(func):
            return func

        return _wrap

    stub.native = _identity
    stub.exempt = _identity
    sys.modules["rextio"] = stub


def _resolve(qualname):
    module_name, _, func_name = qualname.rpartition(".")
    if not module_name:
        raise LookupError("call target must be a dotted qualname: " + repr(qualname))
    module = importlib.import_module(module_name)
    return getattr(module, func_name)


def _exc_frame(exc):
    # str(exc) runs a user-defined __str__, which may itself raise; never let that
    # kill the dispatcher while it is building an error frame.
    try:
        message = str(exc)
    except BaseException:  # noqa: BLE001 -- a __str__ that raises must not escape
        message = "<exception message unavailable>"
    return {{"error": {{"type": type(exc).__name__, "message": message}}}}


def _handle(request):
    qualname = request.get("call")
    if qualname not in _ALLOWED:
        return {{"error": {{"type": "LookupError", "message": "call not permitted: " + repr(qualname)}}}}
    args = request.get("args", [])
    try:
        result = _resolve(qualname)(*args)
    except BaseException as exc:  # noqa: BLE001 -- forward ANY exception (incl. SystemExit/KeyboardInterrupt) to the caller instead of killing the long-lived dispatcher
        return _exc_frame(exc)
    return {{"ok": result}}


def _serve(line):
    # Turn one request line into a response frame. ANY failure -- malformed JSON, a
    # non-dict request, a handler error, or a json.dumps failure (non-serializable
    # result, a non-finite float under allow_nan=False, RecursionError on a deeply
    # nested result, OverflowError on a huge int) -- becomes an error frame, never
    # an unhandled exception that would kill the long-lived dispatcher.
    try:
        request = json.loads(line)
    except ValueError as exc:
        return json.dumps({{"error": {{"type": "ValueError", "message": "invalid request: " + str(exc)}}}})
    try:
        response = _handle(request)
        return json.dumps(response, allow_nan=False)
    except BaseException as exc:  # noqa: BLE001 -- a single request must never kill the loop
        try:
            return json.dumps(_exc_frame(exc))
        except BaseException:  # noqa: BLE001 -- last-resort constant frame
            return '{{"error": {{"type": "RuntimeError", "message": "unrecoverable dispatcher error"}}}}'


def main():
    # Reserve the original stdout for the wire protocol, then point fd 1 (and the
    # Python-level stdout) at stderr so a delegated function's output cannot corrupt
    # the JSON frames. Delegated output is therefore visible on the binary's stderr.
    protocol = os.fdopen(os.dup(1), "w", buffering=1)
    os.dup2(2, 1)
    sys.stdout = sys.stderr
    # Make rextio importable for the reconstructed modules AFTER the redirect, so a
    # real rextio package's import-time output can never land on the protocol stream.
    _ensure_rextio()
    for line in sys.stdin:
        line = line.strip()
        if not line:
            continue
        frame = _serve(line)
        protocol.write(frame)
        protocol.write("\\n")
        protocol.flush()


if __name__ == "__main__":
    main()
'''
