"""The Python dispatcher for the Rust-``main`` executable's subprocess hybrid.

Phase 2 of the native Rust executable backend lets the standalone binary call
functions that are *not* direct-native (runtime-shim / Python fallback) by
delegating them to an external CPython process. This module renders that
dispatcher: a small, self-contained Python program shipped next to the binary
that the binary launches once and talks to over stdio.

Wire protocol (newline-delimited JSON, one message per line):

* request  (binary -> dispatcher):  ``{"call": "<qualname>", "args": [<arg>, ...]}``
* success  (dispatcher -> binary):  ``{"ok": <result>}``
* error    (dispatcher -> binary):  ``{"error": {"type": "<Exc>", "message": "<str>"}}``

Arguments and results are the JSON encodings of the Rextio-supported value types
that JSON represents directly (``int``/``float``/``bool``/``str``/``None``/
``list``/``dict``). ``bytes`` and ``tuple`` need a tagged encoding and are a
follow-up. Only the functions in the generated allow-list may be called, so a
corrupt or unexpected request cannot execute arbitrary code.
"""

from __future__ import annotations

import json

# Bump when the wire protocol changes so the Rust client and dispatcher agree.
PROTOCOL_VERSION = 1


def render_dispatcher_script(allowed_qualnames: list[str]) -> str:
    """Render the dispatcher program that serves the allow-listed qualnames."""
    allowed_literal = json.dumps(sorted(set(allowed_qualnames)))
    return f'''# Generated by Rextio. Do not edit manually.
"""Rextio subprocess dispatcher (protocol v{PROTOCOL_VERSION}).

Reads newline-delimited JSON call requests on stdin and writes newline-delimited
JSON responses on stdout, one per request. Only the allow-listed functions may be
invoked. See rextio.codegen.subprocess_dispatcher for the protocol.
"""

import importlib
import json
import sys

PROTOCOL_VERSION = {PROTOCOL_VERSION}
_ALLOWED = frozenset({allowed_literal})


def _resolve(qualname):
    module_name, _, func_name = qualname.rpartition(".")
    if not module_name:
        raise LookupError("call target must be a dotted qualname: " + repr(qualname))
    module = importlib.import_module(module_name)
    return getattr(module, func_name)


def _handle(request):
    qualname = request.get("call")
    if qualname not in _ALLOWED:
        return {{"error": {{"type": "LookupError", "message": "call not permitted: " + repr(qualname)}}}}
    args = request.get("args", [])
    try:
        result = _resolve(qualname)(*args)
    except Exception as exc:  # noqa: BLE001 -- forward any Python exception to the caller
        return {{"error": {{"type": type(exc).__name__, "message": str(exc)}}}}
    return {{"ok": result}}


def main():
    out = sys.stdout
    for line in sys.stdin:
        line = line.strip()
        if not line:
            continue
        try:
            request = json.loads(line)
        except ValueError as exc:
            response = {{"error": {{"type": "ValueError", "message": "invalid request: " + str(exc)}}}}
        else:
            response = _handle(request)
        out.write(json.dumps(response))
        out.write("\\n")
        out.flush()


if __name__ == "__main__":
    main()
'''
