"""The Python dispatcher for the Rust-``main`` executable's subprocess hybrid.

Phase 2 of the native Rust executable backend lets the standalone binary call
functions that are *not* direct-native (runtime-shim / Python fallback) by
delegating them to an external CPython process. This module renders that
dispatcher: a small, self-contained Python program shipped next to the binary
that the binary launches once and talks to over stdio.

Wire protocol (newline-delimited JSON, one message per line):

* request  (binary -> dispatcher):  ``{"call": "<qualname>", "args": [<arg>, ...]}``
* success  (dispatcher -> binary):  ``{"ok": <result>}``
* error    (dispatcher -> binary):  ``{"error": {"type": "<Exc>", "message": "<str>"}}``

Arguments and results are the JSON encodings of the Rextio-supported value types
that JSON represents directly (``int``/``float``/``bool``/``str``/``None``/
``list``/``dict``). ``bytes`` and ``tuple`` need a tagged encoding and are a
follow-up. Only the functions in the generated allow-list may be called, so a
corrupt or unexpected request cannot execute arbitrary code.
"""

from __future__ import annotations

import json

# Bump when the wire protocol changes so the Rust client and dispatcher agree.
PROTOCOL_VERSION = 1


def render_dispatcher_script(allowed_qualnames: list[str]) -> str:
    """Render the dispatcher program that serves the allow-listed qualnames."""
    allowed_literal = json.dumps(sorted(set(allowed_qualnames)))
    return f'''# Generated by Rextio. Do not edit manually.
"""Rextio subprocess dispatcher (protocol v{PROTOCOL_VERSION}).

Reads newline-delimited JSON call requests on stdin and writes newline-delimited
JSON responses on the wire stdout, one per request. Only the allow-listed
functions may be invoked. See rextio.codegen.subprocess_dispatcher for the
protocol. The wire owns the original stdout: anything a delegated function writes
to stdout/stderr is redirected to this process's stderr so it can never corrupt
the JSON frames the binary parses.
"""

import importlib
import json
import os
import sys

PROTOCOL_VERSION = {PROTOCOL_VERSION}
_ALLOWED = frozenset({allowed_literal})


def _ensure_rextio():
    # The reconstructed project modules `import rextio` for its decorators. Prefer
    # the real package when it is importable; otherwise install a minimal no-op stub
    # so the modules still import under a stripped or bundled interpreter that has
    # no rextio installed (the decorators are markers -- identity is faithful here).
    try:
        import rextio  # noqa: F401
        return
    except ImportError:
        pass
    import types

    stub = types.ModuleType("rextio")

    def _identity(*args, **kwargs):
        if len(args) == 1 and not kwargs and callable(args[0]):
            return args[0]

        def _wrap(func):
            return func

        return _wrap

    stub.native = _identity
    stub.exempt = _identity
    sys.modules["rextio"] = stub


_ensure_rextio()


def _resolve(qualname):
    module_name, _, func_name = qualname.rpartition(".")
    if not module_name:
        raise LookupError("call target must be a dotted qualname: " + repr(qualname))
    module = importlib.import_module(module_name)
    return getattr(module, func_name)


def _handle(request):
    qualname = request.get("call")
    if qualname not in _ALLOWED:
        return {{"error": {{"type": "LookupError", "message": "call not permitted: " + repr(qualname)}}}}
    args = request.get("args", [])
    try:
        result = _resolve(qualname)(*args)
    except BaseException as exc:  # noqa: BLE001 -- forward ANY exception (incl. SystemExit/KeyboardInterrupt) to the caller instead of killing the long-lived dispatcher
        return {{"error": {{"type": type(exc).__name__, "message": str(exc)}}}}
    return {{"ok": result}}


def main():
    # Reserve the original stdout for the wire protocol, then point fd 1 (and the
    # Python-level stdout) at stderr so a delegated function's output cannot corrupt
    # the JSON frames. Delegated output is therefore visible on the binary's stderr.
    protocol = os.fdopen(os.dup(1), "w", buffering=1)
    os.dup2(2, 1)
    sys.stdout = sys.stderr
    for line in sys.stdin:
        line = line.strip()
        if not line:
            continue
        try:
            request = json.loads(line)
        except ValueError as exc:
            response = {{"error": {{"type": "ValueError", "message": "invalid request: " + str(exc)}}}}
        else:
            response = _handle(request)
        try:
            # allow_nan=False keeps non-finite floats off the wire (strict JSON the
            # Rust client can parse); a non-serializable result becomes an error
            # frame instead of an unhandled exception that would kill the dispatcher.
            frame = json.dumps(response, allow_nan=False)
        except (ValueError, TypeError) as exc:
            frame = json.dumps(
                {{"error": {{"type": "TypeError", "message": "result is not JSON-serializable: " + str(exc)}}}}
            )
        protocol.write(frame)
        protocol.write("\\n")
        protocol.flush()


if __name__ == "__main__":
    main()
'''
